### ISSUE TITLE
are the http request/response of casablanca multithreaded in a COM STA object ?i.e do the task of casablanca run parallel in a COM STA object ? 

### ISSUE THREAD

**Issue by stephane78** [Microsoft/cpprestsdk#10]
Hi,
I make http request/response (and upload of file too ) with casablanca in a COM STA object. (an outlook addin)
it seems to block the software ( I cannot do something else and must wait,it freezes).

the following code is in a send(...) function in my STA COM object:

client.request(requete).then([this](task<http_response> responseTask)
                {
                    http_response response;

                    try
                    {
                        
                        response = responseTask.get();
                    }
                    catch (const http_exception &e)
                    ...

does casablanca run well and parallel in a COM STA object ? shall I do something more to run my tasks parallel ?

or should I use atlserver library(or winhttp) and win32 instead of casablanca for http requests and multithreading(win32) in my COM object ?
(I will still use casablanca to parse the json in the responses.)

**Comment by stephane78** [comment]
I use C++ ATL library and casablanca.

**Comment by stephane78** [comment]
Ok I have solved my multitasking problem with casablanca.I have removed the external wait and made some modifications and have used windows messages and postmessage to a window (of the main thread ) of my COM object to signalize the end of my secondary thread...

**Comment by ras0219-msft** [comment]
Thanks for posting the solution.
