### ISSUE TITLE
New Boost version may have incorrect or missing dependencies and imported targets

### ISSUE THREAD

**Issue by LeCrucien** [Microsoft/cpprestsdk#1010]
I have been trying to build Casablanca on Ubuntu 18.04 and linking it with boost-1.67.0 ( related files are located in /usr/local/include/boost and /usr/local/lib) . So far I have not been successful. I have OpenSSL 1.1.1 installed ( related files are located in /usr/local/include/openssl and /usr/local/lib). What am I missing? I appreciate any help. Thank you!

 cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=0
-- Setting gcc options
-- Found websocketpp version 0.7.0 on system
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  Release/cmake/cpprest_find_boost.cmake:47 (find_package)
  Release/cmake/cpprest_find_websocketpp.cmake:17 (cpprest_find_boost)
  Release/src/CMakeLists.txt:68 (cpprest_find_websocketpp)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  Release/cmake/cpprest_find_boost.cmake:47 (find_package)
  Release/cmake/cpprest_find_websocketpp.cmake:17 (cpprest_find_boost)
  Release/src/CMakeLists.txt:68 (cpprest_find_websocketpp)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  Release/cmake/cpprest_find_boost.cmake:47 (find_package)
  Release/cmake/cpprest_find_websocketpp.cmake:17 (cpprest_find_boost)
  Release/src/CMakeLists.txt:68 (cpprest_find_websocketpp)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  Release/cmake/cpprest_find_boost.cmake:47 (find_package)
  Release/cmake/cpprest_find_websocketpp.cmake:17 (cpprest_find_boost)
  Release/src/CMakeLists.txt:68 (cpprest_find_websocketpp)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  Release/cmake/cpprest_find_boost.cmake:47 (find_package)
  Release/cmake/cpprest_find_websocketpp.cmake:17 (cpprest_find_boost)
  Release/src/CMakeLists.txt:68 (cpprest_find_websocketpp)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  Release/cmake/cpprest_find_boost.cmake:47 (find_package)
  Release/cmake/cpprest_find_websocketpp.cmake:17 (cpprest_find_boost)
  Release/src/CMakeLists.txt:68 (cpprest_find_websocketpp)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  Release/cmake/cpprest_find_boost.cmake:47 (find_package)
  Release/cmake/cpprest_find_websocketpp.cmake:17 (cpprest_find_boost)
  Release/src/CMakeLists.txt:68 (cpprest_find_websocketpp)

CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  Release/cmake/cpprest_find_boost.cmake:47 (find_package)
  Release/cmake/cpprest_find_websocketpp.cmake:17 (cpprest_find_boost)
  Release/src/CMakeLists.txt:68 (cpprest_find_websocketpp)

-- Boost version: 1.69.0
-- Found the following Boost libraries:
--   random
--   system
--   thread
--   filesystem
--   chrono
--   atomic
--   date_time
--   regex
-- Added test library httpclient_test
-- Added test library httplistener_test
-- Added test library json_test
-- Added test library pplx_test
-- Added test library streams_test
-- Added test library uri_test
-- Added test library utils_test
-- Added test library websocketsclient_test
-- Configuring done
-- Generating done
-- Build files have been written to: /home/paul/Downloads/cpprestsdk-master/build.release

**Comment by BillyONeal** [comment]
I don't see anything there that indicates a failure. You got `-- Build files have been written to: /home/paul/Downloads/cpprestsdk-master/build.release` which means cmake succeeded. The warnings that are emitted are because the copy of Boost you're using is newer than the copy of cmake you're using, and the static dependency map that shipped inside cmake doesn't know about that version yet.
