### ISSUE TITLE
Linking Error | SSL

### ISSUE THREAD

**Issue by LeCrucien** [Microsoft/cpprestsdk#1011]
/usr/local/lib//libcpprest.a(http_server_asio.cpp.o): In function `(anonymous namespace)::asio_server_connection::deref()':
http_server_asio.cpp:(.text+0x72d7): undefined reference to `SSL_get_ex_data'
http_server_asio.cpp:(.text+0x72e7): undefined reference to `SSL_get_ex_data'
http_server_asio.cpp:(.text+0x7302): undefined reference to `SSL_set_ex_data'
http_server_asio.cpp:(.text+0x7314): undefined reference to `SSL_free'
http_server_asio.cpp:(.text+0x7335): undefined reference to `SSL_CTX_get_default_passwd_cb_userdata'
http_server_asio.cpp:(.text+0x734d): undefined reference to `SSL_CTX_set_default_passwd_cb_userdata'
http_server_asio.cpp:(.text+0x7357): undefined reference to `SSL_CTX_get_ex_data'
http_server_asio.cpp:(.text+0x7366): undefined reference to `SSL_CTX_get_ex_data'
http_server_asio.cpp:(.text+0x7380): undefined reference to `SSL_CTX_set_ex_data'
http_server_asio.cpp:(.text+0x7388): undefined reference to `SSL_CTX_free'
/usr/local/lib//libcpprest.a(http_server_asio.cpp.o): In function `(anonymous namespace)::asio_server_connection::handle_http_line(boost::system::error_code const&)':
http_server_asio.cpp:(.text+0x11903): undefined reference to `SSL_get_ex_data'
http_server_asio.cpp:(.text+0x11913): undefined reference to `SSL_get_ex_data'
http_server_asio.cpp:(.text+0x1192e): undefined reference to `SSL_set_ex_data'
http_server_asio.cpp:(.text+0x11940): undefined reference to `SSL_free'
http_server_asio.cpp:(.text+0x11961): undefined reference to `SSL_CTX_get_default_passwd_cb_userdata'
http_server_asio.cpp:(.text+0x11979): undefined reference to `SSL_CTX_set_default_passwd_cb_userdata'
http_server_asio.cpp:(.text+0x11983): undefined reference to `SSL_CTX_get_ex_data'
http_server_asio.cpp:(.text+0x11992): undefined reference to `SSL_CTX_get_ex_data'
http_server_asio.cpp:(.text+0x119ac): undefined reference to `SSL_CTX_set_ex_data'
http_server_asio.cpp:(.text+0x119b4): undefined reference to `SSL_CTX_free'
/usr/local/lib//libcpprest.a(http_server_asio.cpp.o): In function `(anonymous namespace)::hostport_listener::on_accept(std::unique_ptr<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, std::default_delete<boost::asio::basic_stream_socket<boost::asio::ip::tcp> > >, boost::system::error_code const&)':
http_server_asio.cpp:(.text+0x160a3): undefined reference to `TLS_method'
http_server_asio.cpp:(.text+0x160ab): undefined reference to `SSL_CTX_new'
http_server_asio.cpp:(.text+0x160cb): undefined reference to `SSL_CTX_set_options'
http_server_asio.cpp:(.text+0x160f0): undefined reference to `SSL_CTX_get_default_passwd_cb_userdata'
http_server_asio.cpp:(.text+0x16108): undefined reference to `SSL_CTX_set_default_passwd_cb_userdata'
http_server_asio.cpp:(.text+0x16112): undefined reference to `SSL_CTX_get_ex_data'
http_server_asio.cpp:(.text+0x16121): undefined reference to `SSL_CTX_get_ex_data'
http_server_asio.cpp:(.text+0x1613b): undefined reference to `SSL_CTX_set_ex_data'
http_server_asio.cpp:(.text+0x16143): undefined reference to `SSL_CTX_free'
http_server_asio.cpp:(.text+0x161b0): undefined reference to `SSL_new'
http_server_asio.cpp:(.text+0x161d8): undefined reference to `SSL_ctrl'
http_server_asio.cpp:(.text+0x161f4): undefined reference to `SSL_ctrl'
http_server_asio.cpp:(.text+0x16209): undefined reference to `SSL_ctrl'
http_server_asio.cpp:(.text+0x1623b): undefined reference to `SSL_set_bio'
/usr/local/lib//libcpprest.a(http_server_asio.cpp.o): In function `(anonymous namespace)::asio_server_connection::cancel_sending_response_with_error(web::http::http_response const&, std::__exception_ptr::exception_ptr const&)':
http_server_asio.cpp:(.text+0x1d87f): undefined reference to `SSL_get_ex_data'
http_server_asio.cpp:(.text+0x1d88f): undefined reference to `SSL_get_ex_data'
http_server_asio.cpp:(.text+0x1d8aa): undefined reference to `SSL_set_ex_data'
http_server_asio.cpp:(.text+0x1d8bc): undefined reference to `SSL_free'
http_server_asio.cpp:(.text+0x1d8de): undefined reference to `SSL_CTX_get_default_passwd_cb_userdata'
http_server_asio.cpp:(.text+0x1d8f7): undefined reference to `SSL_CTX_set_default_passwd_cb_userdata'
http_server_asio.cpp:(.text+0x1d902): undefined reference to `SSL_CTX_get_ex_data'
http_server_asio.cpp:(.text+0x1d912): undefined reference to `SSL_CTX_get_ex_data'
http_server_asio.cpp:(.text+0x1d92d): undefined reference to `SSL_CTX_set_ex_data'
http_server_asio.cpp:(.text+0x1d936): undefined reference to `SSL_CTX_free'
/usr/local/lib//libcpprest.a(http_server_asio.cpp.o): In function `boost::asio::ssl::detail::engine::do_accept(void*, unsigned long)':
http_server_asio.cpp:(.text._ZN5boost4asio3ssl6detail6engine9do_acceptEPvm[_ZN5boost4asio3ssl6detail6engine9do_acceptEPvm]+0x4): undefined reference to `SSL_accept'
/usr/local/lib//libcpprest.a(http_server_asio.cpp.o): In function `boost::asio::ssl::detail::engine::do_connect(void*, unsigned long)':
http_server_asio.cpp:(.text._ZN5boost4asio3ssl6detail6engine10do_connectEPvm[_ZN5boost4asio3ssl6detail6engine10do_connectEPvm]+0x4): undefined reference to `SSL_connect'
/usr/local/lib//libcpprest.a(http_server_asio.cpp.o): In function `boost::asio::ssl::detail::engine::do_read(void*, unsigned long)':
http_server_asio.cpp:(.text._ZN5boost4asio3ssl6detail6engine7do_readEPvm[_ZN5boost4asio3ssl6detail6engine7do_readEPvm]+0x14): undefined reference to `SSL_read'
/usr/local/lib//libcpprest.a(http_server_asio.cpp.o): In function `boost::asio::ssl::detail::engine::do_write(void*, unsigned long)':
http_server_asio.cpp:(.text._ZN5boost4asio3ssl6detail6engine8do_writeEPvm[_ZN5boost4asio3ssl6detail6engine8do_writeEPvm]+0x14): undefined reference to `SSL_write'
/usr/local/lib//libcpprest.a(http_server_asio.cpp.o): In function `boost::asio::ssl::detail::engine::~engine()':
http_server_asio.cpp:(.text._ZN5boost4asio3ssl6detail6engineD2Ev[_ZN5boost4asio3ssl6detail6engineD5Ev]+0xa): undefined reference to `SSL_get_ex_data'
http_server_asio.cpp:(.text._ZN5boost4asio3ssl6detail6engineD2Ev[_ZN5boost4asio3ssl6detail6engineD5Ev]+0x19): undefined reference to `SSL_get_ex_data'
http_server_asio.cpp:(.text._ZN5boost4asio3ssl6detail6engineD2Ev[_ZN5boost4asio3ssl6detail6engineD5Ev]+0x33): undefined reference to `SSL_set_ex_data'
http_server_asio.cpp:(.text._ZN5boost4asio3ssl6detail6engineD2Ev[_ZN5boost4asio3ssl6detail6engineD5Ev]+0x45): undefined reference to `SSL_free'
/usr/local/lib//libcpprest.a(http_server_asio.cpp.o): In function `boost::asio::ssl::detail::engine::map_error_code(boost::system::error_code&) const':
http_server_asio.cpp:(.text._ZNK5boost4asio3ssl6detail6engine14map_error_codeERNS_6system10error_codeE[_ZNK5boost4asio3ssl6detail6engine14map_error_codeERNS_6system10error_codeE]+0x5b): undefined reference to `SSL_get_shutdown'
/usr/local/lib//libcpprest.a(http_server_asio.cpp.o): In function `boost::asio::ssl::detail::engine::perform(int (boost::asio::ssl::detail::engine::*)(void*, unsigned long), void*, unsigned long, boost::system::error_code&, unsigned long*)':
http_server_asio.cpp:(.text._ZN5boost4asio3ssl6detail6engine7performEMS3_FiPvmES4_mRNS_6system10error_codeEPm[_ZN5boost4asio3ssl6detail6engine7performEMS3_FiPvmES4_mRNS_6system10error_codeEPm]+0x5c): undefined reference to `SSL_get_error'
http_server_asio.cpp:(.text._ZN5boost4asio3ssl6detail6engine7performEMS3_FiPvmES4_mRNS_6system10error_codeEPm[_ZN5boost4asio3ssl6detail6engine7performEMS3_FiPvmES4_mRNS_6system10error_codeEPm]+0xb9): undefined reference to `SSL_get_shutdown'
collect2: error: ld returned 1 exit status

**Comment by BillyONeal** [comment]
It looks like you need the openssl library put after libcpprest,a?
