### ISSUE TITLE
Can't compile on Visual Studio 2017 (json.h issue)

### ISSUE THREAD

**Issue by aowrew** [Microsoft/cpprestsdk#1012]
Hello,

I've created a project on linux using cpprestsdk and now I'm trying to run it in VS2017 on windows 10. The project runs fine on linux with a minimal cmake configuration.
I've succesfully installed the library on windows through vcpkg using the guide and Visual Studio correctly recognizes the header files, however, when I try to build I'm presented with multiple errors (these are just from one file, but all are related to the json header file) -

```
1>------ Build started: Project: AIPO, Configuration: Debug x64 ------
1>client.cpp
1>c:\repos\po-ai-cpp\lib\client.cpp(5): error C2248: 'web::json::value::operator []': cannot access private member declared in class 'web::json::value'
1>c:\repos\vcpkg\installed\x64-windows\include\cpprest\json.h(654): note: see declaration of 'web::json::value::operator []'
1>c:\repos\vcpkg\installed\x64-windows\include\cpprest\json.h(71): note: see declaration of 'web::json::value'
1>c:\repos\po-ai-cpp\lib\client.cpp(25): error C2679: binary '[': no operator found which takes a right-hand operand of type 'const char [14]' (or there is no acceptable conversion)
1>c:\repos\vcpkg\installed\x64-windows\include\cpprest\http_headers.h(226): note: could be 'utility::string_t &web::http::http_headers::operator [](const web::http::http_headers::key_type &)'
1>c:\repos\po-ai-cpp\lib\client.cpp(25): note: while trying to match the argument list '(web::http::http_headers, const char [14])'
```

After inspecting the header file it looks like the [] operator is declared private when _WIN32 is defined and I can see that _WIN32 is defined in minwindef.h and pplx.h, but that's as far as I'm able to debug. 

Is there any additional configuration needed to be done for the project to run in VS2017? Have I installed something incorrectly? I've added the project to VS by importing from an existing source and hadn't configured anything else.

Regards,
Alex

**Comment by etm** [comment]
Same errors here.

**Comment by aowrew** [comment]
@etm many thanks for the suggestion - it was indeed a case where I've been using std::string instead of utility::string_t.
