### ISSUE TITLE
Need i386 build for iOS simulator build if armv7 slice is used

### ISSUE THREAD

**Issue by mobileben** [Microsoft/cpprestsdk#1015]
I will make this change, but just creating the issue for it.

The i386 slice will be required at a point in the following circumstances:

- If you support armv7
- If you are doing a build that is NOT building for the active architecture.

It turns out that armv7 maps the simulator to i386. Presumably any 32-bit architecture will get mapped the corresponding Intel version.

**Comment by damienhocking** [comment]
I haven't been keeping up with the issues list but we regularly compile and use cpprest on Arm v7, specifically Tegra K1.  Do you need help?

Damien

**Comment by mobileben** [comment]
@damienhocking no worries. This is an iOS/Xcode thing. It's pretty straight forward to do. Although now looking at it some more, it involves an external dependency which is cloned during the configure process.

**Comment by damienhocking** [comment]
Cool

**Comment by mobileben** [comment]
@leetal I believe https://github.com/leetal/ios-cmake is yours. 

The one issue here is that we need to have a variant for a simulator build that includes i386 and x86_64.

The reason for this is that if you are have an armv7 as a target architecture *and* you build a target that builds all architectures for a simulator build, then it wants to build i386 as well.

Interestingly you vary OS and OS64 as follows (note I grabbed this from the comments section, but the code has those settings).

```
#    OS = armv7 armv7s arm64 arm64e
#    OS64 = arm64 arm64e
```

But SIMULATOR and SIMULATOR64 do not follow suit.

```
#    SIMULATOR = i386
#    SIMULATOR64 = x86_64
```

Can we just make SIMULATOR have both i386 and x86_64?

I'll add an issue related to this there.

**Comment by mobileben** [comment]
PR was merged so closing
