### ISSUE TITLE
Building latest on Windows, getting websocket errors

### ISSUE THREAD

**Issue by damienhocking** [Microsoft/cpprestsdk#1059]
Hi, we build cpprest from the ground up as part of our build system with a custom Boost.  We're upgrading to the latest release and we can't get the build to go through.  Our cmake command on Windows is:

C:\Program Files\CMake\bin\cmake.exe .. -G"Visual Studio 15 2017 Win64" -DWEBSOCKETCPP_DIR=C:\projects\cpprestsdk-master\Release\src\websockets -DZLIB_LIBRARY=C:\projects\zlib\zlib\build\Release -DZLIB_INCLUDE_DIR=c:\projects\zlib\zlib -DBOOST_ROOT=c:\projects\boost_1_69_0\win64debug  -DCMAKE_BUILD_TYPE=Debug

But we get this:  

CMake Error at cmake/cpprest_find_websocketpp.cmake:14 (message):
  -- websocketpp not found and embedded version not present; try `git
  submodule update --init` and run CMake again
Call Stack (most recent call first):
  tests/functional/websockets/CMakeLists.txt:10 (cpprest_find_websocketpp)

What are we doing wrong?  We have the websocket code as part of cpprest now, correct?  The error log is complaining about pthread.h so is there a Windows flag we need to add?

Damien

**Comment by c72578** [comment]
Dear Damien.
please check, if the websocketpp files are there. In your case they should be in the following subfolder:
`C:\projects\cpprestsdk-master\Release\src\libs\websocketpp\`

Did you already run `git submodule update --init` as suggested above, from the `C:\projects\cpprestsdk-master\` folder?

Alternatively you can get current websocketpp from https://github.com/zaphoyd/websocketpp and use it.

**Comment by damienhocking** [comment]
I messed up, I was using a zip download.  Doing a git clone and a submodule update and it was fine.  I have a separate link problem with Boost lib names but I'll open a separate issue.

**Comment by SaralaSewwandi** [comment]
before buiilding the cpprestsdk install websocketpp using vcpkg
vcpkg install --triplet x64-windows zlib openssl boost-system boost-date-time boost-regex boost-interprocess websocketpp brotli

Full restcppsdk build guide & source code
https://sageai.blogspot.com/2020/12/how-to-build-cpprestsdk-using-vcpkg-in.html

**Comment by SaralaSewwandi** [comment]
> Hi, we build cpprest from the ground up as part of our build system with a custom Boost. We're upgrading to the latest release and we can't get the build to go through. Our cmake command on Windows is:
> 
> C:\Program Files\CMake\bin\cmake.exe .. -G"Visual Studio 15 2017 Win64" -DWEBSOCKETCPP_DIR=C:\projects\cpprestsdk-master\Release\src\websockets -DZLIB_LIBRARY=C:\projects\zlib\zlib\build\Release -DZLIB_INCLUDE_DIR=c:\projects\zlib\zlib -DBOOST_ROOT=c:\projects\boost_1_69_0\win64debug -DCMAKE_BUILD_TYPE=Debug
> 
> But we get this:
> 
> CMake Error at cmake/cpprest_find_websocketpp.cmake:14 (message):
> -- websocketpp not found and embedded version not present; try `git submodule update --init` and run CMake again
> Call Stack (most recent call first):
> tests/functional/websockets/CMakeLists.txt:10 (cpprest_find_websocketpp)
> 
> What are we doing wrong? We have the websocket code as part of cpprest now, correct? The error log is complaining about pthread.h so is there a Windows flag we need to add?
> 
> Damien

before buiilding the cpprestsdk install websocketpp using vcpkg
vcpkg install --triplet x64-windows zlib openssl boost-system boost-date-time boost-regex boost-interprocess websocketpp brotli

Full restcppsdk build guide & source code
https://sageai.blogspot.com/2020/12/how-to-build-cpprestsdk-using-vcpkg-in.html
