### ISSUE TITLE
msbuild fails to create libraries

### ISSUE THREAD

**Issue by MatrixManAtYrService** [Microsoft/cpprestsdk#107]
When following the windows build instructions, I found that the following line failed with errors and did not produce any binaries:

`msbuild dirs.proj /p:Configuration=Debug /p:Platform=x64 /p:UseEnv=true`

Errors include 
* `error MSB3774: Could not find SDK "Microsoft.VCLibs, Version=14.0`
* `error C2371: 'size_t': redefinition; different basic type`
* `error C2338: This code is for 64-bit size_t.`

I replaced it with this command:

`devenv cpprestsdk140.sln /build "Release|Win32"`

Which also fails to errors, but it does output this line:
`========== Build: 7 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========` 

As it turns out, the libraries I needed were among the 7 successful ones.  Thought I would let somebody know in case the documentation needs updating.

During that build, I noticed the message: **Unknown compiler version - please run the configure tests and report the results**  I sent an email to askcasablanca@microsoft.com about it, but delivery failed:

> 
> Hello,
> 
> I ran across the string in the subject line while building cpprestsdk140.sln, which I cloned from your github repository.  I tried to run the tests it mentions, but couldn’t find any to run (as indicated in the test output).  I have attached files for both the build output and the test output.
> 
> I am building with Visual studio version 14.0.24720.00 Update 1
> I used nuget to grab the project’s dependencies in accordance with your instructions on github
> 
> I thought I’d let you know since that’s what the error says to do.  Let me know if you’d like any more information.

[cpprestsdk140.test.output.txt](https://github.com/Microsoft/cpprestsdk/files/192562/cpprestsdk140.test.output.txt)
[cpprestsdk140.build.output.txt](https://github.com/Microsoft/cpprestsdk/files/192561/cpprestsdk140.build.output.txt)

**Comment by ras0219-msft** [comment]
The Unknown compiler version messages are due to boost, they can be safely ignored.

The failed projects are likely due to missing some VS features such as not having MDD installed. Thank you for the notification, there should probably be a note that some projects will fail if certain components are missing.
