### ISSUE TITLE
how to use std::string as input in json::value::string()?

### ISSUE THREAD

**Issue by chengshuyi** [Microsoft/cpprestsdk#1075]
I read a picture with 1920x1080 size as a std::string. However json::value::string() could not take std::string as input. Below code from json.h file.

```
private:
        // Only used internally by JSON parser.
        static _ASYNCRTIMP value __cdecl string(const std::string &value);
```

So, I use `utility::string_t ustring = utility::conversions::to_string_t(data_string);` to convert std::string to string_t. However this function cost 5 seconds. It costs too much. 

```
utility::string_t ustring = utility::conversions::to_string_t(data_string);
obj['data'] = json::value::string(ustring)
```

And `message.reply(status_codes::OK, json::value(obj));` this function also costs 5 seconds.

Any reply will be appreciated!

**Comment by reneme** [comment]
Hi @chengshuyi,

I guess you are reading an ordinary JPG image (i.e. "binary data") into an `std::string`, right?
In C++, `std::string` conventionally contains text (i.e. "ASCII or UTF-8 encoded (printable) text data"). Now, `string_t` is a platform-dependent typedef (on unix it resolves to `std::string` and on windows to `std::wstring`). Conventionally `std::wstring` contains printable UTF-16 encoded text on Windows.

Long story short: By reading your image into a `std::string` and then converting it (presumably on Windows) to a `string_t` (aka. `std::wstring`) you are actually interpreting your binary image data as printable UTF-8 text that gets re-encoded (inside `utility::conversions::to_string_t`) to UTF-16. This probably explains, why you see the long computation. And on top of that, it probably produces a lot of garbage. 

What you probably want to do is:

1. read your image into a `std::vector<uint8_t>` (i.e. an ordinary binary data buffer)
2. use `utility::conversions::to_base64()` (to encode your binary data as ASCII bytes)
3. add the result of (2) (that is a `std::string_t` containing your base64-encoded image) to your JSON object

**Comment by chengshuyi** [comment]
Thanks for your reply! But it doesn't work. I could specify the program.

1. I use opencv `imwrite` function to load a picture to `Mat`.
2. Then, converting `Mat` to `vector<unsigned char>` by using `imencode()`.
3. Converting `vector<unsigned char>` to `std::string`.
4. Encoding `std::string` by base64 algorithm.
5. Finally, converting encoded `std::string` to `utility::string_t`.

According to your reply, I replace 3, 4 and 5  three steps with `utility::conversions::to_base64()`. However the cost time doesn't  reduce. It still costs 4-5 seconds to finish the function `utility::conversions::to_base64()`. Below is changed code.

```
vector<unsigned char> buff;
imencode('.jpg', pic, buff);   //pic is cv::Mat type.
utility::conversions::to_base64(buff)
```

**Comment by reneme** [comment]
The code you posted makes more sense from a data flow point of view and reflects what I meant with my initial reply.

Regarding performance: How many bytes does your jpg image occupy?
I found this in cpprest's implementation of base64:

```C++
//
// A note on the implementation of BASE64 encoding and decoding:
//
// This is a fairly basic and naive implementation; there is probably a lot of room for
// performance improvement, as well as for adding options such as support for URI-safe base64,
// ignoring CRLF, relaxed validation rules, etc. The decoder is currently pretty strict.
//
```

... and indeed the base64 encoder implementation looks pretty naïve and could most likely be improved substantially.

For the time being, I suggest one of the following ways forward:

1. Find a faster implementation of base64
Maybe you have Qt in your project? (which also contains a base64 encoder) or
you could [pull in libb64](https://stackoverflow.com/questions/29772271/c-opencv-convert-mat-to-base64-and-vice-versa) or any other implementation of base64.
2. Do you actually need to wrap your JPG image into JSON?
Maybe you could just send it as a bare binary file via an HTTP `POST`?

**Comment by chengshuyi** [comment]
> The code you posted makes more sense from a data flow point of view and reflects what I meant with my initial reply.
> 
> Regarding performance: How many bytes does your jpg image occupy?
> I found this in cpprest's implementation of base64:
> 
> ```c++
> //
> // A note on the implementation of BASE64 encoding and decoding:
> //
> // This is a fairly basic and naive implementation; there is probably a lot of room for
> // performance improvement, as well as for adding options such as support for URI-safe base64,
> // ignoring CRLF, relaxed validation rules, etc. The decoder is currently pretty strict.
> //
> ```
> 
> ... and indeed the base64 encoder implementation looks pretty naïve and could most likely be improved substantially.
> 
> For the time being, I suggest one of the following ways forward:
> 
> 1. Find a faster implementation of base64
>    Maybe you have Qt in your project? (which also contains a base64 encoder) or
>    you could [pull in libb64](https://stackoverflow.com/questions/29772271/c-opencv-convert-mat-to-base64-and-vice-versa) or any other implementation of base64.
> 2. Do you actually need to wrap your JPG image into JSON?
>    Maybe you could just send it as a bare binary file via an HTTP `POST`?

Thank you very much. You help me a lot. I compile the same project on different PC and run it on the same PC. The run time is different. One take 5 seconds and the other take less than 1 second. It's confused.

**Comment by reneme** [comment]
> The run time is different. One take 5 seconds and the other take less than 1 second. It's confused.

Did you compile without optimisations on one of the machines?

**Comment by chengshuyi** [comment]
I don't know what is optimizations. However the optimizations, locating at properties->c/c++->optimization, is set to be false.
