### ISSUE TITLE
Failing datetime:parsing_time tests on 32-bit architectures under Linux

### ISSUE THREAD

**Issue by c72578** [Microsoft/cpprestsdk#1090]
- cpprestsdk version: 2.10.12
- The following tests fail on 32-bit architectures (e.g. i686, armv7hl):
<pre>
**** datetime:parsing_time_rfc1123_accepts_each_day FAILED ****
**** datetime:parsing_time_rfc1123_boundary_cases FAILED ****
**** datetime:parsing_time_rfc1123_uses_each_field FAILED ****
**** datetime:parsing_time_rfc1123_max_days FAILED ****
**** datetime:parsing_time_iso8601_boundary_cases FAILED ****
**** datetime:parsing_time_iso8601_uses_each_digit FAILED ****
**** datetime:parsing_time_iso8601_accepts_month_max_days FAILED ****
**** datetime:parsing_time_iso8601_accepts_lowercase_t_z FAILED ****
</pre>
Fedora build logs with failing tests:
i686: https://kojipkgs.fedoraproject.org//work/tasks/335/33790335/build.log
armv7hl: https://kojipkgs.fedoraproject.org//work/tasks/337/33790337/build.log

- Builds for 64-bit architectures are OK and the test pass (e.g. x86_64, aarch64)

**Comment by LocutusOfBorg** [comment]
Possibly related?
```
cd /<<PKGBUILDDIR>>/obj-arm-linux-gnueabihf/Release/src && /usr/bin/c++  -DCPPREST_FORCE_HTTP_CLIENT_ASIO -DCPPREST_FORCE_HTTP_LISTENER_ASIO -DCPPREST_NO_SSL_LEAK_SUPPRESS -Dcpprest_EXPORTS -I/<<PKGBUILDDIR>>/Release/include -I/<<PKGBUILDDIR>>/Release/src/pch  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++11 -fno-strict-aliasing -fPIC   -Werror -pedantic -Wall -Wextra -Wunused-parameter -Wcast-align -Wcast-qual -Wconversion -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-format-attribute -Wmissing-include-dirs -Wpacked -Wredundant-decls -Wunreachable-code -o CMakeFiles/cpprest.dir/utilities/asyncrt_utils.cpp.o -c /<<PKGBUILDDIR>>/Release/src/utilities/asyncrt_utils.cpp
/<<PKGBUILDDIR>>/Release/src/utilities/asyncrt_utils.cpp: In static member function 'static utility::datetime utility::datetime::from_string(const string_t&, utility::datetime::date_format)':
/<<PKGBUILDDIR>>/Release/src/utilities/asyncrt_utils.cpp:1153:21: error: conversion from 'uint64_t' {aka 'long long unsigned int'} to 'time_t' {aka 'long int'} may change value [-Werror=conversion]
             seconds += ntToUnixOffsetSeconds;
             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/Release/src/utilities/asyncrt_utils.cpp:1277:13: error: conversion from 'uint64_t' {aka 'long long unsigned int'} to 'time_t' {aka 'long int'} may change value [-Werror=conversion]
     seconds += ntToUnixOffsetSeconds;
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
[ 11%] Building CXX object Release/src/CMakeFiles/cpprest.dir/utilities/base64.cpp.o
```

**Comment by LocutusOfBorg** [comment]
@BillyONeal this commit seems to have introduced a 32bit regression and build failure...
https://github.com/Microsoft/cpprestsdk/commit/f10d9f8e214516d2c19aa6ef831ee874a58c0479

**Comment by BillyONeal** [comment]
Yeah, I got tripped up by 32 bit time_t. :(

**Comment by BillyONeal** [comment]
Hmmmm I'm not sure why this is working:

```
[bion@localhost build.debug]$ uname -r
5.0.3-200.fc29.i686
```
I'll avoid 32 bit time_t anyway.

**Comment by BillyONeal** [comment]
OH, it worked because I was pulling from the wrong remote. Stand by :)

**Comment by c72578** [comment]
Just tested https://github.com/Microsoft/cpprestsdk/pull/1094 here under Fedora and it works.
Thanks for the fix.

**Comment by LocutusOfBorg** [comment]
yes it works! thank you!
