### ISSUE TITLE
Build failed on raspberrypi 32bit Armbian (websocketpp)

### ISSUE THREAD

**Issue by jinneec** [Microsoft/cpprestsdk#1125]
pi@raspberrypi:~/dep/cpprestsdk/Release $ uname -a
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

1. Build  log:
[  2%] Building CXX object Release/src/CMakeFiles/cpprest.dir/http/common/http_compression.cpp.o
[  3%] Building CXX object Release/src/CMakeFiles/cpprest.dir/http/common/http_helpers.cpp.o
[  3%] Building CXX object Release/src/CMakeFiles/cpprest.dir/http/common/http_msg.cpp.o
[  4%] Building CXX object Release/src/CMakeFiles/cpprest.dir/http/listener/http_listener.cpp.o
[  5%] Building CXX object Release/src/CMakeFiles/cpprest.dir/http/listener/http_listener_msg.cpp.o
[  5%] Building CXX object Release/src/CMakeFiles/cpprest.dir/http/listener/http_server_api.cpp.o
[  6%] Building CXX object Release/src/CMakeFiles/cpprest.dir/http/oauth/oauth1.cpp.o
[  6%] Building CXX object Release/src/CMakeFiles/cpprest.dir/http/oauth/oauth2.cpp.o
[  7%] Building CXX object Release/src/CMakeFiles/cpprest.dir/json/json.cpp.o
[  8%] Building CXX object Release/src/CMakeFiles/cpprest.dir/json/json_parsing.cpp.o
[  8%] Building CXX object Release/src/CMakeFiles/cpprest.dir/json/json_serialization.cpp.o
[  9%] Building CXX object Release/src/CMakeFiles/cpprest.dir/uri/uri.cpp.o
[ 10%] Building CXX object Release/src/CMakeFiles/cpprest.dir/uri/uri_builder.cpp.o
[ 10%] Building CXX object Release/src/CMakeFiles/cpprest.dir/utilities/asyncrt_utils.cpp.o
[ 11%] Building CXX object Release/src/CMakeFiles/cpprest.dir/utilities/base64.cpp.o
[ 11%] Building CXX object Release/src/CMakeFiles/cpprest.dir/utilities/web_utilities.cpp.o
[ 12%] Building CXX object Release/src/CMakeFiles/cpprest.dir/websockets/client/ws_msg.cpp.o
[ 13%] Building CXX object Release/src/CMakeFiles/cpprest.dir/websockets/client/ws_client.cpp.o
[ 13%] Building CXX object Release/src/CMakeFiles/cpprest.dir/websockets/client/ws_client_wspp.cpp.o
In file included from /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/connection.hpp:33:0,
                 from /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/endpoint.hpp:31,
                 from /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/roles/client_endpoint.hpp:31,
                 from /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/client.hpp:31,
                 from /home/pi/dep/cpprestsdk/Release/src/websockets/client/ws_client_wspp.cpp:49:
/home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/frame.hpp: In function [01mvoid websocketpp::frame::word_mask_exact(uint8_t*, uint8_t*, size_t, const masking_key_type&)                                                                                                                                       /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/frame.hpp:707:57: error: cast from [01muint8_t* {aka unsigned char*}to [01msize_t* {aka unsigned int*}increases required alignment of target type [-Werror=cast-align]
     size_t* input_word = reinterpret_cast<size_t*>(input);
/home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/frame.hpp:708:59: error: cast from [01muint8_t* {aka unsigned char*}to [01msize_t* {aka unsigned int*}increases required alignment of target type [-Werror=cast-align]
     size_t* output_word = reinterpret_cast<size_t*>(output);
/home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/frame.hpp: In function [01msize_t websocketpp::frame::word_mask_circ(uint8_t*, uint8_t*, size_t, size_t)                                                           /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/frame.hpp:773:59: error: cast from [01muint8_t* {aka unsigned char*}to [01msize_t* {aka unsigned int*}increases required alignment of target type [-Werror=cast-align]
     size_t * input_word = reinterpret_cast<size_t *>(input);
/home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/frame.hpp:774:61: error: cast from [01muint8_t* {aka unsigned char*}to [01msize_t* {aka unsigned int*}increases required alignment of target type [-Werror=cast-align]
     size_t * output_word = reinterpret_cast<size_t *>(output);
In file included from /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/processors/hybi00.hpp:36:0,
                 from /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/impl/connection_impl.hpp:31,
                 from /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/connection.hpp:1640,
                 from /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/endpoint.hpp:31,
                 from /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/roles/client_endpoint.hpp:31,
                 from /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/client.hpp:31,
                 from /home/pi/dep/cpprestsdk/Release/src/websockets/client/ws_client_wspp.cpp:49:
/home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/common/md5.hpp: In function [01mvoid websocketpp::md5::md5_process(websocketpp::md5::md5_state_t*, const md5_byte_t*)
 /home/pi/dep/cpprestsdk/Release/libs/websocketpp/websocketpp/common/md5.hpp:203:33: error: cast from [01mconst md5_byte_t* {aka const unsigned char*}to [01mconst md5_word_t* {aka const unsigned int*}increases required alignment of target type [-Werror=cast-align]
         X = (md5_word_t const *)data;

**Comment by jinneec** [comment]
does this means cpprestsdk does not support 32bit platform?

**Comment by rkubes** [comment]
See #59. You either need to disable Websockets, or configure to build but not treat cast align warnings as errors. Instructions for each are within #59.

**Comment by jinneec** [comment]
Thanks so much. I will go to #59 to find the solutions.
