### ISSUE TITLE
C++ REST API not working

### ISSUE THREAD

**Issue by ymalli144** [microsoft/cpprestsdk#1129]
Hi,

This is regarding C++ REST API (casablanca120.dll).

I am using this SDK to get REST API responses from server to my application. This is working as expected if I run after windows logged in as user.

If I run same application over windows login screen then this REST API is not working, I can see response status as OK but connection is not establishing and there is no response body.

Please help me on this.

**Comment by RotateAt60MPH** [comment]
If I understand your setup, if your REST API 'listener' is a simple .EXE then it cannot run if the user owning the process is not logged in.  In order to be able to use the REST API when you are logged out, then your REST API must be a WINDOWS service that can be started and executes by itself - not as a logged in user.

Hope this helps...

**Comment by ymalli144** [comment]
Hi,

Thanks for the quick response.

Here my process is not running as any user owning process, it is a custom
credential provider that executes and runs at login screen.

Thanks & Regards,
Mallik

**Comment by RotateAt60MPH** [comment]
Ah.  That is a different story.  Thanks for the additional information.

Does this custom credential provider run as an identifiable process on the computer?  i.e. does it have a PID?  If it does, maybe you can use Remote Desktop to log into the machine (which does not connect to the console which shows the login page).  Then maybe with the RDP session you can attach a debugger to the process and see what is happening.  

Hope this helps.

**Comment by jh4843** [comment]
I have same problem.
I run the program using the listener from my service program (System authority).
In log-in environment, It was working well.
In logged out (login screen), It was not working.

According to you, if I run the program as service account, it will work well in login screen, right?
Please let me know that.
additionally, why is it related to windows log-in?

**Comment by ymalli144** [comment]
Thanks for the details...
I have a different issue with specific REST API (it has basic authentication), I can able get the proper response and error message as "OK" when It runs under the administrator user session but fails with local system account (error message and response data are empty but error code is 200) and my request type is "GET"

Do we have any specific reason on REST SDK side to know more because my process (executing code) is common in both user session (administrator and local system account).
