### ISSUE TITLE
cpprestsdk.v140.winxp.msvcstl.dyn.rt-dyn NuGet package not available

### ISSUE THREAD

**Issue by icnocop** [Microsoft/cpprestsdk#113]
Initially reported on codeplex here: https://casablanca.codeplex.com/workitem/409.

There isn't a cpprestsdk.v140.winxp.msvcstl.dyn.rt-dyn NuGet package available.

I'm not sure how nuget packages are being created since there are no nuspec files in source control.

In any case, I will try to incorporate "casablanca140.xp.vcxproj" from the codeplex workitem and issue a pull request.

**Comment by ras0219-msft** [comment]
Resolved by PR #115, thanks!

**Comment by icnocop** [comment]
Should I expect cpprestsdk.v140.winxp.msvcstl.dyn.rt-dyn, or similar, in NuGet soon?

**Comment by ras0219-msft** [comment]
Probably not soon, we will consider it during the next release. You can create the binaries yourself and add them to the Additional Dependencies list in the meantime.
