### ISSUE TITLE
Compression support on Linux

### ISSUE THREAD

**Issue by shaodan** [microsoft/cpprestsdk#1165]
Hi, I'm developing a web-socket client on Manjaro with cpprestsdk installed from [AUR](https://aur.archlinux.org/packages/cpprestsdk/) v2.10.13-1

I tried to make decompressor from web::http::compression::builtin to decompress messages, but that module doesn't seem to be supported on Linux Platform since CPPREST_HTTP_COMPRESSION wouldn't be defined: 

https://github.com/microsoft/cpprestsdk/blob/9d8f544001cb74544de6dc8c565592f7e2626d6e/Release/src/http/common/http_compression.cpp#L20

Did I install a wrong version or build incorrectly?
Any help would be appreciated.

**Comment by c72578** [comment]
Looks like brotli HTTP compression is not enabled in the package from AUR.
The following is missing in PKGBUILD:
`-DCPPREST_EXCLUDE_BROTLI=OFF`
See: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cpprestsdk

Maybe you want to contact the package maintainer or file a request there to enable it.
