### ISSUE TITLE
Why cpprestsdk strings are defined wide on windows?

### ISSUE THREAD

**Issue by smartseal** [microsoft/cpprestsdk#1166]
On windows all strings are defined as wide string, why is it? How to close it?

**Comment by Naville** [comment]
I'm not a Windows guy. But I heard it's because the underlying NT kernel related syscalls are designed with wide-strings. I got frustrated with this as well and dropped windows support altogether

**Comment by smartseal** [comment]
thanks, I only work on windows. I have to do the char convertion.
