### ISSUE TITLE
uri_builder not working on Windows

### ISSUE THREAD

**Issue by ulkeizsofi** [microsoft/cpprestsdk#1168]
`uri::uri(const utility::string_t& uri_string) : uri(uri_string.c_str()) {}`

On Windows utility::string_t is defined as wstring, but on wstring the .c_str method is not providing the wchar* as expected here.

**Comment by Dimon4eg** [comment]
This is how I solved your issue to work on all platforms:

```c++
#include "cpprest/asyncrt_utils.h"

#ifdef _WIN32
    #define TO_STD_STR(ws_str)     utility::conversions::to_utf8string(ws_str)
    #define FROM_STD_STR(utf8str)  utility::conversions::to_string_t(utf8str)
#else
    #define TO_STD_STR(ws_str)     ws_str
    #define FROM_STD_STR(utf8str)  utf8str
#endif

std::string& uri;
utility::string_t restUri(FROM_STD_STR(uri));
```

**Comment by ulkeizsofi** [comment]
This way it is throwing the throw std::range_error("UTF-8 string is missing bytes in character"); error in the asyncrt_utils file.

**Comment by Dimon4eg** [comment]
It works for me.

What string causes that?

**Comment by ulkeizsofi** [comment]
The uri is localhost:8811. It is not working neither with http at the beginning.

And the code is this:
`
wstring wstrAddress = confStore->getValue<wstring>("self_address");
utility::string_t address = utility::conversions::to_string_t(wstrAddress);
cout << uri::validate(address);
uri_builder uri(address);
`
The wstring from confStore is read ok. 
The uri_builder crashes.

**Comment by ulkeizsofi** [comment]
Ok, I've found out that I need / at the end of the uri to be valid. Now I am getting std::bad_array_new_length{}; error from the throw_bad_alloc.cpp file. The error appears to happen when the cpprest library tries to get the uri_components from the uri.

**Comment by Dimon4eg** [comment]
Proper usage of HTTP client is following:
1. set base url (address of server):
```c++
client = new http_client(address);
```
normal address is `ip:port` or `server_dns_name:port`

2. set resource path to uri_builder: 
```c++
uri_builder builder(FROM_STD_STR("/path"));
...
```
This is path of a resource on the server.
Don't specify server address here.

Example how I use [here](https://github.com/heroiclabs/nakama-cpp/blob/master/src/NHttpClientCppRest.cpp)

**Comment by ulkeizsofi** [comment]
Thank you for your help
