### ISSUE TITLE
On windows, how to convert json::value.serialize() to make_etf8_message()?

### ISSUE THREAD

**Issue by smartseal** [microsoft/cpprestsdk#1169]
I use cpprest on windows, and all the string on windows are defined as utility::string_t, which is wide string wstring.

The json::value::serialize() will return as utility::string_t, which is wstring, but websocket_outgoing_message.set_utf8_message only take std::string as input.

How should I convert between them?

                ```
                json::value obj;
		obj[U("op")] = json::value::string(U("subscribe"));
		obj[U("args")] = json::value::string(U("swap/ticker:BTC-USD-SWAP"));
		websocket_outgoing_message msg;
		msg.set_utf8_message(obj.serialize());
```

**Comment by garethsb-sony** [comment]
`utililty::conversions::to_utf8string` in cpprest/asyncrt_utils.h.
