### ISSUE TITLE
Compiler crashes consistently when processing ws_client_wspp.cpp.o

### ISSUE THREAD

**Issue by jaryder** [microsoft/cpprestsdk#1172]
[48/159] Building CXX object Release/src/CMakeFiles/**cpprest.dir/websockets/client/ws_client_wspp.cpp.o**
FAILED: Release/src/CMakeFiles/cpprest.dir/websockets/client/ws_client_wspp.cpp.o 
/usr/bin/c++  -DCPPREST_EXCLUDE_BROTLI=1 -DCPPREST_FORCE_HTTP_CLIENT_ASIO -DCPPREST_FORCE_HTTP_LISTENER_ASIO -DCPPREST_NO_SSL_LEAK_SUPPRESS -Dcpprest_EXPORTS -I../Release/include -I../Release/src/pch -std=c++11 -fno-strict-aliasing -O3 -DNDEBUG -fPIC   -Werror -pedantic -Wall -Wextra -Wunused-parameter -Wcast-align -Wcast-qual -Wconversion -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-format-attribute -Wmissing-include-dirs -Wpacked -Wredundant-decls -Wunreachable-code -MD -MT Release/src/CMakeFiles/cpprest.dir/websockets/client/ws_client_wspp.cpp.o -MF Release/src/CMakeFiles/cpprest.dir/websockets/client/ws_client_wspp.cpp.o.d -o Release/src/CMakeFiles/cpprest.dir/websockets/client/ws_client_wspp.cpp.o -c ../Release/src/websockets/client/ws_client_wspp.cpp
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.

**Comment by garethsb-sony** [comment]
Compiling websocketpp-based code seems to generate large objects (/bigobj is necessary on Windows) and cause compilers to use a lot of memory. I've seen bug reports on other projects that use websocketpp, that say gcc is running out of memory.

**Comment by jaryder** [comment]
Thanks for the swift response!  I do believe that is what's happening in this case.
Is there any known workaround for this issue?  More available RAM??

Aside: If v2.10.13 were to be available as a Debian package on Ubuntu 18.04, we would not need to build the source and could avoid this problem entirely.

**Comment by jaryder** [comment]
I have found that if you reduce the number of concurrent jobs allowed to run, it will succeessfully compile (albeit a bit slower).

"ninja -j 8" worked for me (if that still fails, try: ninja -j 1).
