### ISSUE TITLE
Platform-independent locks in pplx?

### ISSUE THREAD

**Issue by davidhigh** [Microsoft/cpprestsdk#119]
I hope I'm right in assuming that this is some kind of Q&A forum which replaces the inactive forum at codeplex? If so, here is a questions:
 
Is it possible to use the synchronzation tools from the standard library (`std::mutex`, etc)?

**Comment by ras0219-msft** [comment]
Yes, we recommend using the standard library synchronization objects when you need a `mutex`, `condition_variable`, etc.

Depending on your particular use case, we also have a cross-platform `pplx::task_completion_event` which can make it easier to wrap a callback-based async framework into the `pplx::task`-based async framework.
