### ISSUE TITLE
Conflict with Eigen3 definition

### ISSUE THREAD

**Issue by AGregg** [microsoft/cpprestsdk#1203]
This line
https://github.com/microsoft/cpprestsdk/blob/master/Release/include/cpprest/details/basic_types.h#L87
and line 995 of this file:
https://eigen.tuxfamily.org/dox/BDCSVD_8h_source.html
both define a U()

It would be cool to not use `U(x)` so that I can use both without adding `#undef U`

**Comment by jaeseok4104** [comment]
did you solve this problem?

**Comment by AGregg** [comment]
Yes, in files that include both, I add #define _TURN_OFF_PLATFORM_STRING to the top to disable the U macro for the cpprestclient.

https://github.com/microsoft/cpprestsdk/blob/master/Release/include/cpprest/details/basic_types.h#L83

**Comment by jaeseok4104** [comment]
thanks :)
