### ISSUE TITLE
Is rest still supporting VS2010 c++ development?

### ISSUE THREAD

**Issue by HarrisonSun1997** [microsoft/cpprestsdk#1259]
Because of the project reasons, we need to write rest services in VS2010 using c++. At present, the project only considers the use as a client, but does not exclude the possibility of future requirements as a service. I read the answer on issue and downloaded it to cpprestsdk. v120. nupkg on the internet. I installed it into the project of vs2010. When compiling, it will prompt grammatical errors. But I build it with vs2013 is no problem. Do I need to develop rest support in the environment of VS2010 now? Or is there a framework that can also build restful services but is compatible with c++ on vs2010? Thank you

**Comment by Dimon4eg** [comment]
take a look at this https://github.com/mrtazz/restclient-cpp

**Comment by HarrisonSun1997** [comment]
> take a look at this https://github.com/mrtazz/restclient-cpp

Just now,I download restclient-cpp project to local windows build,but vs2010 show "CURLOPT_UNIX_SOCKET_PATH" : undeclared identifier?Are there any other solutions?please

**Comment by HarrisonSun1997** [comment]
Hi, I found in the old version of the cpprest project that v1.2.0 and before supported vs2010 compilation, thank you for helping me solve the problem
