### ISSUE TITLE
add a known header "access-control-allow-origin into http_constants.dat 

### ISSUE THREAD

**Issue by jsonng** [Microsoft/cpprestsdk#128]
simple change:
DAT(access_control_allow_origin,  "Access-Control-Allow-Origin")

This is needed for some simple response, where I am building my own http_response with the following code:
response.headers().add(U("Access-Control-Allow-Origin"), "*");

however, it would be ideal to use a predefined repsonse header so that people don't have to hard code this.

**Comment by drearyworlds** [comment]
I second this. I may look into adding this myself and putting another pull request for it.
