### ISSUE TITLE
Failure in open_failure: Expected exception: "web::http::http_exception" not thrown FAILED Test case connections_and_errors:open_failure FAILED

### ISSUE THREAD

**Issue by drhalftone** [Microsoft/cpprestsdk#129]
DrHalftone:Binaries dllau$ ./test_runner *_test.dylib
Loaded libhttpclient_test.dylib...
Loaded libhttplistener_test.dylib...
Loaded libjson_test.dylib...
Loaded libpplx_test.dylib...
Loaded libstreams_test.dylib...
Loaded liburi_test.dylib...
Loaded libutils_test.dylib...
Loaded libwebsocketclient_test.dylib...
=== Running tests from: <static> ===
=== Running tests from: libhttpclient_test.dylib ===
Starting test case authentication_tests:empty_username_password...
Test case authentication_tests:empty_username_password PASSED
Starting test case authentication_tests:set_user_options_asio_http...
Test case authentication_tests:set_user_options_asio_http PASSED
Starting test case authentication_tests:set_user_options_asio_https...
Test case authentication_tests:set_user_options_asio_https PASSED
Starting test case building_request_tests:simple_values...
Test case building_request_tests:simple_values PASSED
Starting test case building_request_tests:body_types...
Test case building_request_tests:body_types PASSED
Starting test case building_request_tests:set_body_string_with_charset...
Test case building_request_tests:set_body_string_with_charset PASSED
Starting test case building_request_tests:empty_bodies...
Test case building_request_tests:empty_bodies PASSED
Starting test case building_request_tests:set_body...
Test case building_request_tests:set_body PASSED
Starting test case building_request_tests:set_body_with_charset...
Test case building_request_tests:set_body_with_charset PASSED
Starting test case building_request_tests:set_content_length_locale...
Test case building_request_tests:set_content_length_locale PASSED
Starting test case building_request_tests:set_port_locale...
Test case building_request_tests:set_port_locale PASSED
Starting test case building_request_tests:reuse_request...
Test case building_request_tests:reuse_request PASSED
Starting test case client_construction:string_types...
Test case client_construction:string_types PASSED
Starting test case client_construction:different_uris...
Test case client_construction:different_uris PASSED
Starting test case client_construction:client_construction_error_cases...
Test case client_construction:client_construction_error_cases PASSED
Starting test case client_construction:client_construction_no_scheme...
Test case client_construction:client_construction_no_scheme PASSED
Starting test case client_construction:copy_assignment...
Test case client_construction:copy_assignment PASSED
Starting test case client_construction:move_not_init...
Test case client_construction:move_not_init PASSED
Starting test case client_construction:move_init...
Test case client_construction:move_init PASSED
Starting test case client_construction:get_client_config...
Test case client_construction:get_client_config PASSED
Starting test case client_construction:BaseURI_test...
Test case client_construction:BaseURI_test PASSED
Starting test case client_construction:ssl_context_callback_https...
Test case client_construction:ssl_context_callback_https PASSED
Starting test case client_construction:ssl_context_callback_http...
Test case client_construction:ssl_context_callback_http PASSED
Starting test case connections_and_errors:pending_requests_after_client...
Test case connections_and_errors:pending_requests_after_client PASSED
Starting test case connections_and_errors:server_doesnt_exist...
Test case connections_and_errors:server_doesnt_exist PASSED
Starting test case connections_and_errors:open_failure...
/Users/dllau/SourceTree/RestSDK/Release/tests/functional/http/client/connections_and_errors.cpp:107: error: Failure in open_failure: Expected exception: "web::http::http_exception" not thrown FAILED
Test case connections_and_errors:open_failure FAILED
Starting test case connections_and_errors:server_close_without_responding...
Test case connections_and_errors:server_close_without_responding PASSED
Starting test case connections_and_errors:request_timeout...
Test case connections_and_errors:request_timeout PASSED
Starting test case connections_and_errors:request_timeout_microsecond...
/Users/dllau/SourceTree/RestSDK/Release/tests/functional/http/client/connections_and_errors.cpp:145: error: Failure in request_timeout_microsecond: Test case timed out and is hung. Aborting all remaining test cases. Expected under 180000ms. FAILED
Abort trap: 6
DrHalftone:Binaries dllau$

**Comment by ras0219-msft** [comment]
This test is flaky and needs improvement. If you need to skip the test temporarily, you can add `"Ignore","Flaky"` to the test options in the source file and rebuild.

**Comment by BillyONeal** [comment]
I believe I fixed this in https://github.com/Microsoft/cpprestsdk/pull/926
