### ISSUE TITLE
newlocale use appears incorrect per man page; fails with Emscripten

### ISSUE THREAD

**Issue by jason-ha** [microsoft/cpprestsdk#1329]
`scoped_c_thread_locale::c_locale()` contains the line
```
*clocale = newlocale(LC_ALL, "C", nullptr);
```
This fails use with Emscripten (v1.39.8) as null is returned when `category_mask` is `LC_ALL`.
[newlocal man page](http://man7.org/linux/man-pages/man3/newlocale.3.html) compared with `_create_locale(LC_ALL,` a few lines above and [_create_locale docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/create-locale-wcreate-locale?view=vs-2019) suggest that `LC_ALL_MASK` is the proper `category_mask` argument:
```
*clocale = newlocale(LC_ALL_MASK, "C", nullptr);
```
History shows this call, once added (Steve Gates 8/28/2014), was always this way.

**Comment by BillyONeal** [comment]
I don't understand the statement that the docs page recommends `LC_ALL_MASK` -- neither `LC_ALL_MASK` nor the word mask appear on that page...

**Comment by BillyONeal** [comment]
Oh, this is for newlocale not _create_locale, I can't read.
