### ISSUE TITLE
Unable to make samples on linux

### ISSUE THREAD

**Issue by NihalHarish** [Microsoft/cpprestsdk#133]
The make fails with the following output:

[  5%] Linking CXX executable SearchFile
CMakeFiles/SearchFile.dir/searchfile.o: In function `main':
searchfile.cpp:(.text+0x19e2): undefined reference to`utility::conversions::to_utf8string(std::string)'
CMakeFiles/SearchFile.dir/searchfile.o: In function `pplx::details::recursive_lock_impl::lock()':
searchfile.cpp:(.text._ZN4pplx7details19recursive_lock_impl4lockEv[_ZN4pplx7details19recursive_lock_impl4lockEv]+0xd): undefined reference to`pplx::details::platform::GetCurrentThreadId()'
CMakeFiles/SearchFile.dir/searchfile.o: In function `pplx::details::recursive_lock_impl::unlock()':
searchfile.cpp:(.text._ZN4pplx7details19recursive_lock_impl6unlockEv[_ZN4pplx7details19recursive_lock_impl6unlockEv]+0x16): undefined reference to`pplx::details::platform::GetCurrentThreadId()'
CMakeFiles/SearchFile.dir/searchfile.o: In function `pplx::details::_CancellationTokenRegistration::_Invoke()':
searchfile.cpp:(.text._ZN4pplx7details30_CancellationTokenRegistration7_InvokeEv[_ZN4pplx7details30_CancellationTokenRegistration7_InvokeEv]+0xd): undefined reference to`pplx::details::platform::GetCurrentThreadId()'
CMakeFiles/SearchFile.dir/searchfile.o: In function `pplx::details::_CancellationTokenState::_DeregisterCallback(pplx::details::_CancellationTokenRegistration*)':
searchfile.cpp:(.text._ZN4pplx7details23_CancellationTokenState19_DeregisterCallbackEPNS0_30_CancellationTokenRegistrationE[_ZN4pplx7details23_CancellationTokenState19_DeregisterCallbackEPNS0_30_CancellationTokenRegistrationE]+0x121): undefined reference to`pplx::details::platform::GetCurrentThreadId()'
CMakeFiles/SearchFile.dir/searchfile.o: In function `pplx::details::_TaskCollectionImpl::_RunTask(void (*)(void*), void*, pplx::details::_TaskInliningMode)':
searchfile.cpp:(.text._ZN4pplx7details19_TaskCollectionImpl8_RunTaskEPFvPvES2_NS0_17_TaskInliningModeE[_ZN4pplx7details19_TaskCollectionImpl8_RunTaskEPFvPvES2_NS0_17_TaskInliningModeE]+0x31): undefined reference to`pplx::get_ambient_scheduler()'
CMakeFiles/SearchFile.dir/searchfile.o: In function `pplx::task_options::task_options()':
searchfile.cpp:(.text._ZN4pplx12task_optionsC2Ev[_ZN4pplx12task_optionsC5Ev]+0x14): undefined reference to`pplx::get_ambient_scheduler()'
CMakeFiles/SearchFile.dir/searchfile.o: In function `Concurrency::streams::details::basic_file_buffer<char>::open(std::string const&, std::_Ios_Openmode, int)':
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE4openERKSsSt13_Ios_Openmodei[_ZN11Concurrency7streams7details17basic_file_bufferIcE4openERKSsSt13_Ios_Openmodei]+0x7e): undefined reference to`_open_fsb_str'
CMakeFiles/SearchFile.dir/searchfile.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_close_file(Concurrency::streams::details::_file_info*)':
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE11_close_fileEPNS1_10_file_infoE[_ZN11Concurrency7streams7details17basic_file_bufferIcE11_close_fileEPNS1_10_file_infoE]+0x5e): undefined reference to`_close_fsb_nolock'
CMakeFiles/SearchFile.dir/searchfile.o: In function `Concurrency::streams::details::basic_file_buffer<char>::flush_internal()':
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE14flush_internalEv[_ZN11Concurrency7streams7details17basic_file_bufferIcE14flush_internalEv]+0x71): undefined reference to`_sync_fsb'
CMakeFiles/SearchFile.dir/searchfile.o: In function `Concurrency::streams::details::basic_file_buffer<char>::size() const':
searchfile.cpp:(.text._ZNK11Concurrency7streams7details17basic_file_bufferIcE4sizeEv[_ZNK11Concurrency7streams7details17basic_file_bufferIcE4sizeEv]+0x42): undefined reference to`_get_size'
CMakeFiles/SearchFile.dir/searchfile.o: In function `Concurrency::streams::details::basic_file_buffer<char>::seekpos(std::fpos<__mbstate_t>, std::_Ios_Openmode)':
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE7seekposESt4fposI11__mbstate_tESt13_Ios_Openmode[_ZN11Concurrency7streams7details17basic_file_bufferIcE7seekposESt4fposI11__mbstate_tESt13_Ios_Openmode]+0x59): undefined reference to`_seekrdpos_fsb'
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE7seekposESt4fposI11__mbstate_tESt13_Ios_Openmode[_ZN11Concurrency7streams7details17basic_file_bufferIcE7seekposESt4fposI11__mbstate_tESt13_Ios_Openmode]+0xbf): undefined reference to `_seekwrpos_fsb'
CMakeFiles/SearchFile.dir/searchfile.o: In function`Concurrency::streams::details::basic_file_buffer<char>::seekoff(long, std::_Ios_Seekdir, std::_Ios_Openmode)':
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode[_ZN11Concurrency7streams7details17basic_file_bufferIcE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode]+0x70): undefined reference to `_seekrdpos_fsb'
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode[_ZN11Concurrency7streams7details17basic_file_bufferIcE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode]+0xba): undefined reference to`_seekrdpos_fsb'
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode[_ZN11Concurrency7streams7details17basic_file_bufferIcE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode]+0xf5): undefined reference to `_seekrdtoend_fsb'
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode[_ZN11Concurrency7streams7details17basic_file_bufferIcE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode]+0x189): undefined reference to`_seekwrpos_fsb'
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode[_ZN11Concurrency7streams7details17basic_file_bufferIcE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode]+0x1d4): undefined reference to `_seekwrpos_fsb'
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode[_ZN11Concurrency7streams7details17basic_file_bufferIcE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode]+0x20c): undefined reference to`_seekwrpos_fsb'
CMakeFiles/SearchFile.dir/searchfile.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_putc(char)':
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE5_putcEc[_ZN11Concurrency7streams7details17basic_file_bufferIcE5_putcEc]+0xe6): undefined reference to`_putn_fsb'
CMakeFiles/SearchFile.dir/searchfile.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_putn(char const*, unsigned long)':
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE5_putnEPKcm[_ZN11Concurrency7streams7details17basic_file_bufferIcE5_putnEPKcm]+0x8c): undefined reference to`_putn_fsb'
CMakeFiles/SearchFile.dir/searchfile.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_bumpc()::{lambda()#1}::operator()() const':
searchfile.cpp:(.text._ZZN11Concurrency7streams7details17basic_file_bufferIcE6_bumpcEvENKUlvE_clEv[_ZZN11Concurrency7streams7details17basic_file_bufferIcE6_bumpcEvENKUlvE_clEv]+0x1b8): undefined reference to`_getn_fsb'
CMakeFiles/SearchFile.dir/searchfile.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_nextc()::{lambda()#1}::operator()() const':
searchfile.cpp:(.text._ZZN11Concurrency7streams7details17basic_file_bufferIcE6_nextcEvENKUlvE_clEv[_ZZN11Concurrency7streams7details17basic_file_bufferIcE6_nextcEvENKUlvE_clEv]+0x3a): undefined reference to`_seekrdpos_fsb'
CMakeFiles/SearchFile.dir/searchfile.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_ungetc()::{lambda()#1}::operator()() const':
searchfile.cpp:(.text._ZZN11Concurrency7streams7details17basic_file_bufferIcE7_ungetcEvENKUlvE_clEv[_ZZN11Concurrency7streams7details17basic_file_bufferIcE7_ungetcEvENKUlvE_clEv]+0x80): undefined reference to`_seekrdpos_fsb'
CMakeFiles/SearchFile.dir/searchfile.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_getn(char*, unsigned long)::{lambda()#1}::operator()() const':
searchfile.cpp:(.text._ZZN11Concurrency7streams7details17basic_file_bufferIcE5_getnEPcmENKUlvE_clEv[_ZZN11Concurrency7streams7details17basic_file_bufferIcE5_getnEPcmENKUlvE_clEv]+0x26e): undefined reference to`_getn_fsb'
CMakeFiles/SearchFile.dir/searchfile.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_getcImpl()':
searchfile.cpp:(.text._ZN11Concurrency7streams7details17basic_file_bufferIcE9_getcImplEv[_ZN11Concurrency7streams7details17basic_file_bufferIcE9_getcImplEv]+0x17a): undefined reference to`_getn_fsb'
collect2: error: ld returned 1 exit status
SearchFile/CMakeFiles/SearchFile.dir/build.make:94: recipe for target 'SearchFile/SearchFile' failed
make[2]: **\* [SearchFile/SearchFile] Error 1
CMakeFiles/Makefile2:122: recipe for target 'SearchFile/CMakeFiles/SearchFile.dir/all' failed
make[1]: **\* [SearchFile/CMakeFiles/SearchFile.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2

Should I make any any changes to the CMakeList.txt file before running cmake to successfully make?

**Comment by ras0219-msft** [comment]
It should build successfully from source. What git commit/branch are you building? What cmake options did you use? What Linux environment (compiler, distro, etc)?

**Comment by NihalHarish** [comment]
Branch: Master
I use just 'cmake .'
I also modified the CMakeLists.txt file to include "set (CMAKE_CXX_FLAGS "-std=c++11")"
The version of cmake I'm using is 3.5.2
The compiler I'm using is g++ 4.9.2
The distro I'm using is Debian Linux 64 bit

**Comment by hakbra** [comment]
Same problem here.

Branch: Master
Unmodified CMakeLists.txt
Cmake 3.2.2
g++ 5.2.1
Ubuntu 15.10 64-bit

	/tmp/cc7SpWdc.o: In function `pplx::details::_CancellationTokenRegistration::_Invoke()':
	main.cpp:(.text._ZN4pplx7details30_CancellationTokenRegistration7_InvokeEv[_ZN4pplx7details30_Cancellation
	TokenRegistration7_InvokeEv]+0xd): undefined reference to `pplx::details::platform::GetCurrentThreadId()'
	/tmp/cc7SpWdc.o: In function `pplx::details::_CancellationTokenState::_DeregisterCallback(pplx::details::_
	CancellationTokenRegistration*)':
	main.cpp:(.text._ZN4pplx7details23_CancellationTokenState19_DeregisterCallbackEPNS0_30_CancellationTokenRe
	gistrationE[_ZN4pplx7details23_CancellationTokenState19_DeregisterCallbackEPNS0_30_CancellationTokenRegist
	rationE]+0x14b): undefined reference to `pplx::details::platform::GetCurrentThreadId()'
	/tmp/cc7SpWdc.o: In function `pplx::details::_TaskCollectionImpl::_RunTask(void (*)(void*), void*, pplx::d
	etails::_TaskInliningMode)':
	main.cpp:(.text._ZN4pplx7details19_TaskCollectionImpl8_RunTaskEPFvPvES2_NS0_17_TaskInliningModeE[_ZN4pplx7
	details19_TaskCollectionImpl8_RunTaskEPFvPvES2_NS0_17_TaskInliningModeE]+0x40): undefined reference to `pp
	lx::get_ambient_scheduler()'
	/tmp/cc7SpWdc.o: In function `pplx::task_options::task_options()':
	main.cpp:(.text._ZN4pplx12task_optionsC2Ev[_ZN4pplx12task_optionsC5Ev]+0x23): undefined reference to `pplx
	::get_ambient_scheduler()'
	/tmp/cc7SpWdc.o: In function `web::http::http_request::set_request_uri(web::uri const&)':
	main.cpp:(.text._ZN3web4http12http_request15set_request_uriERKNS_3uriE[_ZN3web4http12http_request15set_req
	uest_uriERKNS_3uriE]+0x2a): undefined reference to `web::http::details::_http_request::set_request_uri(web
	::uri const&)'
	/tmp/cc7SpWdc.o: In function `web::http::http_request::set_body(std::__cxx11::basic_string<char, std::char
	_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std
	::allocator<char> > const&)':
	main.cpp:(.text._ZN3web4http12http_request8set_bodyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
	S9_[_ZN3web4http12http_request8set_bodyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_]+0x7a):
	undefined reference to `web::http::details::http_msg_base::set_body(Concurrency::streams::basic_istream<un
	signed char> const&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocato
	r<char> > const&)'
	/tmp/cc7SpWdc.o: In function `web::http::client::http_client::request(std::__cxx11::basic_string<char, std
	::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char
	>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<
	char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pp
	lx::cancellation_token const&)':
	main.cpp:(.text._ZN3web4http6client11http_client7requestERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESa
	IcEEESA_SA_SA_RKN4pplx18cancellation_tokenE[_ZN3web4http6client11http_client7requestERKNSt7__cxx1112basic_
	stringIcSt11char_traitsIcESaIcEEESA_SA_SA_RKN4pplx18cancellation_tokenE]+0xa6): undefined reference to `ut
	ility::conversions::to_string_t(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<ch
	ar> > const&)'
	main.cpp:(.text._ZN3web4http6client11http_client7requestERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESa
	IcEEESA_SA_SA_RKN4pplx18cancellation_tokenE[_ZN3web4http6client11http_client7requestERKNSt7__cxx1112basic_
	stringIcSt11char_traitsIcESaIcEEESA_SA_SA_RKN4pplx18cancellation_tokenE]+0xbf): undefined reference to `we
	b::uri::uri(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
	main.cpp:(.text._ZN3web4http6client11http_client7requestERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESa
	IcEEESA_SA_SA_RKN4pplx18cancellation_tokenE[_ZN3web4http6client11http_client7requestERKNSt7__cxx1112basic_
	stringIcSt11char_traitsIcESaIcEEESA_SA_SA_RKN4pplx18cancellation_tokenE]+0x153): undefined reference to `w
	eb::http::client::http_client::request(web::http::http_request, pplx::cancellation_token const&)'
	/tmp/cc7SpWdc.o: In function `OpenSubConnection::OpenSubConnection()':
	main.cpp:(.text._ZN17OpenSubConnectionC2Ev[_ZN17OpenSubConnectionC5Ev]+0x32): undefined reference to `web:
	:uri::uri(char const*)'
	main.cpp:(.text._ZN17OpenSubConnectionC2Ev[_ZN17OpenSubConnectionC5Ev]+0x4b): undefined reference to `web:
	:http::client::http_client::http_client(web::uri const&)'
	/tmp/cc7SpWdc.o: In function `OpenSubConnection::connect(std::__cxx11::basic_string<char, std::char_traits
	<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<ch
	ar> >)':
	main.cpp:(.text._ZN17OpenSubConnection7connectENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_[_ZN
	17OpenSubConnection7connectENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_]+0x1e9): undefined ref
	erence to `web::http::methods::POST[abi:cxx11]'
	/tmp/cc7SpWdc.o: In function `void __gnu_cxx::new_allocator<web::http::details::_http_request>::construct<
	web::http::details::_http_request, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator
	<char> > >(web::http::details::_http_request*, std::__cxx11::basic_string<char, std::char_traits<char>, st
	d::allocator<char> >&&)':
	main.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN3web4http7details13_http_requestEE9constructIS4_JNSt7__cxx11
	12basic_stringIcSt11char_traitsIcESaIcEEEEEEvPT_DpOT0_[_ZN9__gnu_cxx13new_allocatorIN3web4http7details13_h
	ttp_requestEE9constructIS4_JNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEEvPT_DpOT0_]+0x6a): unde
	fined reference to `web::http::details::_http_request::_http_request(std::__cxx11::basic_string<char, std:
	:char_traits<char>, std::allocator<char> >)'
	collect2: error: ld returned 1 exit status
	makefile:10: recipe for target 'all' failed
	make: *** [all] Error 1

**Comment by ras0219-msft** [comment]
@NihalHarish Hmm, it looks like SearchFile isn't linking the cpprest library. Could you `make VERBOSE=1` and post the command line that fails?

@hakbra I'm not sure where you're getting these errors from -- we don't build a file called `main.cpp` in cpprestsdk. Are you getting errors trying to link your own project after successfully building cpprestsdk? If so, you probably need to add `-lcpprest` to your link line (`target_link_libraries(main cpprest)` in cmake).

**Comment by ras0219-msft** [comment]
@NihalHarish Actually, re-reading your problem statement I think I understand. Are you trying to run `cmake .` inside the samples directory? If so, that will fail by design. To build the samples, follow the normal build-from-source rules but pass in `-DBUILD_SAMPLES=1` to the initial cmake invocation.

**Comment by LeeRuns** [comment]
getting same error when i use lib install on ubuntu...
cmake pattern shown below
```
set(OPENSSL_USE_STATIC_LIBS TRUE)
find_package(OpenSSL REQUIRED)
#--Headers and Source Files------------#
set( ${PROJECT_NAME}_headers "${PROJECT_NAME}.h")
set( ${PROJECT_NAME}_sources "${PROJECT_NAME}.cc")

#--Create the Library -----------------#
add_library ( ${PROJECT_NAME} SHARED ${${PROJECT_NAME}_headers} 
                                     ${${PROJECT_NAME}_sources}
				     )
# Uncomment to link other modules or boost				   
find_library(cpprest REQUIRED)

target_link_libraries(${PROJECT_NAME} PUBLIC
  OpenSSL::Crypto
  ${Boost_LIBRARIES}
  ${Boost_FILESYSTEM_LIBRARY}
  ${Boost_SYSTEM_LIBRARY}
  )

target_link_libraries("${PROJECT_NAME}" PRIVATE  cpprest )      
#--Create Executable-------------------#
# build main executable
add_executable(	"main${PROJECT_NAME}"
  ${PROJECT_NAME}
  main.cc
  )
target_link_libraries("main${PROJECT_NAME}" PUBLIC
  #add other module names (ie FileDb)
  OpenSSL::Crypto
  ${Boost_LIBRARIES}
  ${Boost_FILESYSTEM_LIBRARY}
  ${Boost_SYSTEM_LIBRARY}
  )
target_link_libraries("main${PROJECT_NAME}" PRIVATE  cpprest)      

#--include directories-----------------#
# update list of include directories
#include_directories(${CMAKE_SOURCE_DIR}/../cpprestsdk/build)

#--install-----------------------------#
install(
  TARGETS "main${PROJECT_NAME}"
  RUNTIME DESTINATION bin
  LIBRARY DESTINATION lib
  ARCHIVE DESTINATION lib/static
  )

install(
  TARGETS ${PROJECT_NAME}
  RUNTIME DESTINATION bin
  LIBRARY DESTINATION lib
  ARCHIVE DESTINATION lib/shared
  )

```
