### ISSUE TITLE
Why is Boost unconditionally used in pplx implementation under Mac?

### ISSUE THREAD

**Issue by vadz** [microsoft/cpprestsdk#1338]
Why is there an `#if defined(__APPLE__)` condition [here](https://github.com/microsoft/cpprestsdk/blob/v2.10.14/Release/include/pplx/pplxlinux.h#L26) forcing the use of Boost under macOS? The equivalent C++11 classes are used under Linux and I'd rather use them under Mac too. Just getting rid of this (and related) checks seems to work fine and I can submit a trivial PR doing this, of course, but I have no idea why had it been done in the first place. This change comes from 709a3784a7d07ddab8d1608f4e819d87410ec1fb but the commit message is not very helpful.

Does anybody still remember why has this been done? If not, would a PR replacing Boost with C++11 classes under macOS, as it's already done under Linux, be useful?

**Comment by BillyONeal** [comment]
This code was probably added long before C++11 synchronization support was available on Mac.

**Comment by vadz** [comment]
I think C++11 support appeared under Mac at about the same time as under Linux, but I could be wrong. Nevertheless the real question is: can we get rid of it now? I.e. would you accept a PR doing the equivalent of just this:
```diff
diff --git a/Release/include/pplx/pplxlinux.h b/Release/include/pplx/pplxlinux.h
index 78b6e180..2de203e3 100644
--- a/Release/include/pplx/pplxlinux.h
+++ b/Release/include/pplx/pplxlinux.h
@@ -26,23 +26,17 @@

 #if defined(__APPLE__)
 #include <dispatch/dispatch.h>
-#include <boost/thread/mutex.hpp>
-#include <boost/thread/condition_variable.hpp>
-#else
-#include <mutex>
-#include <condition_variable>
 #endif

+#include <mutex>
+#include <condition_variable>
+
 #include "pplx/pplxinterface.h"


 namespace pplx
 {
-#if defined(__APPLE__)
-    namespace cpprest_synchronization = ::boost;
-#else
     namespace cpprest_synchronization = ::std;
-#endif
 namespace details
 {
 namespace platform
```
(this is for older version that we use, it won't apply to master as is, but semantically it's still the same there).

**Comment by BillyONeal** [comment]
As long as it passes tests

**Comment by RameshKandukuriB** [comment]
vcpkg pulling boost on windows also, is boost really a dependency in windows for cpprestsdk:x64?
vcpkg install cpprestsdk:x64-windows

**Comment by BillyONeal** [comment]
boost is needed in Windows if and only if you install the websockets feature.
