### ISSUE TITLE
NuGet or Binaries for Visual C++ 2012 (v110)

### ISSUE THREAD

**Issue by Danielku15** [Microsoft/cpprestsdk#134]
Currently the Rest SDK is only available for v120 and v140 and a legacy v110xp. Due to legacy reasons we are still relying on v110 but would like to use this SDK. Is there a chance we can get binaries (preferrably via nuget) for the VS2012 compiler?

**Comment by ras0219-msft** [comment]
We rely on language, conformance, and correctness improvements made in the newer compiler versions which prevent compilation under v110. You could attempt to reenable v110 compilation, however we have no plans to support that compiler version (or make changes in order to support it).

What legacy reasons prevent you from using VS 2015?

**Comment by Danielku15** [comment]
Our software is a 24/7 real time service consisting of 20-30 C++ projects. Migration would be theoretically possible but for now the migration is still to risky and too time consuming. It needs long term planning and testing whether changing the compiler will have any side effects to our code base. We have on our roadmap to migrate to the new compiler and runtime but for now it's not possible for us. 

One feature of the upcoming release needs to consume a Rest API and for this we'd like to use this library. I gave it a quick try to rewrite the existing v120 project to compile with our settings but was then blocked by the fact that openssl does not have a v110 nuget package.

**Comment by Danielku15** [comment]
I was able to compile the library with some effort:  

1. Compile OpenSSL 1.0.2 for v110 (no nuget package available)
2. Create a copy of the cpprestsdk120 project and remove the nuget dependencies. Since I wanted to link it against our already available boost. 
3. Change the compiler version to v110 and adjust the include+linker paths to the local libs and add the SSL libs as additional dependencies . 
4. In the connection.hpp line 169 change the vector initialization since v110 does not support vector initializers:
```cpp
    static std::array<int, 4> versions_supported_init = {0,7,8,13};
    static std::vector<int> const versions_supported(versions_supported_init.begin(), versions_supported_init.end());
```
5. Add the _WEBSOCKETPP_NO_CPP11_FUNCTIONAL_ and BOOST_ALL_DYN_LINK preprocessor to the compilation. 
6. Compile and enjoy

**Comment by ras0219-msft** [comment]
Thank you very much for sharing your solution here!
