### ISSUE TITLE
Build fails on ubuntu

### ISSUE THREAD

**Issue by pmqtt** [microsoft/cpprestsdk#1343]
Trying to build release from source both fails with the following error:
[  1%] Building CXX object Release/src/CMakeFiles/cpprest.dir/http/client/http_client.cpp.o
[  1%] Building CXX object Release/src/CMakeFiles/cpprest.dir/http/client/http_client_msg.cpp.o
[  2%] Building CXX object Release/src/CMakeFiles/cpprest.dir/http/common/http_helpers.cpp.o
[  3%] Building CXX object Release/src/CMakeFiles/cpprest.dir/http/common/http_compression.cpp.o
In file included from /usr/local/share/boost/1.69.0/include/boost/type_traits/common_type.hpp:16,
                 from /usr/local/share/boost/1.69.0/include/boost/chrono/duration.hpp:42,
                 from /usr/local/share/boost/1.69.0/include/boost/thread/detail/platform_time.hpp:19,
                 from /usr/local/share/boost/1.69.0/include/boost/thread/detail/platform_time.hpp:19,
                 from /usr/local/share/boost/1.69.0/include/boost/thread/pthread/condition_variable.hpp:9,
                 from /usr/local/share/boost/1.69.0/include/boost/thread/condition_variable.hpp:16,
                 from /third_party/cpprestsdk/Release/src/pch/stdafx.h:61,
                 from /third_party/cpprestsdk/Release/src/http/client/http_client.cpp:16:
/usr/local/share/boost/1.69.0/include/boost/type_traits/is_complete.hpp:47:14: error: conversion from ‘long unsigned int’ to ‘unsigned int’ may change value [-Werror=conversion]
       ok_tag<sizeof(T)> check_is_complete(int);
              ^~~~~~~~~
In file included from /usr/local/share/boost/1.69.0/include/boost/type_traits/common_type.hpp:16,
                 from /usr/local/share/boost/1.69.0/include/boost/chrono/duration.hpp:42,
                 from /usr/local/share/boost/1.69.0/include/boost/thread/detail/platform_time.hpp:19,
                 from /usr/local/share/boost/1.69.0/include/boost/thread/pthread/condition_variable.hpp:9,
                 from /usr/local/share/boost/1.69.0/include/boost/thread/condition_variable.hpp:16,
                 from /third_party/cpprestsdk/Release/src/pch/stdafx.h:61,
                 from /third_party/cpprestsdk/Release/src/http/common/http_helpers.cpp:14:
/usr/local/share/boost/1.69.0/include/boost/type_traits/is_complete.hpp:47:14: error: conversion from ‘long unsigned int’ to ‘unsigned int’ may change value [-Werror=conversion]
       ok_tag<sizeof(T)> check_is_complete(int);
              ^~~~~~~~~
In file included from /usr/local/share/boost/1.69.0/include/boost/type_traits/common_type.hpp:16,
                 from /usr/local/share/boost/1.69.0/include/boost/chrono/duration.hpp:42,
                 from /usr/local/share/boost/1.69.0/include/boost/thread/detail/platform_time.hpp:19,
                 from /usr/local/share/boost/1.69.0/include/boost/thread/pthread/condition_variable.hpp:9,
                ...

My system:

Docker image ubuntu:latest
websocketpp 0.8.1
g++ 8
boost 1.69.0
openssl 1.1.1d
cmake 3.16.4
zlib 1.2.11

**Comment by c72578** [comment]
`[-Werror=conversion]` ... looks like warnings are treated like errors on your system
You can try adding `-DWERROR=OFF` to your cmake parameters, e.g.
`cmake .. -DCMAKE_BUILD_TYPE=Release -DWERROR=OFF`

**Comment by pmqtt** [comment]
It works, thanks!
