### ISSUE TITLE
provided uri is invalid error

### ISSUE THREAD

**Issue by gamgyul** [microsoft/cpprestsdk#1345]
Hello I'm trying to make http client with referencing to turtorial.

when I build uri I use non english character.  And it throw error at is_path_character function
because it is not english character. Is there any way to use non english character in URI?

for example
```cpp
client::http_client client(U("https://kr.api.com"));
uri_builder builder(U("/foo/bar/가나다"))
```

**Comment by garethsb-sony** [comment]
Unicode characters should be 'percent encoded' in URLs. For an explanation, see e.g. https://stackoverflow.com/questions/2742852/unicode-characters-in-urls.

**Comment by gamgyul** [comment]
thank you for answer.
Is there any method to encode utf8?

**Comment by garethsb-sony** [comment]
See e.g. https://github.com/microsoft/cpprestsdk/blob/b94bc32ff84e815ba44c567f6fe4af5f5f6b3048/Release/include/cpprest/uri_builder.h#L150-L156

**Comment by gamgyul** [comment]
thank you for help.
I'll try.
