### ISSUE TITLE
Undefined refrence.

### ISSUE THREAD

**Issue by JamieLuo** [microsoft/cpprestsdk#1358]
Hi,

I was trying to build the version v2.10.15 on my ubuntu but I got the below errors:

Linking CXX shared library ../Binaries/libcpprest.so
[ 22%] Built target cpprest
Scanning dependencies of target unittestpp
[ 23%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/AssertException.cpp.o
[ 24%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/CompositeTestReporter.cpp.o
[ 25%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/CurrentTest.cpp.o
[ 25%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/DeferredTestReporter.cpp.o
[ 26%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/DeferredTestResult.cpp.o
[ 27%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/GlobalSettings.cpp.o
[ 28%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/MemoryOutStream.cpp.o
[ 28%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/ReportAssert.cpp.o
[ 29%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/Test.cpp.o
[ 30%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/TestDetails.cpp.o
[ 31%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/TestList.cpp.o
[ 31%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/TestReporter.cpp.o
[ 32%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/TestReporterStdout.cpp.o
[ 33%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/TestResults.cpp.o
[ 34%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/TestRunner.cpp.o
[ 35%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/XmlTestReporter.cpp.o
[ 35%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/Posix/SignalTranslator.cpp.o
[ 36%] Building CXX object tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/src/Posix/TimeHelpers.cpp.o
Linking CXX shared library ../../../Binaries/libunittestpp.so
[ 36%] Built target unittestpp
Scanning dependencies of target common_utilities
[ 36%] Building CXX object tests/common/utilities/CMakeFiles/common_utilities.dir/os_utilities.cpp.o
Linking CXX shared library ../../../Binaries/libcommon_utilities.so
[ 36%] Built target common_utilities
Scanning dependencies of target test_runner
[ 36%] Building CXX object tests/common/TestRunner/CMakeFiles/test_runner.dir/test_runner.cpp.o
[ 37%] Building CXX object tests/common/TestRunner/CMakeFiles/test_runner.dir/test_module_loader.cpp.o
Linking CXX executable ../../../Binaries/test_runner
/opt/crosstool/gcc-8.3.0-glibc-2.29/x86_64-unknown-linux-gnu/bin/../lib/gcc/x86_64-unknown-linux-gnu/8.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: warning: libz.so.1, needed by ../../../Binaries/libcpprest.so.2.10, not found (try using -rpath or -rpath-link)
/opt/crosstool/gcc-8.3.0-glibc-2.29/x86_64-unknown-linux-gnu/bin/../lib/gcc/x86_64-unknown-linux-gnu/8.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ../../../Binaries/libcpprest.so.2.10: undefined reference to `deflateInit2_'
/opt/crosstool/gcc-8.3.0-glibc-2.29/x86_64-unknown-linux-gnu/bin/../lib/gcc/x86_64-unknown-linux-gnu/8.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ../../../Binaries/libcpprest.so.2.10: undefined reference to `deflate'
/opt/crosstool/gcc-8.3.0-glibc-2.29/x86_64-unknown-linux-gnu/bin/../lib/gcc/x86_64-unknown-linux-gnu/8.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ../../../Binaries/libcpprest.so.2.10: undefined reference to `deflateEnd'
/opt/crosstool/gcc-8.3.0-glibc-2.29/x86_64-unknown-linux-gnu/bin/../lib/gcc/x86_64-unknown-linux-gnu/8.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ../../../Binaries/libcpprest.so.2.10: undefined reference to `inflate'
/opt/crosstool/gcc-8.3.0-glibc-2.29/x86_64-unknown-linux-gnu/bin/../lib/gcc/x86_64-unknown-linux-gnu/8.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ../../../Binaries/libcpprest.so.2.10: undefined reference to `inflateInit2_'
/opt/crosstool/gcc-8.3.0-glibc-2.29/x86_64-unknown-linux-gnu/bin/../lib/gcc/x86_64-unknown-linux-gnu/8.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ../../../Binaries/libcpprest.so.2.10: undefined reference to `inflateEnd'
/opt/crosstool/gcc-8.3.0-glibc-2.29/x86_64-unknown-linux-gnu/bin/../lib/gcc/x86_64-unknown-linux-gnu/8.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ../../../Binaries/libcpprest.so.2.10: undefined reference to `inflateReset'
/opt/crosstool/gcc-8.3.0-glibc-2.29/x86_64-unknown-linux-gnu/bin/../lib/gcc/x86_64-unknown-linux-gnu/8.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ../../../Binaries/libcpprest.so.2.10: undefined reference to `deflateReset'
collect2: error: ld returned 1 exit status
make[2]: *** [Binaries/test_runner] Error 1
make[1]: *** [tests/common/TestRunner/CMakeFiles/test_runner.dir/all] Error 2
make: *** [all] Error 2

**Comment by c72578** [comment]
Is zlib installed on your system? This is typically installed using:
```sudo apt-get install zlib1g-dev```

**Comment by JamieLuo** [comment]
Yes, my system has installed the zlib. Actually I want to use another zlib that I compiled. Anyway right now I could settle down this issue on my side by modify the link.txt. Thank you.
