### ISSUE TITLE
Reusing web::http::client::http_client on Linux leads to crash, works on Windows.

### ISSUE THREAD

**Issue by francisduffy** [microsoft/cpprestsdk#1360]
I am running in to an issue where the attached minimal working example is working as I expect on Windows but leading to a core dump on Linux.

The attached Python files contain a simple dummy server that I use to respond to requests for testing. I run `python3 dummy_server.py` to start listening for requests on `http://localhost:8080`.

The attached cpp file contains the minimal working example. I compiled the cpp file against cpprestsdk v2.10.15 which in turn I have compiled against openssl 1.1.1d and Boost 1.72.0. I compiled on Windows using Visual Studio 2017 and on Linux (CentOS 7.7.1908) using g++ (GCC) 4.8.5. The test program uses a `web::http::client::http_client` instance to POST a dummy body to the server. If the server does not respond with a 200, the request is tried again using the same client instance.

When the server responds with a 200, the Windows and Linux example return the following expected output. Line 40 and 44 of _dummy_server.py_ can be un-commented and lines 41 and 45 can be commented out to show this i.e. to make the dummy server respond with a 200.

```text
Request: POST http://localhost:8080//
Start making request.
Finished making request.
Got response code: 200
Final response code: 200
```

When the server responds with a 500, as the attached Python dummy server does, the Windows example returns the following expected output.

```text
Request: POST http://localhost:8080//
Start making request.
Finished making request.
Got response code: 500
Problem response was: {"status_code": 500, "message": "error"}
Sleep for 20ms, then retry.
Start making request.
Finished making request.
Got response code: 500
Problem response was: {"status_code": 500, "message": "error"}
Sleep for 20ms, then retry.
Final response code: 500
```

However, the Linux example core dumps with the following output.

```text
Start making request.
Finished making request.
Got response code: 500
Problem response was: {"status_code": 500, "message": "error"}
Sleep for 20ms, then retry.
Start making request.
test: /path/to/cpprestsdk/Release/src/http/client/http_client.cpp:172: virtual Concurrency::streams::streambuf<unsigned char> web::http::client::details::request_context::_get_readbuffer(): Assertion `(bool)instream' failed.
Aborted (core dumped)
```

Apologies if I am missing something obvious here. For example, am I allowed to reuse the `web::http::client::http_client` instance in the way that I am in the example? Any help here would be much appreciated. Thanks.

[example.zip](https://github.com/microsoft/cpprestsdk/files/4345425/example.zip)

**Comment by garethsb-sony** [comment]
You can reuse the `http_client` but you shouldn't rely on reusing the `http_request`.

**Comment by francisduffy** [comment]
Hi Gareth, thanks a lot. When I construct the `http_request` inside the for loop as you suggest, everything works fine.
