### ISSUE TITLE
Compilation failure with json_parsing.cpp post 6d0e2b7 

### ISSUE THREAD

**Issue by swathidesai** [microsoft/cpprestsdk#1377]
Hi,
Cpprest build fails with the below errors,

src/json/json_parsing.cpp:1077:20: error: could not convert ‘value’ from ‘std::unique_ptr<web::json::details::_String, std::default_delete<web::json::details::_String> >’ to ‘std::unique_ptr<web::json::details::_Value>’
             return value;
                    ^
Release/src/json/json_parsing.cpp:1089:20: error: could not convert ‘value’ from ‘std::unique_ptr<web::json::details::_Number, std::default_delete<web::json::details::_Number> >’ to ‘std::unique_ptr<web::json::details::_Value>’
             return value;
                    ^
src/json/json_parsing.cpp:1096:20: error: could not convert ‘value’ from ‘std::unique_ptr<web::json::details::_Number, std::default_delete<web::json::details::_Number> >’ to ‘std::unique_ptr<web::json::details::_Value>’
             return value;
                    ^
Release/src/json/json_parsing.cpp:1103:20: error: could not convert ‘value’ from ‘std::unique_ptr<web::json::details::_Boolean, std::default_delete<web::json::details::_Boolean> >’ to ‘std::unique_ptr<web::json::details::_Value>’
             return value;
                    ^

Release/src/json/json_parsing.cpp:1043:28:error: could not convert ‘result’ from ‘std::unique_ptr<web::json::details::_Array, std::default_delete<web::json::details::_Array> >’ to ‘std::unique_ptr<web::json::details::_Value>’
                     return result;

I am on gcc 4.8 and boost_1_68.

This has not been observed in the earlier commit cdae258.

Am I missing something during the build?

Thanks & Regards,
Swathi Desai

**Comment by garethsb-sony** [comment]
OK, my bad! There isn't a sufficiently aged GCC in the CI, but I'll test this for GCC 4.8, as it's occasionally a platform I n need to care about.

**Comment by garethsb-sony** [comment]
@swathidesai Please would you try #1379 and see if it resolves things for you?

**Comment by swathidesai** [comment]
@garethsb-sony #1379 fixed the issue.

Regards,
Swathi Desasi
