### ISSUE TITLE
error: redundant move in return statement 

### ISSUE THREAD

**Issue by jc200** [Microsoft/cpprestsdk#138]
Building the cpp rest sdk in Debug mode on OS X and received following 3 errors.
Below is one of them:

.../casablanca/Release/src/http/common/http_helpers.cpp:275:16: error
    redundant move in return statement [-Werror, -Wredundant-move]
    return std::move(src);

.../casablanca/Release/src/http/common/http_helpers.cpp:275:16: note: 
      remove std::move call here
        return std::move(src);

**Comment by ArkBriar** [comment]
I have just built successfully by removing the first "-Wall" in casablanca/Release/CMakeLists.txt, line 141
```cmake
set(WARNINGS "-Wall -Wextra -Wcast-qual -Wconversion -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-format-attribute -Wmissing-include-dirs -Wpacked -Wredundant-decls")
```
And a better approach is to merge the pr #140

**Comment by ras0219-msft** [comment]
This is fixed in the development branch. Additionally, in the development branch we have a WERROR cmake option that you could disable which should also fix the build issue. (`-DWERROR=0`).
