### ISSUE TITLE
SSL Handshake error in  in Ubuntu and working in windows

### ISSUE THREAD

**Issue by GA39792** [microsoft/cpprestsdk#1396]
#include <cpprest/http_client.h>
#include <cpprest/filestream.h>

using namespace utility;
using namespace web::http;
using namespace web::http::client;
using namespace concurrency::streams;

#define URL_DOMAIN "https://xyz.com"

int main(int argc, char *args[])
{
    if(argc <  2)
    {
        printf("Usage: search_term output_file\n");
        return -1;
    }
    const string_t outputFileName = args[1];

    // Open a stream to the file to write the HTTP response body into.
    auto fileBuffer = std::make_shared<streambuf<uint8_t>>();
    file_buffer<uint8_t>::open(outputFileName, std::ios::out).then([=](streambuf<uint8_t> outFile) -> pplx::task<http_response>
    {
        *fileBuffer = outFile; 

        http_client_config config;
        bool validate = config.validate_certificates();
        std::cout << "validated "  <<  validate  << std::endl;
        config.set_validate_certificates(validate); 
        http_client client(U(URL_DOMAIN), config);
        //http_client client(U(URL_DOMAIN),cfg);*/

        return client.request(methods::GET); /*, uri_builder(U("/search")).append_query(U("q")).to_string());*/
    })

    // Write the response body into the file buffer.
    .then([=](http_response response) -> pplx::task<size_t>
    {
        printf("HTTP response status code %u returned.\n", response.status_code());

        return response.body().read_to_end(*fileBuffer);
    })
    // Close the file buffer.
    .then([=](size_t)
    {
        return fileBuffer->close();
    })
    // Wait for the entire response body to be written into the file.
    .wait();
    return 0;
}

Note : if I explicitly set as false it works but our requirement is that it should work with HTTPS
config.set_validate_certificates(validate); // validate = false
Please sugggest the solution
Error 👍 
terminate called after throwing an instance of 'web::http::http_exception'
  what():  Error in SSL handshake
Aborted (core dumped)

**Comment by GA39792** [comment]
@BillyONeal : Please help its urgent same set of code works for windows
Do I need to do certificate pinning as it fails every time

**Comment by GA39792** [comment]
//working in windows
#include <cpprest/filestream.h>
#include <cpprest/http_client.h>

using namespace utility;
using namespace web::http;
using namespace web::http::client;
using namespace concurrency::streams;

#define URL_DOMAIN "https://env5.westeurope.cloudapp.azure.com/upload/rscdsyncommand/test41.txt?st=2019-11-07T16%3A38%3A14Z&se=2030-10-07T16%3A38%3A00Z&sp=racwdl&sv=2018-03-28&sr=c&sig=6dQIsx7sMyC9UzAbifXGS27AOpiCDPdMez4F6l0EZUM%3D"


/* Can pass proxy information via environment variable http_proxy.
   Example:
   Linux:   export http_proxy=http://192.1.8.1:8080
 */
web::http::client::http_client_config client_config_for_proxy()
{
    web::http::client::http_client_config client_config;
    wchar_t* pValue = nullptr;
    std::unique_ptr<wchar_t, void (*)(wchar_t*)> holder(nullptr, [](wchar_t* p) { free(p); });
    size_t len = 0;
    auto err = _wdupenv_s(&pValue, &len, L"http_proxy");
    if (pValue) holder.reset(pValue);
    if (!err && pValue && len)
    {
        std::wstring env_http_proxy_string(pValue, len - 1);
        if (env_http_proxy_string == U("auto"))
            client_config.set_proxy(web::web_proxy::use_auto_discovery);
        else
            client_config.set_proxy(web::web_proxy(env_http_proxy_string));
    }

    return client_config;
    }

int wmain(int argc, wchar_t* args[])
{
    if (argc < 2)
    {
        printf("Usage: BingRequest.exe search_term output_file\n");
        return -1;
    }
   // const string_t searchTerm = args[1];
    const string_t outputFileName = args[1];

    // Open a stream to the file to write the HTTP response body into.
    auto fileBuffer = std::make_shared<streambuf<uint8_t>>();
    file_buffer<uint8_t>::open(outputFileName, std::ios::out)
        .then([=](streambuf<uint8_t> outFile) -> pplx::task<http_response> {
        *fileBuffer = outFile;

        // Create an HTTP request.
        // Encode the URI query since it could contain special characters like spaces.
        http_client client(U(URL_DOMAIN), client_config_for_proxy());
        return client.request(methods::GET);// , uri_builder(U("/search")).append_query(U("q"), searchTerm).to_string());
            })

        // Write the response body into the file buffer.
                .then([=](http_response response) -> pplx::task<size_t> {
                printf("Response status code %u returned.\n", response.status_code());

                return response.body().read_to_end(*fileBuffer);
                    })

                // Close the file buffer.
                        .then([=](size_t) { return fileBuffer->close(); })

                        // Wait for the entire response body to be written into the file.
                        .wait();

                    return 0;
}

**Comment by garethsb-sony** [comment]
Presumably on Windows you have installed the cert you're using. With the ASIO-based `http_client` you feed to supply the cert programmatically using `set_ssl_context_callback`. There's an example here: https://github.com/sony/nmos-cpp/blob/63637607d3275234bf73306688d76b8144c0b194/Development/nmos/client_utils.cpp#L27-L64

**Comment by GA39792** [comment]
Tried this
   http_client_config config;
        config.set_ssl_context_callback([](boost::asio::ssl::context& context)-> void{
            context.load_verify_file(std::string("/usr/lib/ssl/certs/cacert.pem"));
        });
And passing my certificate file. still the same error

**Comment by GA39792** [comment]
> Presumably on Windows you have installed the cert you're using. With the ASIO-based `http_client` you feed to supply the cert programmatically using `set_ssl_context_callback`. There's an example here: https://github.com/sony/nmos-cpp/blob/63637607d3275234bf73306688d76b8144c0b194/Development/nmos/client_utils.cpp#L27-L64

**Comment by garethsb-sony** [comment]
@GA39792, can you tell us how did you solve your issue?

**Comment by GA39792** [comment]
Sorry, not solved still waiting for some solution. Can you check with the URL why I am getting SSL handshake error with another URL like https:\\www.bing.com or google it works.

**Comment by garethsb-sony** [comment]
OK, sorry, I think you'll have to debug. For problems with an SSL handshake I normally have to use WireShark packet capture to understand why it fails.

**Comment by GA39792** [comment]
Thanks, Gareth it's working with ssl_context I am missing one certificate...
