### ISSUE TITLE
missing cmake package version file (can't use cmake package versioning)

### ISSUE THREAD

**Issue by diablodale** [microsoft/cpprestsdk#1411]
The `cpprestsdk` port is missing the package version file. Therefore it is not possible in cmake to use package version checking as in `find_package(cpprestsdk 2.8.0 CONFIG REQUIRED)`

### Repro

1. Setup a working vcpkg with VS2019 for simplicity
2. `vcpkg install cpprestsdk`
3. Create your app's `CMakeLists.txt` with the needed toolchain file
4. Add to that `CMakeLists.txt` the following: `find_package(cpprestsdk 2.8.0 CONFIG REQUIRED)`

### Result

```
[cmake] CMake Error at C:/njs/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package):
[cmake]   Could not find a configuration file for package "cpprestsdk" that is
[cmake]   compatible with requested version "2.8.0".
[cmake] 
[cmake]   The following configuration files were considered but not accepted:
[cmake] 
[cmake]     C:/njs/vcpkg/installed/x86-windows-static-md-v142-sdk81/share/cpprestsdk/cpprestsdk-config.cmake, version: unknown
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:127 (find_package)
```

### Expected

No errors and a later successful compile using the `cpprestsdk` library.

### Solution

Add package versioning information to the port as described in official cmake docs https://cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#package-version-file

Usually you just set the version as project's property, and then you use CMake's helpers to create a simple Config + Version file like

```cmake
project(xxxx VERSION 2.8.0 LANGUAGES CXX)
...
include(CMakePackageConfigHelpers)
write_basic_package_version_file(
    ${CMAKE_CURRENT_BINARY_DIR}/xxxxxxxxxxxx.cmake
    COMPATIBILITY SameMajorVersion
)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/xxxxxxxxxxxxxx.cmake DESTINATION ${CMAKE_INSTALL_DATADIR}/cmake/xxxxxxxxxxxxxxxx)
```

### Notes and related issues

No reasonable alternative other than to remove package version in `find_package()`. Otherwise, the alternative is to implement what is already built into cmake.

https://github.com/microsoft/cpprestsdk/issues/1382
https://github.com/microsoft/cpprestsdk/issues/686
https://github.com/microsoft/vcpkg/issues/10938

**Comment by c72578** [comment]
Is the file `cpprestsdk-config-version.cmake` installed on your system?
It should be there, e.g.:
`vcpkg\installed\x86-windows\share\cpprestsdk\cpprestsdk-config-version.cmake`

**Comment by diablodale** [comment]
Ah-ha! This issue was fixed here 5 days after my original report on 20 April in the vcpkg repo.
I just now tested with the current v2.10.16 and it happily works.
Sorry for noise. Thanks for very helpful library -- I've used cpprest since 2016.
