### ISSUE TITLE
vcpkg updates?

### ISSUE THREAD

**Issue by patlecat** [microsoft/cpprestsdk#1414]
When can we expect a newer version of cpprestsdk in vcpkg? It's several version behind from months ago.

**Comment by c72578** [comment]
cpprestsdk is up-to-date in vcpkg.
See: https://github.com/microsoft/vcpkg/blob/master/ports/cpprestsdk/CONTROL
`Version: 2.10.16`

**Comment by patlecat** [comment]
Then why does search show me an old version?

```
vcpkg search cpprestsdk
bitserializer-cpp... 0.8              This is an implementation of the BitSerializer archive for serialization JSON ...
cpprestsdk           2.10.14-1        C++11 JSON, REST, and OAuth library The C++ REST SDK is a Microsoft project fo...
```

And why does the update think there's nothing to update?

```
 vcpkg update
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
```

vcpkg list

```
cpprestsdk:x64-windows                             2.10.14-1        C++11 JSON, REST, and OAuth library The C++ REST...
cpprestsdk[brotli]:x64-windows                                      Brotli compression support
cpprestsdk[compression]:x64-windows                                 HTTP Compression support
cpprestsdk[default-features]:x64-windows                            Features installed by default
cpprestsdk[websockets]:x64-windows                                  Websockets support
```

**Comment by c72578** [comment]
The sources of vcpkg on your system are outdated.
If you have obtained vcpkg using
`git clone https://github.com/Microsoft/vcpkg.git`
then update it using e.g.:
`git pull`

**Comment by patlecat** [comment]
Okay you are right, but it seems weird that the version of vcpkg influences the content of packages stored and managed on a server. How is this even related and why?

**Comment by c72578** [comment]
The packages are not stored on a server, they are built locally on your system.
The "recipes", which include the version of a package and how to build it, are stored locally in the `CONTROL` and `portfile.cmake` files.
See e.g. inside the folder `./ports/cpprestsdk/` of your local vcpkg git directory. In case of cpprestsdk, the source code is downloaded from github and then compiled locally (from `portfile.cmake`):
```cmake
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO Microsoft/cpprestsdk
    REF v2.10.16
    SHA512 d850b26051439dd10edcecd006075c64c61c565193cd76870af175bd343a72ecc59485deb0f907807071a57dd256b67139ad5d016f19cb38f7142357f430be1c
    HEAD_REF master
) 
```
This downloads the file `Microsoft-cpprestsdk-v2.10.16.tar.gz`, which you will find in the `./downloads` subdir ...

**Comment by patlecat** [comment]
I bursted out laughing. Okay but thanks for the explanation.
