### ISSUE TITLE
Json parsing

### ISSUE THREAD

**Issue by own2pwn** [Microsoft/cpprestsdk#142]
When im trying to parse this
https://steamcommunity.com/login/getrsakey/?username=user

```
json::value jsonResp = getRSAKeyResponse.extract_json().get();
try
        {
            auto s = jsonResp.at(L"success");
                       //or auto s = jsonResp.at(L"publickey_mod");
        }

        catch (const std::exception& e)
        {
            printf("Error exception:%s\n", e.what());
        }
```

i got
`
not an onject exception
`

**Comment by ras0219-msft** [comment]
I am unable to reproduce this on the development branch. Could you please include the exact JSON document you're receiving from the API?

**Comment by Wbdn** [comment]
'''
{"success":true,"publickey_mod":"AFC44772C3D028C6A9D8867DDD62BDDCFC1A6A37341A1023E9D3531DBE9F1B948B076E8E7D1B302E09C98950F4ABB99E81926044DBF856D25D299C4D7C13F5ADB4A527B18AD6F00D2BD7D2277CA828D960BBF6A0F18C14A439BB95A0AF677EA30405760F15787231980817D121AAB6F6DDE7B8A8C5B95DA0EA3C663C222AFD592FA1C466B50C02354DCB4201B8B1B26CC06389E29D964DC30C0CE7C153E7C5CC16C53663F8FD85E93EDA083A974F2F36CC0170C8859D232B8E1EDC4BC03FDF4B34117313186C831076B88A7EA5A52808C51931925E2D7AC2DF3C3C253010C412A0B2D0FB4EFFB614130E4A1EC687EA4BA0CD5B709E7EF961A2B9860CB3667B57","publickey_exp":"010001","timestamp":"291879950000","token_gid":"cc95653e09d3025"}
'''

**Comment by ras0219-msft** [comment]
I'm still not able to reproduce this issue. Could you try the development branch locally and ensure this reproduces?
Here is the code I'm using (on windows):
```
#include "cpprest/json.h"
#include <stdio.h>

auto jsonval = LR"({"success":true,"publickey_mod":"AFC44772C3D028C6A9D8867DDD62BDDCFC1A6A37341A1023E9D3531DBE9F1B948B076E8E7D1B302E09C98950F4ABB99E81926044DBF856D25D299C4D7C13F5ADB4A527B18AD6F00D2BD7D2277CA828D960BBF6A0F18C14A439BB95A0AF677EA30405760F15787231980817D121AAB6F6DDE7B8A8C5B95DA0EA3C663C222AFD592FA1C466B50C02354DCB4201B8B1B26CC06389E29D964DC30C0CE7C153E7C5CC16C53663F8FD85E93EDA083A974F2F36CC0170C8859D232B8E1EDC4BC03FDF4B34117313186C831076B88A7EA5A52808C51931925E2D7AC2DF3C3C253010C412A0B2D0FB4EFFB614130E4A1EC687EA4BA0CD5B709E7EF961A2B9860CB3667B57","publickey_exp":"010001","timestamp":"291879950000","token_gid":"cc95653e09d3025"})";

int main() {
    auto jsondoc = web::json::value::parse(jsonval);
    auto p = jsondoc.at(L"success");
    
    if (p.as_bool())
        printf("true\n");
    else
        printf("false\n");

    return 0;
}
```
