### ISSUE TITLE
web::uri endpointURI()

### ISSUE THREAD

**Issue by srijanc** [microsoft/cpprestsdk#1459]
I am new to this library but here is my issue, (please forgive me if I am blunt in my knowledge)
Below code when used on a Linux system is working as expected but when written on a Windows 10 system (I am using QT editor), it is throwing error of unable to locate the matching constructor for endpointURI(). Please suggest me in case something needs to be corrected when used on a windows system. I have imported all the required libraries.

`
    void BasicController::setEndpoint(const std::string &value) {
        uri endpointURI(value);  // Error line
        uri_builder endpointBuilder;

        endpointBuilder.set_scheme(endpointURI.scheme());

    }
`
Error: No matching constructor for initialization of 'web::uri'
Any suggestion would be helpful.

**Comment by garethsb-sony** [comment]
Constructor of `web::uri` takes `utility::string_t` which is `std::string` on Linux but `std::wstring` on Windows. At the point that you want to convert from `std::string` to `utility::string_t` use `utility::conversions::to_string_t` which in your example would be a no-op on Linux.

**Comment by srijanc** [comment]
This resolves my issue. Thank you for your help.
