### ISSUE TITLE
Any plans to utilise part of C++17, or will be C++14 compatible?

### ISSUE THREAD

**Issue by silentWatcher3** [microsoft/cpprestsdk#1501]
It doesn't likely affect much either way, but to know current status of support of C++14 will continue, or shift to newer standard

**Comment by AdityaGupta150** [comment]
Kuchh bhi likh diya h be 😆 😆 

> 
> 
> It doesn't likely affect much either way, but to know current status of support of C++14 will continue, or shift to newer standard

**Comment by patlecat** [comment]
C++17 is most welcome indeed with things like string_view and hopefully better multi-threading, etc.

**Comment by barcharcraz** [comment]
there are no plans to add support for c++17/20 constructs. We are not working on any new features for cpprestsdk at this time
