### ISSUE TITLE
How to upgrade libcpprestSDK in Linux ?

### ISSUE THREAD

**Issue by Gaurav-Karu** [microsoft/cpprestsdk#1506]
I want to upgrade the .so file from 2.8 to 2.16 latest, Becoz I have faced one issue recenlty when I was trying to upload the packages to BLOB storage its given an exception saying "Request Cancelled by the User"

If I am upgrade the library does this issue will be fixed

**Comment by barcharcraz** [comment]
ask your linux package maintainer. We do not control the linux packages for cpprestsdk.
