### ISSUE TITLE
Cpprestsdk has different behavior from one Ubuntu 18.04LTS vm to another with POST method

### ISSUE THREAD

**Issue by leskodan** [microsoft/cpprestsdk#1513]
I am using the cpprestsdk to send a serialized json object to a custom API using the following code and getting a seg fault (I believe) somewhere in the .wait():

```
auto postJson = http_client("https://my.api.url/endpoint")
.request(methods::POST, "", serializedJson, "application/json")
.then([](http_response response)
{
cout << "got response\n";
if(response.status_code() != 200)
{
  cout << "Response was not 200.\n";
}
else
{
  cout << "Response was 200.\n";
  return response.extract_json();
}
}).wait();
```
I will note that the post completes successfully, but the application crashes soon after. This is not universal however. I have this code running on one vm with no seg fault, it simply returns to the listener after executing a post. However, on an identical vm (Ubuntu 18.04LTS with all the same dependencies) which I am attempting to use as a dev environment, I get the seg fault.

Is there a way of building the sdk or linking it that I am missing that can cause this discrepancy in behavior?

**Comment by barcharcraz** [comment]
there may be some kind of linkage error, you should consider building your application with the various sanitizers, I'm not going to have time to investigate this issue for a while.

**Comment by leskodan** [comment]
Thanks for advising @barcharcraz. I've pivoted to use curl for the time being so no worries.
