### ISSUE TITLE
Exception thrown on instantiating http_client

### ISSUE THREAD

**Issue by SimAddict** [microsoft/cpprestsdk#1514]
Hi everyone. I'm trying to run a simple example with http_client, but on trying to create the http_client instance, it crashes with the exception in the attached image. 

The line of code that triggers the exception is -

http_client client(U("https://jsonplaceholder.typicode.com/photos"));

That's the first line in main()

Please help...

![Capture1](https://user-images.githubusercontent.com/3987936/95970546-c01c0d80-0e18-11eb-8504-840482d51fdc.PNG)

**Comment by SimAddict** [comment]
OK, found it, I apparently was trying to link release lib to my debug build.

Thanks go to https://github.com/Microsoft/cpprestsdk/issues/694

**Comment by Nick7K** [comment]
To save anyone else spending as much time on this issue as I have.

I just ran into an issue where something changed the configuration for my debug builds to Release.

Properties, Configuration\vcpkg\Vcpkg configuration
