### ISSUE TITLE
Build error on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Pintulalmeena** [Microsoft/cpprestsdk#152]
followed the documentation at https://github.com/Microsoft/cpprestsdk/wiki/How-to-build-for-Linux
and got an error ,error description is given below  
.......
[ 33%] Building CXX object tests/common/TestRunner/CMakeFiles/test_runner.dir/test_module_loader.cpp.o
[ 34%] Linking CXX executable ../../../Binaries/test_runner
CMakeFiles/test_runner.dir/test_runner.cpp.o: In function 

`boost::filesystem::path::path<boost::filesystem::directory_entry>(boost::filesystem::directory_entry const&, boost::enable_if<boost::filesystem::path_traits::is_pathable<boost::decay<boost::filesystem::directory_entry>::type>, void>::type*)':

/usr/include/boost/filesystem/path.hpp:140: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
collect2: error: ld returned 1 exit status
tests/common/TestRunner/CMakeFiles/test_runner.dir/build.make:123: recipe for target 'Binaries/test_runner' failed
make[2]: *** [Binaries/test_runner] Error 1
CMakeFiles/Makefile2:296: recipe for target 'tests/common/TestRunner/CMakeFiles/test_runner.dir/all' failed
make[1]: *** [tests/common/TestRunner/CMakeFiles/test_runner.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Danimoth** [comment]
Hi there,
Please try: 
```bash
sudo apt-get install g++ git make libboost1.58-all-dev libssl-dev cmake
```

instead of 
```bash
sudo apt-get install g++ git make libboost-all-dev libssl-dev cmake
```

**Comment by Pintulalmeena** [comment]
Thanks :
