### ISSUE TITLE
[MacOs]: Linking to foundation library should be private / internal

### ISSUE THREAD

**Issue by Milerius** [microsoft/cpprestsdk#1522]
ref: https://github.com/microsoft/cpprestsdk/blob/7fbb08c491f9c8888cc0f3d86962acb3af672772/Release/src/CMakeLists.txt#L97

This cause terrible trouble when installing through VCPKG with a specific sdk:
<img width="1644" alt="Capture d’écran 2020-10-26 à 12 49 34" src="https://user-images.githubusercontent.com/21139416/97171484-cce02000-178d-11eb-9fe0-86894456bcd5.png">

Specific user SDK should never appears in `INTERFACE_LINK_LIBRARIES`, we cannot force user on a specific SDK even if he build this specific deps targeting let's say 10.13, it's perfectly fine to create a project that use 10.15 SDK and link a libraries that is targeting 10.13 SDK but we should not force it in the interface link libraries.

How to reproduce:

- Install cpprestsdk through VCPKG targeting a specific SDK (10.13)

- Try to link cpprestsdk to a project that use Obj-C function and cpprestsdk and target a most recent SDK let's say 10.15

for the ref there is my code making this fiesta happening:

```cpp
#include <Availability.h>
#include "manager.hpp"

#ifdef __MAC_10_15
#import <AppKit/AppKit.h> // Here because of cpprestsdk will search into the wrong SDK place
#endif

#ifdef __MAC_10_15
static NSColor *colorFromRGB(unsigned char r, unsigned char g, unsigned char b)
{
    return [NSColor colorWithCalibratedRed:(r/255.0f) green:(g/255.0f) blue:(b/255.0f) alpha:1.0];
}
#endif

void atomic_dex::mac_window_setup(long winid, bool fullscreen)
{
    (void)winid;
    (void)fullscreen;
#ifdef __MAC_10_15
    NSView *nativeView = reinterpret_cast<NSView *>(winid);
    NSWindow* nativeWindow = [nativeView window];
    NSWindowStyleMask windowMask = NSWindowStyleMaskFullSizeContentView | NSWindowStyleMaskBorderless | NSWindowStyleMaskTitled | NSWindowStyleMaskClosable | NSWindowStyleMaskMiniaturizable | NSWindowStyleMaskResizable;
    if (fullscreen) {
        windowMask |= NSWindowStyleMaskFullScreen;
    }
    [nativeWindow setStyleMask: windowMask];
    [nativeWindow setTitlebarAppearsTransparent:YES];
    NSColor *myColor = colorFromRGB(30, 41, 56);
    [myColor set];
    [nativeWindow setBackgroundColor: myColor];
    [nativeWindow setTitleVisibility: static_cast<NSWindowTitleVisibility>(1)];
#endif
}
```

**Comment by lizhiyong2000** [comment]
same problem occured to me

set_target_properties(cpprestsdk::cpprest PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "CPPREST_FORCE_HTTP_CLIENT_ASIO;CPPREST_FORCE_HTTP_LISTENER_ASIO"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "cpprestsdk::cpprestsdk_boost_internal;cpprestsdk::cpprestsdk_openssl_internal;**### **/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/CoreFoundation.framework;/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Security.framework****;cpprestsdk::cpprestsdk_boost_internal;cpprestsdk::cpprestsdk_openssl_internal;cpprestsdk::cpprestsdk_boost_internal;cpprestsdk::cpprestsdk_openssl_internal"
)

**Comment by Milerius** [comment]
https://github.com/microsoft/cpprestsdk/pull/1523
