### ISSUE TITLE
Inconsistent tag 2.10.17

### ISSUE THREAD

**Issue by egorpugin** [microsoft/cpprestsdk#1552]
Previous tags has `v` prefix - `v2.10.16`.
This breaks some scripts.

**Comment by garethsb-sony** [comment]
Adding +1 as comment, since 👍 reactions don't generate any notifications to maintainer.

**Comment by mloskot** [comment]
This is a trivial mistake but it is actually annoying for those who fork or refer to the repo via submodule in any semi- or automated fashion. I'm not suggesting a slap in back of release manager's head, but please, spare a minute and fix it :-)

**Comment by garethsb-sony** [comment]
And developers looking for the most recent tag can be misled by GitHub UI -

![image](https://user-images.githubusercontent.com/31761158/106270818-7409a300-6226-11eb-8c90-1d1edce557c7.png)

(I know the 2.10.17 tag appears first in the Releases and Tags pages, but the drop-down menu may be first point of call for many.)

**Comment by barcharcraz** [comment]
I'll create duplicate tags with the v prefix. I'm sorry, 2.10.17 was the first release I did as maintainer!

**Comment by mloskot** [comment]
@barcharcraz the correction is much appreciated, thank you!

**Comment by garethsb-sony** [comment]
Thanks :-)

**Comment by barcharcraz** [comment]
and done. I did not create a new release in github, I simply made duplicate tags, hopefully it won't cause release-monitoring (like anitya) to freak out, but who knows.
