### ISSUE TITLE
Does it exist this problem when sending request using cpprest, it will delay to send the request about 3 seconds later?

### ISSUE THREAD

**Issue by okayabc** [microsoft/cpprestsdk#1556]
If this problem exists, does the master solve it?
If this problem doesn't exist, what's the possible reason?
Thx!

**Comment by barcharcraz** [comment]
This is not enough information to investigate or reproduce the problem. Please provide some code reproducing the issue and information about your environment (OS, cpprestsdk version, backend, etc).
