### ISSUE TITLE
I want to create a web service using c++ rest sdk

### ISSUE THREAD

**Issue by yashmahes** [Microsoft/cpprestsdk#157]
I want to create a web service using c++ rest sdk ,I am new to c++ rest sdk,Please help me in creating a web service using c++ rest sdk.

**Comment by ras0219-msft** [comment]
Take a look at our samples and reference documentation. If you have specific questions about library APIs, please first read the report issues guidelines.

https://github.com/Microsoft/cpprestsdk/tree/master/Release/samples
http://microsoft.github.io/cpprestsdk/namespaces.html
https://github.com/Microsoft/cpprestsdk/wiki/Make-a-contribution-and-report-issues
