### ISSUE TITLE
ninja-build really necessary

### ISSUE THREAD

**Issue by jade2k11598** [microsoft/cpprestsdk#1586]
According to the [build instructions for linux](https://github.com/Microsoft/cpprestsdk/wiki/How-to-build-for-Linux), it requires one to install `ninja-build`.  Is that really necessary?  This build is largely cmake, which suffices to to just trigger `make` to build.

**Comment by barcharcraz** [comment]
the instructions are not the _only_ way to build, they are just what we tend to use when building. Ninja is faster and smaller than make (although on linux you probably already have make, but maybe not ninja). Make should work fine, however.
