### ISSUE TITLE
this Json is way more complicated, I have no idea how do I build this Json with cpprestsdk?

### ISSUE THREAD

**Issue by abcdef123ghi** [microsoft/cpprestsdk#1589]
"input": {
		"druginfo": {
			"acct_used_flag": "1",
			"dise_codg": ""
		}
}

**Comment by barcharcraz** [comment]
Closing this as not a bug, if you can provide more information about the problem you're encountering you can reopen the issue.

**Comment by abcdef123ghi** [comment]
> Closing this as not a bug, if you can provide more information about the problem you're encountering you can reopen the issue.

Sorry for any cause inconvenience

**Comment by abcdef123ghi** [comment]
Btw I have resolved the problem
