### ISSUE TITLE
compile error due to ambiguous 'credential'

### ISSUE THREAD

**Issue by hshixun** [Microsoft/cpprestsdk#159]
in the file:
cpprestsdk/Release/tests/functional/http/client/proxy_tests.cpp
Line 100
**credentials cred(U("artur"), U("fred")); // relax, this is not my real password**
compiler complains about ambiguity (krb5.h)
should use  
***web::credentials  cred(U("artur"), U("fred"));*** 

build environment: CentOS 6.7/gcc 4.9.3

**Comment by ras0219-msft** [comment]
This is fixed in the development branch.
