### ISSUE TITLE
Makefile Error 65 When Building for iOS

### ISSUE THREAD

**Issue by joshhaines** [Microsoft/cpprestsdk#160]
I'm following the documentation on how to build for iOS, but I am stuck on the step [Building the C++ Rest SDK](https://github.com/Microsoft/cpprestsdk/wiki/How-to-build-for-iOS#building-the-c-rest-sdk). I'm getting the following error, and I'm not really sure what it means. Has anyone else run into this?

```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/admin/Documents/casablanca/Build_iOS/build.debug/build.i386/src/casablanca.build/Debug-iphonesimulator/cpprest.build/Objects-normal/i386/http_helpers.o src/http/common/http_helpers.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make[2]: *** [CMakeFiles/sim] Error 65
make[1]: *** [CMakeFiles/sim.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by persenlee** [comment]
I get the same error。I use cmake  generate Xcode project ,then I build target,I found some error。after fix those error.  make pass

**Comment by ras0219-msft** [comment]
This looks like just a summary of the failures during the build. Try rerunning the build with verbose output and paste the full log here.

**Comment by joshhaines** [comment]
I actually tried the development branch, and it worked. If I get the time today then I'll try again with verbose output on the master branch.
