### ISSUE TITLE
Missing file version, copyright and Digital Signatures for cpprest_2_10.dll

### ISSUE THREAD

**Issue by oneiric** [microsoft/cpprestsdk#1601]
Hi,

After downloading the CPPRESTSDK dlls by the vcpkg command, we find some DLL properties  (File Version , copyright, digital signatures ) are missing in this cpprest_2_10.dll. But our product requires these DLL properties for the security reasons.

Do you have any plan to support these properties?

Best Regards,
Alex

**Comment by barcharcraz** [comment]
We don't plan to sign the DLLs, as we're not the one building them (vcpkg builds them on your machine). As for file version and copywright I'd accept a good pull request that adds them via the appropriate cmake properties.

**Comment by oneiric** [comment]
We have switched to static library. So no need for dll version, copyright or digital signatures.
I will close this issue.
