### ISSUE TITLE
Support for Centos7

### ISSUE THREAD

**Issue by HarryFHNg** [microsoft/cpprestsdk#1619]
Any plan for cpprestsdk to support Centos7 OS in near future?

**Comment by barcharcraz** [comment]
what does support mean to you? We don't have any plans to make packages for centos 7 (and we don't support any of the linux packages in the distros, they are supported by the package maintainer who maintains them for the distro).

Is there a particular thing that's causing cpprestsdk to fail to compile on centos 7?
