### ISSUE TITLE
Recommendations for C++ REST libraries for new projects

### ISSUE THREAD

**Issue by kyle-klassy** [microsoft/cpprestsdk#1647]
Is there a C++ REST library or package that Microsoft recommends for new projects now that the C++ REST SDK has been moved to maintenance mode? Is there an equivalent library for cpp that is supported?

**Comment by Barenboim** [comment]
Recommending: https://github.com/sogou/workflow
~~~cpp
#include <stdio.h>
#include "workflow/WFHttpServer.h"

int main()
{
    WFHttpServer server([](WFHttpTask *task) {
        task->get_resp()->append_output_body("<html>Hello World!</html>");
    });

    if (server.start(8888) == 0) { // start server on port 8888
        getchar(); // press "Enter" to end.
        server.stop();
    }

    return 0;
}
~~~

**Comment by Majestro000** [comment]
@Barenboim Made in China 👎

**Comment by barcharcraz** [comment]
We usually recommend libcurl or Qt's networking support library.
