### ISSUE TITLE
Are the tasks using HTTP client thread-safe?

### ISSUE THREAD

**Issue by dyong0** [Microsoft/cpprestsdk#165]
Hi, I'd like to question, but I couldn't find where to post questions. I put this here then.

I'm making a program with multiple threads, which call REST APIs to a remote server. So I need a thread-safe HTTP client. This library looks like supporting thread-safe HTTP clients for REST API calls. Is this HTTP client really thread-safe?

**Comment by ras0219-msft** [comment]
Yes, all of the `http_client` APIs are thread safe. If you find any APIs which are not, please report them as bugs.

**Comment by dyong0** [comment]
@ras0219 Thanks for your answer!

**Comment by chenziliang** [comment]
Is there any documentation for this although it is confirmed http_client is multi-thread safe. It is a critical piece of information which i expect to doc.
