### ISSUE TITLE
Locale bug

### ISSUE THREAD

**Issue by CRC32EX** [microsoft/cpprestsdk#1715]
# Steps to reproduce this issue

1. Write code

<b>vcpkg.json</b>
```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "websocket-test",
  "version": "1.0.0",
  "dependencies": [
    {
      "name": "cpprestsdk",
      "features": [ "websockets" ]
    }
  ]
}
```

<b>Source.cpp</b>
```cpp
#include <cpprest/ws_client.h>

int main() {
    std::locale::global(std::locale("Japanese"));

    web::websockets::client::websocket_callback_client client;
    client.connect(U("wss://example.com:7000/")).then([&client]() {
        std::wcout << L"connected" << std::endl;
    });

    while (true) { Sleep(1000); }
    return 0;
}
```

3. Execute
4. `connected` not appear.

# Possible solution
Remove this line works successfully.
I don't know why.

```cpp
std::locale::global(std::locale("Japanese"));
```

# Environment
- vcpkg version 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6
- cpprestsdk Version: 2.10.18
- VisualStudio 2022 Community 64bit Version 17.1.6
- Windows 11 21H2

**Comment by barcharcraz** [comment]
According to https://docs.microsoft.com/en-us/cpp/c-runtime-library/country-region-strings?view=msvc-170 Japanese is not actually a valid "language string", which surprised me.

**Comment by CRC32EX** [comment]
I'm sorry, It's not `cpprestsdk` side problem. I think.

Remove this line

```cpp
std::locale::global(std::locale("Japanese"));
```

and, use these APIs to emit Japanese strings to console. Solved.

```txt
MultiByteToWideChar
WideCharToMultiByte
```

ref: https://nekko1119.hatenablog.com/entry/2017/01/02/054629
