### ISSUE TITLE
Unable to find NuGet package

### ISSUE THREAD

**Issue by candychiu** [Microsoft/cpprestsdk#176]
Hi, I am following the tutorial to try to get a simple app up and running.  I haven't not been able to download the NuGet package.

I tried to search for "C++ REST SDK" or "Casablanca", neither returned a package.  Did I search for the wrong string? 

The steps I took so far:
1. Create a solution with a C++ Console Application with Precompiled Headers.  
2. Manange NuGet Packages.. for the project above.  --> (not working)

I am using Visual Studio 2015 Update 2.

Thanks.

**Comment by candychiu** [comment]
I was able to download via NuGet's Package Manager Console.

**Comment by DvoryankinEvgeny** [comment]
Go to menu Tools - Options - Nuget Package Manager - Package Source and check available package source. I have one record https://api.nuget.org/v3/index.json and search with key word "Casablanca" works perfectly.

**Comment by ras0219-msft** [comment]
Glad to hear you solved the issue.
