### ISSUE TITLE
Support /Zc:wchar_t-

### ISSUE THREAD

**Issue by KrishnaPG** [Microsoft/cpprestsdk#179]
Getting this error:

```
cpprestsdk\include\cpprest/streams.h(467): error C2766: explicit specialization; 'Concurrency::streams::_type_parser_integral_traits<utf16char>' has already been defined
1>  cpprestsdk\include\cpprest/streams.h(462): note: see previous definition of '_type_parser_integral_traits<unsigned short>'
```

This is happening when `wchar_t` is opted to be not treated as built-in type (which is required for Qt and some other character processing libraries)

![image](https://cloud.githubusercontent.com/assets/4610831/16106093/d5ff39ae-33ae-11e6-8508-90cb3a098fe2.png)

**Comment by Jiebour** [comment]
so what is your solution?

**Comment by MadaanGagesh** [comment]
hey, facing the same issue, but at the very starting and just trying out the sample http client prgram....could you tell me how you solved it...?

**Comment by pvanulden** [comment]
Also having this issue...

**Comment by jvsun** [comment]
+1
