### ISSUE TITLE
http_client Connect to HTTPS server

### ISSUE THREAD

**Issue by gtrunso** [Microsoft/cpprestsdk#18]
I've a webservice running in node.js under the protocol HTTPS.
Could someone give an insight of how to perform this connection? I can't figure it out. 

Thanks in regards.

**Comment by Shedon** [comment]
but how to specify my certificate?

**Comment by gigaplex** [comment]
Do you mean client side certificates? You didn't mention anything like that in the original question.

**Comment by Shedon** [comment]
/*Do you mean client side certificates?*/
yes,

/*You didn't mention anything like that in the original question.*/
i'm not the topic starter

**Comment by gigaplex** [comment]
> /Do you mean client side certificates?/
> yes,

Then that's a different question entirely. I don't think cpprest currently supports client side certificates. You may be able to work around the limitation by getting access to the native handle and using platform specific code.

> /You didn't mention anything like that in the original question./
> i'm not the topic starter

My apologies.

**Comment by ras0219-msft** [comment]
Closing, since original question has been answered. Please feel free to open a separate issue about client side certificates.
