### ISSUE TITLE
PVS-Studio

### ISSUE THREAD

**Issue by AndreyKarpov** [Microsoft/cpprestsdk#183]
One of the Microsoft development teams already uses PVS-Studio analyzer in their work. It's great, but it's not enough. That's why I keep demonstrating how static code analysis could benefit developers, using Microsoft projects as examples. We scanned Casablanca project three years ago and found nothing. As a tribute to its high quality, the project was awarded with a "bugless code" medal. As time went by, Casablanca developed and grew. PVS-Studio's capabilities, too, have significantly improved, and now I've finally got the opportunity to write an article about errors found by the analyzer in Casablanca project (C++ REST SDK). These errors are few, but the fact that their number is still big enough for me to make this article, does speak a lot in favor of PVS-Studio's effectiveness. Continue read: http://www.viva64.com/en/b/0406/

**Comment by grahamreeds** [comment]
To be fair to Casablanca these are all in the example Black Jack code and
are issues with the application logic, not the underlying API. It isn't
supposed to be a tutorial on how to write a black jack server but how to
use the Casablanca library in a clear way.

I agree that these are bugs but curious that there were none reported in
the library itself...

GR

**Comment by ras0219-msft** [comment]
Thank you for bringing up the blog post; we'll be happy to address the issues raised.

Fortunately, all but one of the issues are in the BlackJack sample code (not in the core library).
