### ISSUE TITLE
How to detect JSON charset before extraction

### ISSUE THREAD

**Issue by damienhocking** [Microsoft/cpprestsdk#185]
Is there a way to do this, or detect the charset of the whole request?

**Comment by ras0219-msft** [comment]
I assume you mean JSON content type, such as application/json, application/xjson, etc. The charset for JSON is specified by the RFC to always be UTF-8.

In the first continuation after `http_client::request()`, you can call
`http_response::headers()` to get the `http_headers` object. On that, you can call `http_headers::content_type()` to get the content type header.
```
client.request(/*...*/).then([](http_request req)
{
    if (req.headers().content_type() == U("application/json")) { /*.....*/ }
});
```

Note that unfortunately in the wild there are many different content types in use. Our list of valid JSON content types is available at https://github.com/Microsoft/cpprestsdk/blob/621f0daeda554ab897312bb8d622bca0fc19a923/Release/src/http/common/http_msg.cpp#L452.

**Comment by damienhocking** [comment]
Actually I meant UTF8 vs UTF16.

Damien
