### ISSUE TITLE
Web server with multiple endpoints

### ISSUE THREAD

**Issue by gaultier** [microsoft/cpprestsdk#186]
Hello, I have been going through the samples and the code and I have a question about implementing a webserver offering mutlitple endpoints. What is the preferred way:
- having one `http_listener` per endpoint (passing the string endpoint to the constructor)
- using `http_server` (abstract) / `http_linux_server` and registering the listeners with `register_listener`

Thing is,  `register_listener` takes a `http_listener_impl`, which is a private member of `http_listener` so there is no obvious way to obtain one.

I have implemented a simple webserver using solution one [here](https://bitbucket.org/snippets/edgelab/n4Lay) (to build put it in a directory under `samples`, add the directory to the CMakeLists.txt in the parent directory, and add a CMakeLists.txt in the new directory on the same model as other samples), and am currently wondering about solution two.

I know this is still experimental, and thank you for any answer. I found so far the code and the tests really high quality, thank you for creating a good web library for C++!

Whatever the answer may be, we could update the samples to reflect it.

Info: 
Ubuntu 14.04
x86_64
gcc 5.1.1

**Comment by ras0219-msft** [comment]
Hi gaultier, I'm glad you're enjoying the library so far. Thanks for including your system information :).

One option for handling separate endpoints is exactly what you found. You can make separate `http_listener`'s and add individual handlers (your linked code looks perfectly fine using this approach).

The other approach is to use a single `http_listener` and do your own routing by checking the request paths in the support handler and calling your own callbacks as appropriate. This might be easier if you can share code between different routes, but it can also be more complex.

**Comment by JengdiB** [comment]
Hi gaultier, 

My solution is to use a single http_listener and do routing by myself. I redirect all incoming requests to one handler function to route where should the request end up. 

I did something like

`http_listener listener(baseURI);`
`listener.support(routingHandler);`
`listener.support(http::methods::OPTIONS, routingHandler);// in case you want to handle OPTIONS.`

**Comment by gaultier** [comment]
Thank you for your swift answers. Do you think the documentation and examples should be updated accordingly to make this point clear? 

If needed I could submit a PR for that.

**Comment by ras0219-msft** [comment]
Roughly what documentation changes would you suggest? A PR would be ideal, but I'd be happy to discuss the general shape of the changes without one.

**Comment by gaultier** [comment]
It could be a sample http server, with 2 or 3 different endpoints. One file, located in the `samples` directory.
This way it would be easier to grasp than with the blackjack client + server example, and would also show how to implement a rest service (contrary to the blackjack server who does not offer a rest api I think).

So something like a toto app:
GET /health
GET, POST, DELETE, PUT /todos

Since it seems that nowaday the 'todo' app is the 'hello  world' for the web :)

**Comment by prabhakarjuzgar** [comment]
Hi,

Is it the same reason, the following example dumps, when a open is executed?

int main()
{
   http_listener listener(L"http://localhost/restdemo");
 
   listener.support(methods::GET, handle_get);
   listener.support(methods::POST, handle_post);
   listener.support(methods::PUT, handle_put);
   listener.support(methods::DEL, handle_del);
 
   try
   {
      listener
         .open()   <<<<<<<<<<<<<<<<<<<<<<<<<<<<< dumps here
         .then([&listener](){TRACE(L"\nstarting to listen\n");})
         .wait();
 
      while (true);
   }
   catch (exception const & e)
   {
      wcout << e.what() << endl;
   }
 
   return 0;
}

**Comment by LeonineKing1199** [comment]
I'm so glad I found this because I had the exact same question!

I think the best approach is to actually not use multiple listeners. Listening on just `ip:port` allows you to parse the relative hostname and then decide on a handler from there.

Because there's the concurrency runtime in the background, routing can be offloaded to a separate task where everything can be taken care of from there so the main listening thread can be uninterrupted.

I'm not sure how memory efficient each listener is but only using one listener should allow you keep both performance and memory efficiency.

**Comment by Maktm** [comment]
I don't understand something. How does using one listener work? The way I'm imagining it now, the one listener handles one incoming connection at a time and blocks all incoming connections until that one connection is complete with its request (which includes routing to the correct path, calling the callback and responding). By routing does everyone mean handing over the work to some other service/application?

**Comment by LeonineKing1199** [comment]
In a way, yes.

The real goal is, receive incoming request and then handle it in a separate task. cpprestsdk makes handling the request somewhat straight-forward because you can just use PPLX. But what we're discussing is matching URIs to the correct functions.

**Comment by VovanSychov** [comment]
Hello, I make a Server using cpprestsdk.  Every time I run server, it falls. Here is my code. What I do something wrong?
[Server.txt](https://github.com/microsoft/cpprestsdk/files/3882523/Server.txt)
