### ISSUE TITLE
Documentation then Ambiguity 

### ISSUE THREAD

**Issue by bessermt** [Microsoft/cpprestsdk#190]
There are a number references to the .then() member function:

For example:

http://microsoft.github.io/cpprestsdk/classpplx_1_1task.html#adeea53eacc5b9d4ccca60c36f3ee7305

says:

An internal version of then that takes additional flags 

This is incorrect English. I think you meant:

An internal version of member function ".then(params)" that takes additional flags

It is likely someone reading documentation is unfamiliar with the library since it can be reasonably expected this is the reason a user is reading documentation. This means it is easy to read the sentence as incorrect English given the word "then" is also a valid English word.

**Comment by ras0219-msft** [comment]
Some additional markup around references to member functions such as `.then` would definitely improve readability.

I'd be happy to merge a PR that adds these.

**Comment by ras0219-msft** [comment]
I'm closing this in favor of #189 .
