### ISSUE TITLE
Can i include openssl library to libcpprest.a and boost.framework

### ISSUE THREAD

**Issue by phucpd** [Microsoft/cpprestsdk#193]
When i completed build libcpprest and put it to ios xcode project, it requirements copy openssl/lib and openssl/include into xcode project. 
My question is: can i build and including openssl into libcpprest.a and boost.framework that i no need to copy openssl/lib + openssl/include into xode project ?

Thanks

**Comment by ras0219-msft** [comment]
This is theoretically possible, however very difficult to do.

When using static libraries, you must have all the libraries available to your XCode project. A shared library could fix this, however XCode only recently started supporting shared libraries so we have not tested this approach.

**Comment by phucpd** [comment]
Can you show me step by step to build this?

**Comment by ras0219-msft** [comment]
Sorry, this is not a supported scenario for us. If you are able to succeed, please consider posting back with the results.
