### ISSUE TITLE
[question] Redhat 7.2 and HTTP 1.1 standard

### ISSUE THREAD

**Issue by oridox** [Microsoft/cpprestsdk#194]
Hi,
I am considering using this package for a cross-platform project (Windows + RH Linux).
1. Can it work on RedHat Linux 7.2? I saw documentation refers to Ubuntu.
2. Does it fully support the HTTP 1.1 standard RFC 2616 ? What about HTTPS?
3. What is the roadmap of this library. I saw current version is 2.8 and I understand there is version 3 on the way. What is the content of it?

Thanks,
Ori.

**Comment by ras0219-msft** [comment]
1. We only test on Ubuntu, however we have heard successes on RedHat from other users. If you encounter issues, we'd be happy to accept any fixes.

2. We do not support every feature listed in RFC2616, however the ones we do support are HTTP 1.1 compliant. We do support HTTPS.

3. So far, we will likely be including several performance improvements and some breaking changes in version 3. There are no major new APIs planned for 3.0 at this time, however we are always willing to consider PRs.
