### ISSUE TITLE
Running automatic tests after build

### ISSUE THREAD

**Issue by oridox** [Microsoft/cpprestsdk#196]
Hi,
I just built cpprestsdk for RH 7.2.
I wonder if there is a set of automatic tests I can run to validate my build.
If so, how do I run it?
Thanks,
Ori.

**Comment by ras0219-msft** [comment]
Hi oridox, please take a look at https://github.com/Microsoft/cpprestsdk/wiki/How-to-build-for-Linux:

After building you can run the tests by executing the ./run_tests.sh script inside the "Binaries" folder: 
```
cd Binaries
./test_runner *_test.so
```
