### ISSUE TITLE
FileNotFound Exception thrown as soon as I start my program

### ISSUE THREAD

**Issue by HeroesHannibal** [Microsoft/cpprestsdk#201]
Immediately after starting my program, I get an exception and an HRESULT:0x8007007E along with the message "The specified module cannot be found". It doesn't say which specific module but the issue only comes up when link and use things from the cpprest140d_2_8 dll . The weird thing is I have set the linker settings so that cpprest140d_2_8.lib is linked from \packages\cpprestsdk.v140.windesktop.msvcstl.dyn.rt-dyn.2.8.0\lib\native\v140\windesktop\msvcstl\dyn\rt-dyn\x64\Debug.  I am using Visual Studio 2015 and I am running on Debug and x64 mode. My program is also a Universal Windows Application. Can I use this library with these settings? Ive also googled the HRESULT code that I get and some entries suggest I am missing dependencies but the entry on NuGet says that cpprest140d_2_8 has no dependencies? 

Furthermore, when I installed the cpprestsdk packet from NuGet, it didn't add the package to my include and lib directories. I had to set these up manually. Is this normal? I though NuGet should have set this up.

**Comment by ras0219-msft** [comment]
Hi Heroes,

You did everything perfectly for a Windows Desktop application :). Since you're targeting UWP, you'll need to use our "winapp" package instead of "windesktop".

The NuGet package definitely should set up the include and lib directories; if it doesn't, please report it as a bug.

**Comment by HeroesHannibal** [comment]
Ahh, thank you! That worked!
