### ISSUE TITLE
XML parsing

### ISSUE THREAD

**Issue by Johnathon332** [Microsoft/cpprestsdk#203]
I am pretty sure the url I have passed the library only returns in XML format, I am not sure how I should go about extracting the contents of the request via xml.  I have tried what was in this tutorial https://msdn.microsoft.com/en-us/library/jj950082.aspx however I get an error saying Incorrect Content-Type: must be textual to extract_string, JSON to extract_json.  I had a look at the response back from the URL and indeed its content-type is XML.  I was wondering how I should go about extracting this information?

**Comment by kavyako** [comment]
hey Johnathon

http_response::extract_string works just fine to read XML strings from the response.
You can also try the extract_string(true) overload to ignore the content type.

This sample code could successfully fetch the xml string from the response:
	
` http_client client(U("https://httpbin.org/xml"));

	return client.request(methods::GET).then([=](http_response response)
	{
		return response.extract_string();
	}).then([](utility::string_t str)
	{
		std::wcout << str;
	});
`
