### ISSUE TITLE
Build cpprestsdk on Android tablet

### ISSUE THREAD

**Issue by pkfox** [Microsoft/cpprestsdk#205]
Hi all, I have a C++ compiler ( c4Droid ) on my Android tablet and would like to be able to code on the go using cpprestsdk ( I'm learning it at the moment ) , however the app I use for my C++ sandboxing (c4Droid ) doesn't support cmake , is it possible to build or use a static library using this app ?

**Comment by ras0219-msft** [comment]
I cannot comment on the c4Droid app, however you could try adding all the cpprestsdk source files to your project. You may need some extra defines or warning suppressions; read through our cmake script to get an understand of what you need.
