### ISSUE TITLE
Network Timeout

### ISSUE THREAD

**Issue by bessermt** [Microsoft/cpprestsdk#207]
I'm looking for the best practice for dealing with timeouts. As I see so far, I get an exception that I can't catch inside my code. However, the caller can wrap a try/catch block around their code and deal with that case. I'd prefer to catch it for the caller, but I'm flexible on this point. 

Here's a function that simply does an HTTP GET, but I can't seem to catch the timeout inside. I tried to make a default task stub that always returns false so if anything fails for any reason, I get a task that tells me it didn't succeed. The .then member is never called when the network is disconnected but the myClient_.request member is called, so I suspect the exception is thrown inside the Casablanca library since my try/catch's never catch a timeout. 

Feel free to suggest any changes since this is mostly guesswork based on sketchy information. 

Thanks.

```
pplx::task<bool> MyCtrl::ping()
{
	auto result = pplx::task<bool>([]() 
	{
		return false;
	});

	try
	{
		auto pingRequest = std::make_shared<web::http::http_request>(web::http::methods::GET);
		auto pingTask = myClient_.request(*pingRequest)
		.then
		(
			[pingRequest]
			(const web::http::http_response pingResponse)
			{
				auto success = false;
				try
				{
					const auto statusCode = pingResponse.status_code();
					if (statusCode == web::http::status_codes::OK)
					{
						success = true;
					}
				}
				catch (const std::exception &e)
				{
					const auto what = e.what();
					LOG(Log::Severity::warning, Log::Category::network | Log::Category::communication, what);
				}
				return success;
			}
		);
		result = pingTask;
	}
	catch (const std::exception &e)
	{
		const auto what = e.what();
		LOG(Log::Severity::warning, Log::Category::network | Log::Category::communication, what);
	}

	return result;
}

```

**Comment by ras0219-msft** [comment]
Try changing your continuation off of `.request()` to accept a `task<http_response>` and use `.get()` inside your continuation to retrieve the `http_response`. If there was an error during `.request()`, the call to `.get()` will throw and you can handle it with a surrounding try/catch.

As a side note, `http_request` already has `shared_ptr` semantics so you don't need to wrap it in another `shared_ptr`.

**Comment by bessermt** [comment]
I'm concerned the call to get() will block the caller from executing until the result is available. I'm assuming your suggestion doesn't do that. I assume the caller keeps running until the get() in the caller (not the one you suggested I add in the callee) is executed. 

Aside from that, it seems to work. Thanks.

**Comment by mobileben** [comment]
A quick addition on this. Yes, the get() will indeed block. This sort of takes away the usefulness of the tasks if the solution is to split things apart. A potentially more useful approach would be for the library to report the error rather than just throw the exception which won't be caught if one uses .then()
