### ISSUE TITLE
Unknown SSL protocol on Linux

### ISSUE THREAD

**Issue by lbromo** [Microsoft/cpprestsdk#211]
Hi,

I'm building a rest API with Casablanca, and I need SSL support the the clients.

I have a service up and running without SSL, but I'm struggling a bit to get it running with SSL.

I've tried setting up my ```http_listner``` with a ```http_listener_config``` that defines a SSL callback funciton, much like it is done in [this test](https://github.com/Microsoft/cpprestsdk/blob/3070ca21ed665a5aeb7d0cfe28f7f21d6c062a92/Release/tests/functional/http/listener/listener_construction_tests.cpp#L435).

When i test it with curl, I can see that it begin to perform a SSL handshake, but ten it fails.

```
➜  ~ curl -v https://localhost:8000/test
*   Trying ::1...
* Connected to localhost (::1) port 8000 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to localhost:8000 
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to localhost:8000 
```

I've found a (rather) old post on SO stating that server side [SSL only works on Windows](http://stackoverflow.com/a/31503632/2041172). Is this still the case?

**Comment by dave456** [comment]
So while that's a perfectly fine test, I think its horrible as sample code. The scoping issues you can run into using that as an example without understand how that lamda function is being used as a callback is icky. I wonder if someone should just slide the bufs inside the lamda block too. Anyway...

If you rewrite the callback as a static entry point in a class (which is how it should be written IMHO), it would look more like this: (forgive the almost zero error checking)

//
// Static entry point for ssl callback
//
void Server::ssl_context_callback(boost::asio::ssl::context& ctx)
{
    std::ifstream certFile("server.pem");
    std::ifstream keyFile("private.key");
    std::vector<char> buf;

    // read the cert file
    if (!certFile.eof() && !certFile.fail()) {
	certFile.seekg(0, std::ios_base::end);
	std::streampos fileSize = certFile.tellg();
	buf.resize(fileSize);
	certFile.seekg(0, std::ios_base::beg);
	certFile.read(&buf[0], fileSize);
    }
    boost::asio::const_buffer cert(&buf[0], buf.size());

    // read the key file
    if (!keyFile.eof() && !keyFile.fail()) {
	keyFile.seekg(0, std::ios_base::end);
	std::streampos fileSize = keyFile.tellg();
	buf.resize(fileSize);
	keyFile.seekg(0, std::ios_base::beg);
	keyFile.read(&buf[0], fileSize);
    }
    boost::asio::const_buffer key(&buf[0], buf.size());

    ctx.set_options(boost::asio::ssl::context::default_workarounds);
    ctx.use_certificate_chain(cert);
    ctx.use_private_key(key, boost::asio::ssl::context::pem);
}

I've used something very much like this (this is slightly tweaked from a cut and paste so it may not actually compile...), and this works perfectly fine on Linux.

**Comment by lbromo** [comment]
Thanks a lot! That helped :+1:
