### ISSUE TITLE
Does the C++ REST SDK must need c++ 11 support?

### ISSUE THREAD

**Issue by BorisJineman** [Microsoft/cpprestsdk#223]
Hi team, 

Does the C++ REST SDK must need c++ 11/14 support?

I have a project, it cannot apply '-std=c++11' now for some reason, so could I use this library?
If I cannot , is there any other candidate libraries which can replace this?

Peace and Long Life,
Boris

**Comment by ras0219-msft** [comment]
Yes, we require c++11 support. I recommend trying to upgrade your project to c++11 or newer; significant improvements to the language have been made regarding safety and performance.
