### ISSUE TITLE
Conflict with gtest headers during tests

### ISSUE THREAD

**Issue by levavakian** [Microsoft/cpprestsdk#230]
When I try to use C++ Resk SDK headers along gtest headers, I get a slew of errors in gtest that are something along the lines of this:

```
/usr/include/gtest/internal/gtest-internal.h:961:54: error: declaration of ‘rhs’ as array of references
inline bool ArrayEq(const T(&lhs)[N], const U(&rhs)[N]) {
                                                     ^
/usr/include/gtest/internal/gtest-internal.h: In function ‘bool testing::internal::ArrayEq(...)’:
/usr/include/gtest/internal/gtest-internal.h:962:28: error: ‘lhs’ was not declared in this scope
  return internal::ArrayEq(lhs, N, rhs);
                           ^
/usr/include/gtest/internal/gtest-internal.h:962:36: error: ‘rhs’ was not declared in this scope
  return internal::ArrayEq(lhs, N, rhs);
                                   ^
/usr/include/gtest/internal/gtest-internal.h: At global scope:
/usr/include/gtest/internal/gtest-internal.h:1001:40: error: variable or field ‘CopyArray’ declared void
inline void CopyArray(const T(&from)[N], U(*to)[N]) {
                                       ^
/usr/include/gtest/internal/gtest-internal.h:1001:23: error: expected primary-expression before ‘const’
inline void CopyArray(const T(&from)[N], U(*to)[N]) {
                      ^
```

which only hit if the C++ Rest SDK headers are included before the gtest headers. If I put the gtest headers at the top, then all is fine. Has anyone else encountered this?

I thought the source might be a sneaky #define somewhere, but I haven't been able to find the source yet.

**Comment by ras0219-msft** [comment]
Yes, this is caused by us defining a macro U(X). This can be suppressed by defining `_TURN_OFF_PLATFORM_STRING` before including a C++REST SDK header.

https://github.com/Microsoft/cpprestsdk/blob/master/Release/include/cpprest/details/basic_types.h#L95

**Comment by levavakian** [comment]
Cheers!

**Comment by burannah** [comment]
Any plans to fix this? So we can have both - platform strings and google tests?
