### ISSUE TITLE
TestRunner.exe never created and BingRequest program always throws exception

### ISSUE THREAD

**Issue by spencerparkin** [Microsoft/cpprestsdk#25]
An exception is always thrown in the wait entered in the BingRequest demo.  I gave it a search string and a file name that I believe were valid, so I'm ruling out "garbage in, garbage out" as a problem.

Build always fails, but building again succeeds, probably because DevStudio does not get the dependencies right.

Using VS2013, v120 build tools, x64, Windows 10.

**Comment by kavyako** [comment]
Could you copy paste the build error here so we can investigate it?

**Comment by Danimoth** [comment]
I tried:
- cpprestsdk 2.7.0 with VS2015, x64, Windows 10
- cpprestsdk 2.7.0 with VS2013, x64, Windows 10

and it works as expected. As kavyako mentioned above, could you provide some more info around your error messages so we can look into it?

**Comment by spencerparkin** [comment]
If it's working for you, then never mind...could've been something weirdo on my machine.  I don't have everything setup anymore to test it again...switched to cURL to get my project done.

There was no build error.  Every time I ran the BingRequest demo, it threw an exception deep in the wait code.

Sorry...shouldn't have said anything...or at least given a callstack.

**Comment by Danimoth** [comment]
I see. In that case I will close this bug report.
Should the issue occur again in the future, please feel free to reopen this bug or report a new one.
Thanks!
