### ISSUE TITLE
Unhandled exception on wating http_response

### ISSUE THREAD

**Issue by iness97** [microsoft/cpprestsdk#255]
Hello. I have an issue .
First , I am sorry for my english skill because I 'm not a native english speaker. 

I' ve met this exception if I was waiting http_response after sending a  'GET' request message. 

Unhandled exception at 0x000007FEFD09965D in ZZZ_TestRest.exe: Microsoft C++ exception: web::http::http_exception at memory location 0x000000000028F090.

My debugger indicates the source line 1779 in ppltasks.h code 

```
        if (_HasUserException())
        {
            _M_exceptionHolder->_RethrowUserException();     <-- exception occurred
        }
```

Here is my source code that I've tested. 

If I fill any string for body parameter on request function , the exception is occurred.
But if body parameter is empty , the exception is not occurred.

client.request(methods::GET, L"", L"", L"application/json") <-- no problem. 
client.request(methods::GET, L"",L"anyvalue", L"application/json") <-- problem

Environment 
OS : windows 7
Plattform : X64

Please advice me for this issue. 
Thank you.
# ------------------ source code ----------------------

```
#include "stdafx.h"
#include <iostream>

using namespace std;
#include <cpprest/http_client.h>
#include <cpprest/filestream.h>

#ifdef _DEBUG
    #pragma comment(lib, "cpprest120d_2_8") 
#else
    #pragma comment(lib, "cpprest120_2_8")  
#endif

using namespace utility;                    // Common utilities like string conversions
using namespace web;                        // Common features like URIs.
using namespace web::http;                  // Common HTTP functionality
using namespace web::http::client;          // HTTP client features
using namespace concurrency::streams;       // Asynchronous streams

void GetJson()
{
    http_client client(U("http://197.243.34.203/api/common/moto_vehicles/getByPlatesNumber"));
    json::value postData;
    postData[U("plate_no")] = json::value::string(U("RD900E"));

    client.request(methods::GET, L"", postData.serialize().c_str(), L"application/json").then([=](http_response r)
    {
        wcout << U("STATUS : ") << r.status_code() << endl;
        wcout << "content-type : " << r.headers().content_type() << endl;
        r.extract_string(true).then([](string_t sBoby)
        {
            wcout << sBoby << endl;
        }).wait();

        //r.extract_json(true).then([](json::value v) {
        //  wcout << v.at(U("date")).as_string() << endl;
        //  wcout << v.at(U("date")).as_string() << endl;
        //  wcout << v.at(U("time")).as_string() << endl;
        //}).wait();
    }).wait();
}

int main(int argc, char* argv[])
{

    wcout.imbue(locale("kor"));  // windows only
    GetJson();
    wcout << L"done" << endl;
    return 0;
}

```

**Comment by guangpingzhou** [comment]
@iness97 hello, I have this issue  too, if you fixed it?

**Comment by iness97** [comment]
I'm not sure, it is because I posted the issue long time ago.
I could'n t find the way how to do request using GET method. 
So I used POST method instead of GET method. 

Here is the sample source code; 

CString strVehiclePath, strAuthPath;
 strAuthPath.Format(L"%s/api/login", szDBIP);
 
   json::value postData;
   json::value authData;

   http_client client((LPCWSTR)strAuthPath);  
    
   try
   {
    authData[U("id] = json::value::string(szDBID);
    authData[U("pw] = json::value::string(szDBPW);



    client.request(methods::POST, L"", authData.serialize().c_str(), L"application/json").then([=](http_response r)
    {
     if (r.status_code() == 200)
     {
      r.extract_json(true).then([=](json::value v)
      {
       token_s = v.at(U("uuid")).as_string();
      }).wait();
     }
     else
     {
      CString strLog;
      strLog.Format(L"<-------  auth Failure (response code = %d %s)",   r.status_code(), r.reason_phrase().c_str());
     }
    }).wait();
   }
   catch (const std::exception& ex)
   {
    CString strLog;
    strLog.Format(L"[%s] %s - Authentication request error", m_CommInfo.cIpAddr, utility::conversions::to_string_t(ex.what()).c_str());
   }
