### ISSUE TITLE
UTF-8 encoded JSON files causing JSON parser to throw exceptions

### ISSUE THREAD

**Issue by damienhocking** [Microsoft/cpprestsdk#258]
This has me really scratching my head.  We're POSTing JSON files to our cpprest-based server and we've started seeing exceptions.  It's all coreect JSON with no fancy characters.  When these files are encoded as ANSI, the parser is fine.  When they're encoded as UTF-8, they cause exceptions, always in the same place, Line 1, Column 2.  JSON is supposed to be UTF-8.  Anyone got any suggestions?  

I should point out that we compile our own cpprest, we're not using the Nuget version.

Damien

**Comment by damienhocking** [comment]
Anyone?  Bueller?  Anyone?

**Comment by grahamreeds** [comment]
Can you create a minimum verifiable executable?

Also can you post the JSON that is causing the exception?

GR

**Comment by damienhocking** [comment]
Yeah I think so.

Damien

**Comment by hacst** [comment]
Being that early in a file a UTF-8 BOM going somewhere it isn't expected is a likely candidate to watch out for.

**Comment by damienhocking** [comment]
The thing that has me scratching my head is that if I load the file into 
Notepad, and save it out as ANSI, it's fine.  If I save as UTF8, that's 
when it crashes.

**Comment by MicBe** [comment]
Same problem here.
I had to manually remove the bom(if any) before parsing..

**Comment by damienhocking** [comment]
How did you do that?  Do you have an example you can share?

**Comment by MicBe** [comment]
I opened the json data in an hex editor to view the exact value that was causing the problem. In my case, it was 0xfeff which is an UTF-16 BOM according to the table here: https://en.wikipedia.org/wiki/Byte_order_mark.
The function I use:
`json::value sanitizeJson(const wstring& json)
{
	wstring dataWithoutBom(json);
	if (!json.empty())
	{
		if (json.size() > 1 && json[0] == 0xfeff)
			dataWithoutBom = wstring(json.begin() + 1, json.end());
	}
	return json::value::parse(dataWithoutBom);
}`
json being the result of extract_string().get() on http_response.

**Comment by damienhocking** [comment]
Thank you, I’m going to try this.

**Comment by damienhocking** [comment]
Sorry, I meant to respond to this earlier.  MicBe's code fix works for our situation.  I don't know why we're sending UTF-16 but it's not a cpprestsdk bug, it's throwing correctly.  I'll close this.
