### ISSUE TITLE
Link Error Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by john3-16** [Microsoft/cpprestsdk#264]
[CMakeLists.txt](https://github.com/Microsoft/cpprestsdk/files/528295/CMakeLists.txt)
[webclient.txt](https://github.com/Microsoft/cpprestsdk/files/528299/webclient.txt)
Above are the make file and code rename from .cpp to .txt

I used brew to install cpprestsdk which include Boost and openssl.

I followed your [getting start tutorial](https://github.com/Microsoft/cpprestsdk/wiki/Getting-Started-Tutorial) for simple step to use this sdk.  No matter what I do get the link error above.  I am using Xcode 8 as the compiler and linker.

Running OS X El Capitan 10.11.6 on MacBook Pro 16GB memory Intel Core I7 
I have ran brew doctor as well but don't see any issues that would cause this issue.

Using Visual Studio Code with the CMAKE extension to perform the builds. Below is the linker step:

`[100%] Linking CXX executable anyExecutable
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.11.0 -o anyExecutable -L/usr/local/opt/openssl/lib -L/usr/local/opt/libiconv/lib -search_paths_first -headerpad_max_install_names CMakeFiles/anyExecutable.dir/webclient.cpp.o /usr/local/lib/libboost_program_options-mt.dylib -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/lib/darwin/libclang_rt.osx.a`

Then the error shows up

`Undefined symbols for architecture x86_64:
  "_CONF_modules_unload", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::~do_init() in webclient.cpp.o
  "_CRYPTO_cleanup_all_ex_data", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::~do_init() in webclient.cpp.o
  "_CRYPTO_num_locks", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::do_init() in webclient.cpp.o
  "_CRYPTO_set_locking_callback", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::do_init() in webclient.cpp.o
      boost::asio::ssl::detail::openssl_init_base::do_init::~do_init() in webclient.cpp.o
  "_ENGINE_cleanup", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::~do_init() in webclient.cpp.o
  "_ERR_free_strings", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::~do_init() in webclient.cpp.o
  "_ERR_reason_error_string", referenced from:
      boost::asio::error::detail::ssl_category::message(int) const in webclient.cpp.o
  "_ERR_remove_thread_state", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::~do_init() in webclient.cpp.o
  "_EVP_cleanup", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::~do_init() in webclient.cpp.o
  "_OPENSSL_add_all_algorithms_noconf", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::do_init() in webclient.cpp.o
  "_SSL_COMP_free_compression_methods", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::~do_init() in webclient.cpp.o
  "_SSL_library_init", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::do_init() in webclient.cpp.o
  "_SSL_load_error_strings", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::do_init() in webclient.cpp.o
  "web::uri_builder::append_path(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)", referenced from:
      std::__1::__function::__func<main::$_0, std::__1::allocator<main::$_0>, pplx::task<web::http::http_response> (Concurrency::streams::basic_ostream<unsigned char>)>::operator()(Concurrency::streams::basic_ostream<unsigned char>&&) in webclient.cpp.o
  "web::uri_builder::append_query(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)", referenced from:
      web::uri_builder& web::uri_builder::append_query<char [37]>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const (&) [37], bool) in webclient.cpp.o
  "web::uri_builder::to_string()", referenced from:
      std::__1::__function::__func<main::$_0, std::__1::allocator<main::$_0>, pplx::task<web::http::http_response> (Concurrency::streams::basic_ostream<unsigned char>)>::operator()(Concurrency::streams::basic_ostream<unsigned char>&&) in webclient.cpp.o
  "web::uri::encode_impl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<bool (int)> const&)", referenced from:
      web::uri_builder& web::uri_builder::append_query<char [37]>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const (&) [37], bool) in webclient.cpp.o
  "web::uri::uri(char const*)", referenced from:
      std::__1::__function::__func<main::$_0, std::__1::allocator<main::$_0>, pplx::task<web::http::http_response> (Concurrency::streams::basic_ostream<unsigned char>)>::operator()(Concurrency::streams::basic_ostream<unsigned char>&&) in webclient.cpp.o
  "web::uri::uri(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      web::http::client::http_client::request(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, pplx::cancellation_token const&) in webclient.cpp.o
  "web::http::client::http_client::request(web::http::http_request, pplx::cancellation_token const&)", referenced from:
      web::http::client::http_client::request(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, pplx::cancellation_token const&) in webclient.cpp.o
  "web::http::client::http_client::http_client(web::uri const&)", referenced from:
      std::__1::__function::__func<main::$_0, std::__1::allocator<main::$_0>, pplx::task<web::http::http_response> (Concurrency::streams::basic_ostream<unsigned char>)>::operator()(Concurrency::streams::basic_ostream<unsigned char>&&) in webclient.cpp.o
  "web::http::details::_http_request::set_request_uri(web::uri const&)", referenced from:
      web::http::client::http_client::request(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, pplx::cancellation_token const&) in webclient.cpp.o
  "web::http::details::_http_request::_http_request(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      std::__1::shared_ptr<web::http::details::_http_request> std::__1::shared_ptr<web::http::details::_http_request>::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) in webclient.cpp.o
  "web::http::details::http_msg_base::http_msg_base()", referenced from:
      pplx::details::_Task_impl<web::http::http_response>::_Task_impl(pplx::details::_CancellationTokenState*, pplx::scheduler_ptr) in webclient.cpp.o
  "web::http::methods::GET", referenced from:
      std::__1::__function::__func<main::$_0, std::__1::allocator<main::$_0>, pplx::task<web::http::http_response> (Concurrency::streams::basic_ostream<unsigned char>)>::operator()(Concurrency::streams::basic_ostream<unsigned char>&&) in webclient.cpp.o
  "pplx::get_ambient_scheduler()", referenced from:
      pplx::details::_ContinuationTypeTraits<main::$_0, Concurrency::streams::basic_ostream<unsigned char> >::_TaskOfType pplx::task<Concurrency::streams::basic_ostream<unsigned char> >::then<main::$_0>(main::$_0 const&) const in webclient.cpp.o
      pplx::details::_ContinuationTypeTraits<main::$_1, web::http::http_response>::_TaskOfType pplx::task<web::http::http_response>::then<main::$_1>(main::$_1 const&) const in webclient.cpp.o
      pplx::details::_ContinuationTypeTraits<main::$_2, unsigned long>::_TaskOfType pplx::task<unsigned long>::then<main::$_2>(main::$_2 const&) const in webclient.cpp.o
      pplx::details::_ContinuationTypeTraits<Concurrency::streams::file_stream<unsigned char>::open_ostream(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, int)::'lambda'(Concurrency::streams::streambuf<unsigned char>), Concurrency::streams::streambuf<unsigned char> >::_TaskOfType pplx::task<Concurrency::streams::streambuf<unsigned char> >::then<Concurrency::streams::file_stream<unsigned char>::open_ostream(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, int)::'lambda'(Concurrency::streams::streambuf<unsigned char>)>(Concurrency::streams::file_stream<unsigned char>::open_ostream(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, int)::'lambda'(Concurrency::streams::streambuf<unsigned char>) const&) const in webclient.cpp.o
      Concurrency::streams::details::basic_file_buffer<unsigned char>::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, int) in webclient.cpp.o
      pplx::details::_ContinuationTypeTraits<Concurrency::streams::file_buffer<unsigned char>::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, int)::'lambda'(pplx::task<std::__1::shared_ptr<Concurrency::streams::details::basic_streambuf<unsigned char> > >), std::__1::shared_ptr<Concurrency::streams::details::basic_streambuf<unsigned char> > >::_TaskOfType pplx::task<std::__1::shared_ptr<Concurrency::streams::details::basic_streambuf<unsigned char> > >::then<Concurrency::streams::file_buffer<unsigned char>::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, int)::'lambda'(pplx::task<std::__1::shared_ptr<Concurrency::streams::details::basic_streambuf<unsigned char> > >)>(Concurrency::streams::file_buffer<unsigned char>::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, int)::'lambda'(pplx::task<std::__1::shared_ptr<Concurrency::streams::details::basic_streambuf<unsigned char> > >) const&) const in webclient.cpp.o
      Concurrency::streams::details::streambuf_state_manager<unsigned char>::close(unsigned int) in webclient.cpp.o
      ...
  "pplx::details::platform::GetCurrentThreadId()", referenced from:
      pplx::details::_CancellationTokenState::_DeregisterCallback(pplx::details::_CancellationTokenRegistration*) in webclient.cpp.o
      pplx::details::_CancellationTokenRegistration::_Invoke() in webclient.cpp.o
      pplx::scoped_lock<pplx::details::recursive_lock_impl>::scoped_lock(pplx::details::recursive_lock_impl&) in webclient.cpp.o
      pplx::details::recursive_lock_impl::unlock() in webclient.cpp.o
  "boost::this_thread::interruption_point()", referenced from:
      boost::condition_variable::wait(boost::unique_lock<boost::mutex>&) in webclient.cpp.o
      boost::condition_variable::do_wait_until(boost::unique_lock<boost::mutex>&, timespec const&) in webclient.cpp.o
  "boost::chrono::steady_clock::now()", referenced from:
      pplx::details::event_impl::wait(unsigned int) in webclient.cpp.o
  "boost::chrono::system_clock::now()", referenced from:
      pplx::details::event_impl::wait(unsigned int) in webclient.cpp.o
  "boost::detail::get_current_thread_data()", referenced from:
      boost::detail::interruption_checker::interruption_checker(_opaque_pthread_mutex_t*, _opaque_pthread_cond_t*) in webclient.cpp.o
  "boost::system::system_category()", referenced from:
      boost::unique_lock<boost::mutex>::lock() in webclient.cpp.o
      boost::condition_variable::wait(boost::unique_lock<boost::mutex>&) in webclient.cpp.o
      boost::detail::interruption_checker::interruption_checker(_opaque_pthread_mutex_t*, _opaque_pthread_cond_t*) in webclient.cpp.o
      boost::unique_lock<boost::mutex>::unlock() in webclient.cpp.o
      boost::detail::interruption_checker::~interruption_checker() in webclient.cpp.o
      boost::condition_variable::do_wait_until(boost::unique_lock<boost::mutex>&, timespec const&) in webclient.cpp.o
      boost::asio::ssl::detail::openssl_init_base::do_init::do_init() in webclient.cpp.o
      ...
  "boost::system::generic_category()", referenced from:
      __GLOBAL__sub_I_webclient.cpp in webclient.cpp.o
  "vtable for web::http::details::_http_request", referenced from:
      web::http::details::_http_request::~_http_request() in webclient.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for web::http::details::http_msg_base", referenced from:
      std::__1::__shared_ptr_emplace<web::http::details::_http_response, std::__1::allocator<web::http::details::_http_response> >::~__shared_ptr_emplace() in webclient.cpp.o
      std::__1::__shared_ptr_emplace<web::http::details::_http_response, std::__1::allocator<web::http::details::_http_response> >::~__shared_ptr_emplace() in webclient.cpp.o
      web::http::details::_http_request::~_http_request() in webclient.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for web::http::details::_http_response", referenced from:
      pplx::details::_Task_impl<web::http::http_response>::_Task_impl(pplx::details::_CancellationTokenState*, pplx::scheduler_ptr) in webclient.cpp.o
      std::__1::__shared_ptr_emplace<web::http::details::_http_response, std::__1::allocator<web::http::details::_http_response> >::~__shared_ptr_emplace() in webclient.cpp.o
      std::__1::__shared_ptr_emplace<web::http::details::_http_response, std::__1::allocator<web::http::details::_http_response> >::~__shared_ptr_emplace() in webclient.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "__close_fsb_nolock", referenced from:
      Concurrency::streams::details::basic_file_buffer<unsigned char>::_close_file(Concurrency::streams::details::_file_info*) in webclient.cpp.o
  "__get_size", referenced from:
      Concurrency::streams::details::basic_file_buffer<unsigned char>::size() const in webclient.cpp.o
  "__getn_fsb", referenced from:
      Concurrency::streams::details::basic_file_buffer<unsigned char>::_bumpc()::'lambda'()::operator()() const in webclient.cpp.o
      Concurrency::streams::details::basic_file_buffer<unsigned char>::_getcImpl() in webclient.cpp.o
      Concurrency::streams::details::basic_file_buffer<unsigned char>::_getn(unsigned char*, unsigned long)::'lambda'()::operator()() const in webclient.cpp.o
  "__open_fsb_str", referenced from:
      Concurrency::streams::details::basic_file_buffer<unsigned char>::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, int) in webclient.cpp.o
  "__putn_fsb", referenced from:
      Concurrency::streams::details::basic_file_buffer<unsigned char>::_putc(unsigned char) in webclient.cpp.o
      Concurrency::streams::details::basic_file_buffer<unsigned char>::_putn(unsigned char const*, unsigned long) in webclient.cpp.o
  "__seekrdpos_fsb", referenced from:
      Concurrency::streams::details::basic_file_buffer<unsigned char>::seekpos(std::__1::fpos<__mbstate_t>, unsigned int) in webclient.cpp.o
      Concurrency::streams::details::basic_file_buffer<unsigned char>::seekoff(long long, std::__1::ios_base::seekdir, unsigned int) in webclient.cpp.o
      Concurrency::streams::details::basic_file_buffer<unsigned char>::_nextc()::'lambda'()::operator()() const in webclient.cpp.o
      Concurrency::streams::details::basic_file_buffer<unsigned char>::_ungetc()::'lambda'()::operator()() const in webclient.cpp.o
  "__seekrdtoend_fsb", referenced from:
      Concurrency::streams::details::basic_file_buffer<unsigned char>::seekoff(long long, std::__1::ios_base::seekdir, unsigned int) in webclient.cpp.o
  "__seekwrpos_fsb", referenced from:
      Concurrency::streams::details::basic_file_buffer<unsigned char>::seekpos(std::__1::fpos<__mbstate_t>, unsigned int) in webclient.cpp.o
      Concurrency::streams::details::basic_file_buffer<unsigned char>::seekoff(long long, std::__1::ios_base::seekdir, unsigned int) in webclient.cpp.o
  "__sync_fsb", referenced from:
      Concurrency::streams::details::basic_file_buffer<unsigned char>::flush_internal() in webclient.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [anyExecutable] Error 1
make[1]: *** [CMakeFiles/anyExecutable.dir/all] Error 2
make: *** [all] Error 2
[vscode] CMake exited with status 2
`
Appreciate any help this.  spent many hours yesterday an trying different things.

**Comment by john3-16** [comment]
Finally solved: Figured out how to referenced the missing symbol names to the library that was needed. The final list compete is what follows:

CPPFLAGS -stdlib=libc++ LDFLAGS -lcpprest -lssl -lcrypto -lboost_system -lboost_thread-mt -lboost_chrono-mt

**Comment by 0x8BADFOOD** [comment]
Met same problem. Working options for me:

`g++ test.cpp -std=c++11 -lcpprest -lssl -lcrypto -lboost_system -lboost_thread-mt -lboost_chrono-mt -L/usr/local/Cellar/openssl/1.0.2g/lib`
