### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Victordmdb** [Microsoft/cpprestsdk#266]
Building on Ubuntu 16.04. After following the instructions here
https://github.com/Microsoft/cpprestsdk/wiki/How-to-build-for-Linux

I get the following build error with cmake option -DCMAKE_BUILD_TYPE=Debug ( a similar error happens with the Release build as well)

```
Scanning dependencies of target websocketclient_test
[ 86%] Building CXX object tests/functional/websockets/client/CMakeFiles/websocketclient_test.dir/authentication_tests.cpp.o
[ 86%] Building CXX object tests/functional/websockets/client/CMakeFiles/websocketclient_test.dir/client_construction.cpp.o
[ 87%] Building CXX object tests/functional/websockets/client/CMakeFiles/websocketclient_test.dir/close_tests.cpp.o
[ 87%] Building CXX object tests/functional/websockets/client/CMakeFiles/websocketclient_test.dir/error_tests.cpp.o
[ 88%] Building CXX object tests/functional/websockets/client/CMakeFiles/websocketclient_test.dir/receive_msg_tests.cpp.o
[ 89%] Building CXX object tests/functional/websockets/client/CMakeFiles/websocketclient_test.dir/send_msg_tests.cpp.o
[ 89%] Linking CXX shared library ../../../../Binaries/libwebsocketclient_test.so
[ 89%] Built target websocketclient_test
Scanning dependencies of target SearchFile
[ 89%] Building CXX object samples/SearchFile/CMakeFiles/SearchFile.dir/searchfile.cpp.o
[ 90%] Linking CXX executable ../../Binaries/SearchFile
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `main':
/data/casablanca/Release/samples/SearchFile/searchfile.cpp:193: undefined reference to `utility::conversions::to_utf8string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `pplx::details::recursive_lock_impl::lock()':
/data/casablanca/Release/include/pplx/pplxlinux.h:213: undefined reference to `pplx::details::platform::GetCurrentThreadId()'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `pplx::details::recursive_lock_impl::unlock()':
/data/casablanca/Release/include/pplx/pplxlinux.h:229: undefined reference to `pplx::details::platform::GetCurrentThreadId()'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `pplx::details::_CancellationTokenRegistration::_Invoke()':
/data/casablanca/Release/include/pplx/pplxcancellation_token.h:232: undefined reference to `pplx::details::platform::GetCurrentThreadId()'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `pplx::details::_CancellationTokenState::_DeregisterCallback(pplx::details::_CancellationTokenRegistration*)':
/data/casablanca/Release/include/pplx/pplxcancellation_token.h:564: undefined reference to `pplx::details::platform::GetCurrentThreadId()'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `pplx::details::_TaskCollectionImpl::_RunTask(void (*)(void*), void*, pplx::details::_TaskInliningMode)':
/data/casablanca/Release/include/pplx/pplx.h:205: undefined reference to `pplx::get_ambient_scheduler()'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `pplx::task_options::task_options()':
/data/casablanca/Release/include/pplx/pplxtasks.h:1247: undefined reference to `pplx::get_ambient_scheduler()'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode, int)':
/data/casablanca/Release/include/cpprest/filestream.h:755: undefined reference to `_open_fsb_str'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_close_file(Concurrency::streams::details::_file_info*)':
/data/casablanca/Release/include/cpprest/filestream.h:212: undefined reference to `_close_fsb_nolock'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::flush_internal()':
/data/casablanca/Release/include/cpprest/filestream.h:732: undefined reference to `_sync_fsb'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::size() const':
/data/casablanca/Release/include/cpprest/filestream.h:136: undefined reference to `_get_size'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::seekpos(std::fpos<__mbstate_t>, std::_Ios_Openmode)':
/data/casablanca/Release/include/cpprest/filestream.h:662: undefined reference to `_seekrdpos_fsb'
/data/casablanca/Release/include/cpprest/filestream.h:666: undefined reference to `_seekwrpos_fsb'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::seekoff(long, std::_Ios_Seekdir, std::_Ios_Openmode)':
/data/casablanca/Release/include/cpprest/filestream.h:688: undefined reference to `_seekrdpos_fsb'
/data/casablanca/Release/include/cpprest/filestream.h:690: undefined reference to `_seekrdpos_fsb'
/data/casablanca/Release/include/cpprest/filestream.h:692: undefined reference to `_seekrdtoend_fsb'
/data/casablanca/Release/include/cpprest/filestream.h:703: undefined reference to `_seekwrpos_fsb'
/data/casablanca/Release/include/cpprest/filestream.h:705: undefined reference to `_seekwrpos_fsb'
/data/casablanca/Release/include/cpprest/filestream.h:707: undefined reference to `_seekwrpos_fsb'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_putc(char)':
/data/casablanca/Release/include/cpprest/filestream.h:300: undefined reference to `_putn_fsb'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_putn(char const*, unsigned long)':
/data/casablanca/Release/include/cpprest/filestream.h:373: undefined reference to `_putn_fsb'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_bumpc()::{lambda()#1}::operator()() const':
/data/casablanca/Release/include/cpprest/filestream.h:426: undefined reference to `_getn_fsb'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_nextc()::{lambda()#1}::operator()() const':
/data/casablanca/Release/include/cpprest/filestream.h:533: undefined reference to `_seekrdpos_fsb'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_ungetc()::{lambda()#1}::operator()() const':
/data/casablanca/Release/include/cpprest/filestream.h:549: undefined reference to `_seekrdpos_fsb'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_getn(char*, unsigned long)::{lambda()#1}::operator()() const':
/data/casablanca/Release/include/cpprest/filestream.h:585: undefined reference to `_getn_fsb'
CMakeFiles/SearchFile.dir/searchfile.cpp.o: In function `Concurrency::streams::details::basic_file_buffer<char>::_getcImpl()':
/data/casablanca/Release/include/cpprest/filestream.h:481: undefined reference to `_getn_fsb'
collect2: error: ld returned 1 exit status
samples/SearchFile/CMakeFiles/SearchFile.dir/build.make:94: recipe for target 'Binaries/SearchFile' failed
make[2]: *** [Binaries/SearchFile] Error 1
CMakeFiles/Makefile2:1078: recipe for target 'samples/SearchFile/CMakeFiles/SearchFile.dir/all' failed
make[1]: *** [samples/SearchFile/CMakeFiles/SearchFile.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Victordmdb** [comment]
Ok I tried again today, and it worked!

**Comment by guyavrah1986** [comment]
I have encountered more or less in the same issue also when following the above link (https://github.com/Microsoft/cpprestsdk/wiki/How-to-build-for-Linux). 
The error is as follows:
Scanning dependencies of target cpprest
[  0%] Building CXX object src/CMakeFiles/cpprest.dir/http/client/http_client.cpp.o
In file included from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/pch/stdafx.h:99:0,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:16:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:6702:79: error: ‘operator&&’ function uses ‘auto’ type specifier without trailing return type
 auto operator&&(const task<_ReturnType> & _Lhs, const task<_ReturnType> & _Rhs)
                                                                               ^
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:6702:79: note: deduced return type only available with -std=c++14 or -std=gnu++14
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:6734:92: error: ‘operator&&’ function uses ‘auto’ type specifier without trailing return type
 &&(const task<std::vector<_ReturnType>> & _Lhs, const task<_ReturnType> & _Rhs)
                                                                               ^
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:6734:92: note: deduced return type only available with -std=c++14 or -std=gnu++14
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:6765:92: error: ‘operator&&’ function uses ‘auto’ type specifier without trailing return type
 &&(const task<_ReturnType> & _Lhs, const task<std::vector<_ReturnType>> & _Rhs)
                                                                               ^
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:6765:92: note: deduced return type only available with -std=c++14 or -std=gnu++14
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:6796:105: error: ‘operator&&’ function uses ‘auto’ type specifier without trailing return type
 <std::vector<_ReturnType>> & _Lhs, const task<std::vector<_ReturnType>> & _Rhs)
                                                                               ^
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:6796:105: note: deduced return type only available with -std=c++14 or -std=gnu++14
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:7087:79: error: ‘operator||’ function uses ‘auto’ type specifier without trailing return type
 auto operator||(const task<_ReturnType> & _Lhs, const task<_ReturnType> & _Rhs)
                                                                               ^
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:7087:79: note: deduced return type only available with -std=c++14 or -std=gnu++14
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:7148:92: error: ‘operator||’ function uses ‘auto’ type specifier without trailing return type
 ||(const task<std::vector<_ReturnType>> & _Lhs, const task<_ReturnType> & _Rhs)
                                                                               ^
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:7148:92: note: deduced return type only available with -std=c++14 or -std=gnu++14
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:7222:92: error: ‘operator||’ function uses ‘auto’ type specifier without trailing return type
 ||(const task<_ReturnType> & _Lhs, const task<std::vector<_ReturnType>> & _Rhs)
                                                                               ^
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:7222:92: note: deduced return type only available with -std=c++14 or -std=gnu++14
In file included from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/streams.h:18:0,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/pch/stdafx.h:103,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:16:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/astreambuf.h: In instantiation of ‘pplx::task<void> Concurrency::streams::details::streambuf_state_manager<_CharType>::close(std::ios_base::openmode) [with _CharType = unsigned char; std::ios_base::openmode = std::_Ios_Openmode]’:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:402:3:   required from here
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/astreambuf.h:416:39: error: invalid use of ‘auto’
                     closeOp = closeOp && _close_write().then([this_ptr]{}); // 
                                       ^
In file included from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/pch/stdafx.h:99:0,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:16:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h: In instantiation of ‘struct pplx::details::_ContinuationTypeTraits<Concurrency::streams::details::streambuf_state_manager<_CharType>::close(std::ios_base::openmode) [with _CharType = unsigned char; std::ios_base::openmode = std::_Ios_Openmode]::<lambda()>, void>’:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:4405:10:   required by substitution of ‘template<class _Function> typename pplx::details::_ContinuationTypeTraits<_Function, void>::_TaskOfType pplx::task<void>::then(_Function&&, pplx::task_options) const [with _Function = Concurrency::streams::details::streambuf_state_manager<_CharType>::close(std::ios_base::openmode) [with _CharType = unsigned char; std::ios_base::openmode = std::_Ios_Openmode]::<lambda()>]’
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/astreambuf.h:418:29:   required from ‘pplx::task<void> Concurrency::streams::details::streambuf_state_manager<_CharType>::close(std::ios_base::openmode) [with _CharType = unsigned char; std::ios_base::openmode = std::_Ios_Openmode]’
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:402:3:   required from here
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:480:130: error: no type named ‘_TaskRetType’ in ‘struct pplx::details::_TaskTypeTraits<auto, false>’
 ionTypeTraits<_Function, _ReturnType>::_FuncRetType>::_TaskRetType> _TaskOfType
                                                                     ^
In file included from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/streams.h:18:0,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/pch/stdafx.h:103,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:16:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/astreambuf.h: In instantiation of ‘pplx::task<void> Concurrency::streams::details::streambuf_state_manager<_CharType>::close(std::ios_base::openmode) [with _CharType = unsigned char; std::ios_base::openmode = std::_Ios_Openmode]’:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:402:3:   required from here
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/astreambuf.h:418:29: error: no matching function for call to ‘pplx::task<void>::then(Concurrency::streams::details::streambuf_state_manager<_CharType>::close(std::ios_base::openmode) [with _CharType = unsigned char; std::ios_base::openmode = std::_Ios_Openmode]::<lambda()>)’
                     closeOp = closeOp.then([this_ptr] { return this_ptr->_close
                             ^
In file included from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/pch/stdafx.h:99:0,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:16:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:4405:10: note: candidate: template<class _Function> typename pplx::details::_ContinuationTypeTraits<_Function, void>::_TaskOfType pplx::task<void>::then(_Function&&, pplx::task_options) const
     auto then(_Function&& _Func, task_options _TaskOptions = task_options()) co
          ^
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:4405:10: note:   substitution of deduced template arguments resulted in errors seen above
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:4441:10: note: candidate: template<class _Function> typename pplx::details::_ContinuationTypeTraits<_Function, void>::_TaskOfType pplx::task<void>::then(_Function&&, pplx::cancellation_token, pplx::task_continuation_context) const
     auto then(_Function&& _Func, cancellation_token _CancellationToken, task_co
          ^
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:4441:10: note:   template argument deduction/substitution failed:
In file included from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/streams.h:18:0,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/pch/stdafx.h:103,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:16:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/astreambuf.h:418:29: note:   candidate expects 3 arguments, 1 provided
                     closeOp = closeOp.then([this_ptr] { return this_ptr->_close
                             ^
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/astreambuf.h: In instantiation of ‘pplx::task<void> Concurrency::streams::details::streambuf_state_manager<_CharType>::close(std::ios_base::openmode) [with _CharType = char; std::ios_base::openmode = std::_Ios_Openmode]’:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:402:3:   required from here
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/astreambuf.h:416:39: error: invalid use of ‘auto’
                     closeOp = closeOp && _close_write().then([this_ptr]{}); // 
                                       ^
In file included from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/pch/stdafx.h:99:0,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:16:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h: In instantiation of ‘struct pplx::details::_ContinuationTypeTraits<Concurrency::streams::details::streambuf_state_manager<_CharType>::close(std::ios_base::openmode) [with _CharType = char; std::ios_base::openmode = std::_Ios_Openmode]::<lambda()>, void>’:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:4405:10:   required by substitution of ‘template<class _Function> typename pplx::details::_ContinuationTypeTraits<_Function, void>::_TaskOfType pplx::task<void>::then(_Function&&, pplx::task_options) const [with _Function = Concurrency::streams::details::streambuf_state_manager<_CharType>::close(std::ios_base::openmode) [with _CharType = char; std::ios_base::openmode = std::_Ios_Openmode]::<lambda()>]’
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/astreambuf.h:418:29:   required from ‘pplx::task<void> Concurrency::streams::details::streambuf_state_manager<_CharType>::close(std::ios_base::openmode) [with _CharType = char; std::ios_base::openmode = std::_Ios_Openmode]’
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:402:3:   required from here
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:480:130: error: no type named ‘_TaskRetType’ in ‘struct pplx::details::_TaskTypeTraits<auto, false>’
 ionTypeTraits<_Function, _ReturnType>::_FuncRetType>::_TaskRetType> _TaskOfType
                                                                     ^
In file included from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/streams.h:18:0,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/pch/stdafx.h:103,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:16:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/astreambuf.h: In instantiation of ‘pplx::task<void> Concurrency::streams::details::streambuf_state_manager<_CharType>::close(std::ios_base::openmode) [with _CharType = char; std::ios_base::openmode = std::_Ios_Openmode]’:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:402:3:   required from here
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/astreambuf.h:418:29: error: no matching function for call to ‘pplx::task<void>::then(Concurrency::streams::details::streambuf_state_manager<_CharType>::close(std::ios_base::openmode) [with _CharType = char; std::ios_base::openmode = std::_Ios_Openmode]::<lambda()>)’
                     closeOp = closeOp.then([this_ptr] { return this_ptr->_close
                             ^
In file included from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/pch/stdafx.h:99:0,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:16:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:4405:10: note: candidate: template<class _Function> typename pplx::details::_ContinuationTypeTraits<_Function, void>::_TaskOfType pplx::task<void>::then(_Function&&, pplx::task_options) const
     auto then(_Function&& _Func, task_options _TaskOptions = task_options()) co
          ^
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:4405:10: note:   substitution of deduced template arguments resulted in errors seen above
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:4441:10: note: candidate: template<class _Function> typename pplx::details::_ContinuationTypeTraits<_Function, void>::_TaskOfType pplx::task<void>::then(_Function&&, pplx::cancellation_token, pplx::task_continuation_context) const
     auto then(_Function&& _Func, cancellation_token _CancellationToken, task_co
          ^
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/pplx/pplxtasks.h:4441:10: note:   template argument deduction/substitution failed:
In file included from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/streams.h:18:0,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/pch/stdafx.h:103,
                 from /home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/src/http/client/http_client.cpp:16:
/home/guy/Desktop/Guy/dev/httpClientCasablanca/casablanca/Release/include/cpprest/astreambuf.h:418:29: note:   candidate expects 3 arguments, 1 provided
                     closeOp = closeOp.then([this_ptr] { return this_ptr->_close
                             ^
src/CMakeFiles/cpprest.dir/build.make:62: recipe for target 'src/CMakeFiles/cpprest.dir/http/client/http_client.cpp.o' failed
make[2]: *** [src/CMakeFiles/cpprest.dir/http/client/http_client.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/cpprest.dir/all' failed
make[1]: *** [src/CMakeFiles/cpprest.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
