### ISSUE TITLE
How to keep Http state in cpprestsdk 

### ISSUE THREAD

**Issue by levuphuong** [Microsoft/cpprestsdk#269]
I use cpprestsdk  to send request to server.
But problem is when I send 2 request. Then server receive them with each different session id. So i cannot check status login of client with session on server.
To send these http requests I used same http_client object (init object 1 times.).

Can anyone please help ? Has anyone done similar kind of thing ?
Thank you.

**Comment by levuphuong** [comment]
The problem was fixed by adding cookie from request header.

**Comment by celsosz** [comment]
Hi @levuphuong, can you show me how do you do it? I have the same issue here.

Regards,
Celso.

**Comment by levuphuong** [comment]
Hi @celsosz 

I just get a cookie from first request
`m_cookie = res.headers()["set-cookie"];`

And then set to requests later.
```
if(m_cookie != "")
	request.headers().add("Cookie", m_cookie);
```

**Comment by gebogebo** [comment]
hi, how do u define the m_cookie and request.
I use http_client to post a request, hoping to add cookie from request header, but not find how to use.
thanks, i am a new to use the library.

**Comment by balamcsd** [comment]
Hi, can you explain briefly how you have done it. It is not clear from your answer how you achieved it

**Comment by balamcsd** [comment]
I found the answer 
Define one class level variable
utility::string_t m_szSessionToken = L"";

Wherever you are adding other request headers, add cookie header 
		if (!m_szSessionToken.empty())
			req.headers().add(L"Cookie", m_szSessionToken);

Once you get response

				auto headers = response.headers();

				auto it = headers.find(U("Set-Cookie"));

				if (it != headers.end()) {
					m_szSessionToken = it->second;
				}

Please note that m_szSessionToken will be set only once (after the first response)
which we store it and add it to request headers (from the second request)

This way client will contact with same jessionid for every call
