### ISSUE TITLE
License clarification for 2.9.0 release

### ISSUE THREAD

**Issue by megaposer** [Microsoft/cpprestsdk#270]
Hi,

just saw the [license.txt](https://github.com/Microsoft/cpprestsdk/blob/v2.9.0/license.txt) was adjusted for the 2.9.0 release to reflect MIT licensing. This is awesome ... but it seems the source files (haven't checked all of them) still contain the Apache 2.0 license preamble.

This will make life difficult for (any) legal department in a corporation which needs to approve the usage of open source components. Does the MIT license in the license.txt take precedence over the Apache 2.0 license in the source files?

Cheers

**Comment by ras0219-msft** [comment]
This was an oversight; thanks for catching it!

**Comment by megaposer** [comment]
My pleasure. Do you plan to fix this within 2.9.x or the next minor release?

**Comment by ras0219-msft** [comment]
We will fix this for the current release (I will put out a 2.9.1 tag containing the adjustments).

**Comment by megaposer** [comment]
Perfect, thanks a lot!

**Comment by ras0219-msft** [comment]
I've pushed https://github.com/Microsoft/cpprestsdk/tree/v2.9.1-license-fix which (I believe) contains all the fixes. I will mark this with a tag and merge it into master when we release NuGet packages.

**Comment by ras0219-msft** [comment]
Pushed v2.9.1 which contains the fixes, along with fixed NuGet packages.
