### ISSUE TITLE
Switch to RapidJSON instead of current JSON parser

### ISSUE THREAD

**Issue by thedrow** [Microsoft/cpprestsdk#271]
RapidJSON is a well known and fast (actually one of the fastest) JSON parsers library written in C++.
Is there a good reason for including a custom JSON parser?

**Comment by grahamreeds** [comment]
And only really became popular a couple of years ago when it went to
version 1.0. Up until that point it was languishing in the land of
perpetual beta.

So when the Casablanca project started in 2012 there is a good chance that
RapidJSON was looked at but was dismissed as being buggy and in beta. Also,
as developers, we always think we can do better if we write it ourselves.

So that is what they did. Would you be equally upset if they had used
another c++ JSON parser?

GR

**Comment by thedrow** [comment]
I'm not upset. I just think that this project could focus on communication with REST services instead of format parsing. 
RapidJSON is just what comes to mind first. You can replace it with any other library. 
Is it something we care to resolve?

**Comment by grahamreeds** [comment]
Is there a serious defect with the current one?

Have you run any benchmarks to prove there is a benefit from switching to
BrandX of parser?

What impact does this change have on the subsystems that consume the parser?

GR

**Comment by ras0219-msft** [comment]
@thedrow Thanks for bringing this up. RapidJSON is indeed an excellent parsing library and does rank very well in benchmarks for both speed and conformance.

We would consider a pull request that can maintain our current APIs while using RapidJSON under the hood, however we would not be willing to break our existing users. If you'd like to use RapidJSON+Cpprestsdk in some particular project, it is straightforward to simply use `.extract_string()` and pass that into RapidJSON's usual parsing mechanisms.

Thank you both for the various perspectives on the issue.

**Comment by thedrow** [comment]
Sure, no problem :)

**Comment by scalpel4k** [comment]
@grahamreeds this is for you ;-)
https://github.com/miloyip/nativejson-benchmark

**Comment by kklouzal** [comment]
RapidJSON is an order of magnitude faster (sometimes two orders faster) than CPPRestSDK's implementation. I would pay to have this implemented and for low-latency applications that use CPPRestSDK any API-Breaking changes that occur from this can be well overlooked. For now I'll continue using `.extract_string()` so RapidJSON can do all my parsing. One less thing developers have to spend their precious time on.

**Comment by soroshsabz** [comment]
ITNOA

@ras0219-msft when RapidJSON is very faster than built-in json or when nlohmann/json is very richer API and features than built-in json, did you have any plan to change built-in json or improvement?

**Comment by SylvainCorlay** [comment]
> nlohmann/json 

Yes, nlohmann/json has a much nicer API than any parser out there.
