### ISSUE TITLE
link with prerequisite libraries

### ISSUE THREAD

**Issue by amigo421** [Microsoft/cpprestsdk#278]
I've just clone the library and faced with some issues during the build process under WIndows.
1. When I load the project (cmakelists.txt) into IDE (clion or qtcreator , as I understand VS still doesn't support cmake directly?), I couldn't build this because it can't find boost.
you are using nuget for the getting boost , sorry that instrument is unknown for me , BOOST_ROOT was specified , however seems cmakelists doesn't look for that. I had to re-write cmakelists .

I don't use Visual Studio and haven't this installed , but seems your version of cmakelists relies on this.
could you provide more generic and classic way cmakelists which relies on cross-platform tools only, like cmake, git, etc? the version with find_package(Boost ..... ....) which actually the same what you do for UNIX platform would be preferable.

2. still have a problem with OpenSSL library. I didn't use this previously, so I'm not sure that understand the problem well, but I've built this from latest git and found that it doesn't contain import libs like libeay32, ssleay32, which your version of cmakelists refers to,
my just built version of OpenSSL contains the libs (import as well as static ones) like:
libcrypto.lib
libssl.lib
openssl.lib 

could you recommend me how to solve this? 

thank you!

**Comment by ras0219-msft** [comment]
We do not currently support building cpprestsdk for Windows using any compilers other than MSVC v120/v140/v141. If you get MSys2 or Cygwin to work, we'd be happy to hear about your success, but we do not intend to officially support those at this time.

Our officially supported way to build for Windows is via the MSBuild Solution files. You should be able to build those files using VS community 2015 (freely available at https://www.visualstudio.com/vs/community/), then consume the precompiled binaries and headers in your other CMake projects using CLion/QTCreator.

Alternatively, you can look at [Vcpkg](https://github.com/microsoft/vcpkg) which will automatically build OpenSSL, Boost, and cpprestsdk and make them easily consumable from a CMake project.

**Comment by amigo421** [comment]
I'm talking about Cygwin/MinGW, just about MSVC,
just asking - why do you not do cmake way for windows (with vc toolchain but without IDE tools? 

regarding OpenSSL, the developers told me:
"...
There are two generations of OpenSSL in flight at the moment:

- 1.0.2, the 'old' one. Libs are named libeay32.* and ssleay32.*
- 1.1.0, the 'new' one. Libs are named libcrypto*.* and libssl*.*
..."
