### ISSUE TITLE
[http_listener]: how do I get addresses to be resolved?

### ISSUE THREAD

**Issue by kreuzerkrieg** [Microsoft/cpprestsdk#281]
When I create the listener I usually pass a string containing the host name and port for the listener to listen on, for example "http://mymachine:8181/". Now, the question how do I create listener which will listens on "http://127.0.0.1:8181/" or "http://localhost:8181/" if I access the listener locally? how do I create listener which will listen on both DNS name and the IP? Since the listener will answer with "HTTP Error 400. The request hostname is invalid." in case I create it with DNS name and then try to access it by IP.

**Comment by ras0219-msft** [comment]
Hi kreuzerkrieg,

You can make multiple `http_listener` instances to bind to each different server name you'd like to receive on.
Example:
```
#include "cpprest\http_listener.h"

using namespace web::http;
using namespace web::http::experimental::listener;

void get(http_request req)
{
    req.reply(200, "Hi");
}

int main()
{
	http_listener c(U("http://localhost:1081"));
    c.open().wait();
    c.support(get);
    http_listener c2(U("http://127.0.0.1:1081"));
    c2.open().wait();
    c2.support(get);

    std::cin.get();
}
```

**Comment by kreuzerkrieg** [comment]
yep... already drilled down in to the implementation, all listeners are saved in map<string, listener> where the key is the host from listener instantiation. So, to support localhost/127.0.0.1/hostname/dnsname/ip I have to create 5 listeners. I think it is somewhat inconvenient...

**Comment by kreuzerkrieg** [comment]
Any news regarding this one? just found this gist  https://gist.github.com/SeanCline/6005128 and it opens the listener using asterisk, `http_listener listener(U("http://*/json"));` however didnt find any mention in the documentation

**Comment by hh-kasi-mir** [comment]
Just in case anyone has had the same problem and comes across this - you can put address "0.0.0.0" into the URI; if you do that on Linux with the current cpprestsdk, it listens on all interfaces without the need for multiple listeners.

**Comment by kreuzerkrieg** [comment]
> Just in case anyone has had the same problem and comes across this - you can put address "0.0.0.0" into the URI; if you do that on Linux with the current cpprestsdk, it listens on all interfaces without the need for multiple listeners.

Now the final part is to find solution for Win and we are done

**Comment by cserajeevdas** [comment]
Didn't receive Auth code from Authentication Server [Microsoft]:

1. Followed the sample "Oauth2Client.cpp" and created listener (oauth2_code_listener) at below address
https://127.0.0.1:8080/
2.The browser opens and prompts for user credentials.
3. I do login. 
4. Post that I get "This site can’t be reached" error:
https://127.0.0.1:8080/?error=invalid_scope&error_description=The%20provided%20value%20for%20the%20input%20parameter%20%27scope%27%20is%20not%20valid.%20The%20scope%20%27wl.basic%27%20is%20not%20configured%20for%20this%20tenant.&state=QgRm5xeZxVi8avkaYcddHaIc7Pvh3PM5

Note:- checked netstat, the listener[https://127.0.0.1:8080] is active on port 8080.
Checked HTTP response too after opening the browser using GET request, I get return code as 200 (i.e OK)

Please suggest how to get the auth code in this scenario!!
