### ISSUE TITLE
 fatal error C1083: Cannot open include file: 'cpprest/http_client.h visual studio 2012

### ISSUE THREAD

**Issue by ashokchandran** [Microsoft/cpprestsdk#284]
Hi ,
I am trying out the below bing search sample for cpprestsdk on visual studio 2012. 
https://github.com/Microsoft/cpprestsdk/wiki/Getting-Started-Tutorial
I am able to find the cpprestsdk libray using nuget in visual studio 2012. After installing and using the example for bing i am getting the error "Cannot open include file:'cpprest/http_client.h' error. 
Is cpprestsdk still supported on visual studio 2012?

**Comment by ras0219-msft** [comment]
Hi Ashok,

We no longer support VS 2012. I recommend upgrading to VS 2015 community or 2017 (freely available at https://www.visualstudio.com/downloads/)
