### ISSUE TITLE
Dump program if request to server not found?

### ISSUE THREAD

**Issue by levuphuong** [Microsoft/cpprestsdk#292]
Hi

I have a problem with handling exception for client request.
1. `return raw_client->request(request).then([=](http_response response)
{			
	 return response;
});`
If i send a request to server which isn't started. Then Client will go dump "Trace/breakpoint trap (core dumped)".
Now I want to catch this error. Please tell me how to do that.

Update:
2. If i use command `raw_client->request(request).get(); `. it can be throw to error.

Can anyone tell me what is different from method 1 and 2 in catching error?
I really need to use method because that api will be used in UI form.

Thanks.

**Comment by ras0219-msft** [comment]
Hi levuphuong,

Take a look at https://msdn.microsoft.com/en-us/library/dd997692.aspx for how exception handling works in PPLX.

**Comment by levuphuong** [comment]
Thanks for your helpful link.
I saw this. "When possible, surround every call to concurrency::task::get and concurrency::task::wait with a try/catch block to handle ".
That maybe reason why method 2 can throw exception and method 1 can not.
Sorry but i have more a question.
I see a lot of sample application in sdk use method 1. I mean below snippet code without using try and catch.
`return raw_client->request(request).then([=](http_response response) { return response; });`
In my case, I use cpprestsdk to make 1 middleware library which will be used in top UI.
if i use get() or wait() to wait until HTTP response is complete. then UI code will be blocked in time wait HTTP response.
Do you have any comment for this case?

Thank you.

**Comment by ras0219-msft** [comment]
In method 1, it would be the job of whoever is calling the function doing the return to wrap their `.wait()/.get()` in a try/catch.

Depending on what particular UI framework you are using, you probably will want to post a "native" event whenever your task completes. For example, in XAML/UWP this would be using a WinRT event. In traditional Win32, you might use a window message. This will prevent your UI thread from ever needing to block on the task :).

**Comment by levuphuong** [comment]
So i will create PPLX task on top application and then update UI after function in midleware lib returned ( .then()).
I think that way will help flow program not blocked. I will try it and let you know soon.

Thanks for your support.

**Comment by levuphuong** [comment]
That's fine. Thank you.
