### ISSUE TITLE
How to use http_client with sock5 ? 

### ISSUE THREAD

**Issue by basicsk8r13** [Microsoft/cpprestsdk#294]
I want to use the http_client get request with a sock5 proxy.
How could I make this code still do exactly what it does but from a sock5 proxy for example: 127.0.0.1:9000

http_client client(U("http://3.100.5.83/"));
		
uri_builder builder(U("/test.php"));
builder.append_query(U("worker"), utility::conversions::to_string_t(workerName));
return client.request(methods::GET, builder.to_string());

**Comment by ras0219-msft** [comment]
We don't currently have native support for SOCKS5 proxies. Your best options are

1. If you can, use an HTTP proxy instead
2. Use a [proxifier](https://en.wikipedia.org/wiki/Comparison_of_proxifiers) program to handle the proxying in a separate layer from the cpprestsdk-based application.
3. Contribute SOCKS5 support! You will probably need to add an additional field to the `http_client_config` object, along with modifying the underlying connection implementation for each target platform.
