### ISSUE TITLE
[Cmake] Bug - Unknown CMake command "add_compile_options"

### ISSUE THREAD

**Issue by avs009** [Microsoft/cpprestsdk#310]
When trying compile with cmake older than 2.8.12 you receive this error:

`CMake Error at src/CMakeLists.txt:71 (add_compile_options):
  Unknown CMake command "add_compile_options".`

Versions in test compilation:
Cmake 2.8.11.2
Cpp Rest SDK 2.9 Release

The function add_compile_options was added to CMake version 2.8.12 and later, as can see in this release notes:
https://cmake.org/pipermail/cmake/2013-October/056020.html

I suggest increase the minimum version required for compile the 2.9 Release or add another alternative for add compile options.

**Comment by ras0219-msft** [comment]
Thanks for reporting this, I've bumped the minimum version to 3.0.
