### ISSUE TITLE
Request received with get var "request"  omitted from query

### ISSUE THREAD

**Issue by cneira** [Microsoft/cpprestsdk#316]
Hi, 
Trying the example code for http_client, this function always return the error message (Win7)

Request received with get var \"request\" omitted from query. along with the BadRequest status

I just point to http://localhost:9090/json  to produce the error message on the console 

The code is the following 

`void handle_get(http_request req) {
		auto http_get_vars = uri::split_query(req.request_uri().query());

		auto found_name = http_get_vars.find(U("request"));

		if (found_name == end(http_get_vars)) {
			auto err = U("Request received with get var \"request\" omitted from query.");
			uclog << err << endl;
			respond(req, status_codes::BadRequest, json::value::string(err));
			return;
		}

		auto request_name = found_name->second;
		uclog << U("Received request: ") << request_name << endl;
		respond(req, status_codes::OK, json::value::string(U("Request received for: ") + request_name));
	}` 

is this wrong ? or my way of testing the endpoint is wrong ? I used just a browser and a rest client.
to test this but anyways the status code is BadRequest.

**Comment by ras0219-msft** [comment]
If you are hitting http://localhost/json, this is the expected result; you have an empty query parameter! Have you tried hitting http://localhost:9090/json?request=hello ?

**Comment by cneira** [comment]
Thank you very much. that was the problem.  I was not using
http://localhost:9090/json?request=hello.
<http://localhost:9090/json?request=hello>

thanks for your help

On Tue, Dec 20, 2016 at 7:49 PM, Robert Schumacher <notifications@github.com
