### ISSUE TITLE
C4592 warning in Visual Studio 2015 Update 1

### ISSUE THREAD

**Issue by hs3180** [Microsoft/cpprestsdk#34]
There is a warning that stops compiling websocket++ in line 164, connection.hpp

    static std::vector<int> const versions_supported = {0,7,8,13};

Severity | Code | Description | Project  | File | Line | Suppression State
-------- | ------ | ------ | ----- | ----- | ----- | -------
Warning	|C4592	|'websocketpp::versions_supported': symbol will be dynamically initialized (implementation limitation)	|cpprestsdk140|	\path\to\cpprestsdk\Release\libs\websocketpp\websocketpp\connection.hpp	| 164 |
Error	| C2220	|warning treated as error - no 'object' file generated	|cpprestsdk140|	\path\to\cpprestsdk\Release\libs\websocketpp\websocketpp\connection.hpp| 164	 |

Seems that it is a bug in vs2015-1:
http://stackoverflow.com/questions/34013930/error-c4592-symbol-will-be-dynamically-initialized-vs2015-1-static-const-std

**Comment by kavyako** [comment]
You are right, and it looks like the warning has been fixed for next VS Update. 
For the time being, you could suppress the warning in casablanca140.vcxproj. 
We will gladly accept a PR if you wish to contribute.

**Comment by kavyako** [comment]
The fix is now in development branch.
