### ISSUE TITLE
Weird pause in HTTP listener when listening on 0.0.0.0

### ISSUE THREAD

**Issue by adah1972** [Microsoft/cpprestsdk#349]
I am testing a very simple HTTP listener that deal with JSON requests. While it performs well on http://localhost:8383/, it has weird pauses when listening on http://0.0.0.0:8383/. The pause is also very regular: `http_listener` pauses for exactly one or two seconds every 125 requests—this is seen from the log output of the handle_post function.

```
Replied: Tue, 07 Feb 2017 17:13:41.317 +0800
Replied: Tue, 07 Feb 2017 17:13:41.320 +0800
Replied: Tue, 07 Feb 2017 17:13:41.324 +0800
Replied: Tue, 07 Feb 2017 17:13:42.329 +0800
Replied: Tue, 07 Feb 2017 17:13:42.334 +0800
Replied: Tue, 07 Feb 2017 17:13:42.337 +0800
```

My platform is macOS Sierra + cpprestsdk 2.9.1 (from Homebrew). I cannot reproduce this problem on a Linux machine, so it looks like a platform-specific issue. I would appreciate any suggestions.

**Comment by marcofiocco** [comment]
Did you find a solution? It crashes for me on Windows

**Comment by adah1972** [comment]
No.

However, crashing would be surprising, considering that the authors should test on Windows first ;-). Are you sure the difference is really 0.0.0.0 vs. 127.0.0.1?

**Comment by marcofiocco** [comment]
Actually it does not crash but it throws an exception. If I ignore it runs, but it's not able to receive any message, and when I stop it it throws another exception...

**Comment by marcofiocco** [comment]
I've found a solution, if I do http://*:8383 it works

**Comment by adah1972** [comment]
We are having different problems: listening on http://*:8383 does not even work on Mac. I got an exception with the following message:

```
resolve: Host not found (authoritative)
```

So your way is not portable, to say the least.

**Comment by damienhocking** [comment]
Http services are different on Windows and Posix platforms, it's part of 
the OS and network stacks.  CPPRest has to work around the outside of 
those.  On Posix you still need to specify an IP address, on Windows you 
can use *.

Damien

**Comment by EvgenyVorobyov** [comment]
Inability to use uniform syntax for Windows and Linux is still a problem. I want to listen to any address and I have to type "http://*:port/" for Windows and "http://0.0.0.0:port/" for Linux. Will it be fixed? And should I open a new issue?

**Comment by adah1972** [comment]
I no longer observe pauses, due to either the OS upgrade or cpprestsdk upgrade.
