### ISSUE TITLE
WebSocket server implementation?

### ISSUE THREAD

**Issue by garethsb-ghost** [microsoft/cpprestsdk#358]
I had been hoping to find a websocket server implementation to use alongside http_listener. Have I missed it, is it in the roadmap, or do you have any pointers on doing it myself (I'm currently looking at mashing something up wrapping websocketpp::server)?

Thanks!

**Comment by ampyx** [comment]
+1

**Comment by gdelab** [comment]
+1

**Comment by garethsb-sony** [comment]
Please see if the interface at https://github.com/sony/nmos-cpp/blob/master/Development/cpprest/ws_listener.h and implementation at https://github.com/sony/nmos-cpp/blob/master/Development/cpprest/ws_listener_implementation.cpp is of interest. It may not be complete enough for cpprestsdk yet, but feedback is welcome.

**Comment by sinall** [comment]
@garethsb-sony do you plan to send a pull request to cpprestsdk? It will help a lot of people.

**Comment by garethsb-sony** [comment]
Yes. Sorry, it will take us a little while to prepare to do it, but any feedback is welcome.

**Comment by hdiethelm** [comment]
+1 for this!
I implemented the function set_message_handler(), so the server can also handle incoming messages:
[ws.diff.txt](https://github.com/Microsoft/cpprestsdk/files/1732548/ws.diff.txt)

**Comment by nathanprins** [comment]
@garethsb-sony are you still intending on sending a pr? It has been some time since your previous comment.

**Comment by garethsb-sony** [comment]
@nathanprins There seems little interest from the Microsoft maintainers in adding new functionality, and I think it unlikely a PR would be accepted without a test suite in the C++ REST SDK style. However, my implementation is in active use on several projects and is now reasonably feature complete. See interface at https://github.com/sony/nmos-cpp/blob/master/Development/cpprest/ws_listener.h and implementation at https://github.com/sony/nmos-cpp/blob/master/Development/cpprest/ws_listener_impl.cpp.

**Comment by nathanprins** [comment]
Alright, I'll take a closer look at your repo. Thanks!

**Comment by garethsb-sony** [comment]
@nathanprins - recently updated to enable richer user validation on connection, e.g. to check "Authorization" header when doing Secure WebSocket.

**Comment by jbbcst** [comment]
Hi all,

I am testing ccprestsdk on a Linux system, i am using the handler.cpp file (as in the sample Restweb available in Documentations/Samples). I can respond to the different HTTP requests (GET, POST...), my question is about WebSocket server side, is it possible to add it at the same level of the handle.cpp file? I have already implemented the HTTP request processing in the handler.cpp and I wonder if I can manage the websocket in the same file, at the same level?

Thanks in advance

**Comment by garethsb** [comment]
The nmos-cpp websocket_listener server is functional and works in same style as cpprestsdk, but must be opened on a different port than an http_listener.

**Comment by garethsb** [comment]
Yes, that's it.

**Comment by jbbcst** [comment]
Ok thanks, is there an example of using websockets processing with nmos? I looked in the documentation but did not find

**Comment by garethsb** [comment]
The `websocket_listener` is used in nmos-cpp itself but there isn't currently a standalone example just showing how to use it/alongside `http_listener`. That would be nice for sure...

**Comment by jbbcst** [comment]
Thank you for your help,  I'll take a closer look

**Comment by barcharcraz** [comment]
This is not on the roadmap, and we don't intend to support new server types
