### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/cpprestsdk#359]
> Platforms - Windows desktop, Windows Store, Windows Phone, Ubuntu, OS X, iOS, and Android

Is only Ubuntu supported or are other Linux distros supported as well?
If they are, the README should be clarified.

https://github.com/Microsoft/cpprestsdk/blob/master/README.md

**Comment by ras0219-msft** [comment]
We only regularly test on Ubuntu, however we should be compatible with any POSIX-compliant system that has boost, openssl, and zlib (we can use the internal copy of websocketspp).

We've fixed build issues on CentOS before, for example #65. From my current understanding, we are being used successfully on other POSIX systems.

**Comment by OlafvdSpek** [comment]
Nice. I see there's even a Debian package, so I think broader support should be mentioned.

**Comment by saqibahmed515** [comment]
I'm having problem on fedora. Kindly have a look at this issue. [#327](https://github.com/Microsoft/cpprestsdk/issues/327)
