### ISSUE TITLE
SEC_E_BUFFER_TOO_SMALL error

### ISSUE THREAD

**Issue by juergenr** [Microsoft/cpprestsdk#36]
I get sometimes (randomly) an error on using http_request on http_client.
The error occurs in completion_callback in the line:
 p_request_context->report_error(errorCode, build_error_msg(error_result));
The error code is ox80090321: meaning SEC_E_BUFFER_TOO_SMALL

I have no clue how I could track the error.

Any help or advice is greatly appreciated!

**Comment by Danimoth** [comment]
Hi,
I tried investigating the "random" part of the bug by using the simple BingRequest sample which covers the classes/methods you mentioned. However, I was not able to encounter the [0x80090321](https://msdn.microsoft.com/en-us/library/windows/desktop/dd542646%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) error code.

Could you please share sample test code that leads you to this error code from:
```
p_request_context->report_error(errorCode, build_error_msg(error_result));
```
(http_client_winhttp.cpp line 1022 in the current dev branch)

Also, the underlying platform details?
