### ISSUE TITLE
Can sample CasaLens run in Ubuntu?

### ISSUE THREAD

**Issue by theonionman** [microsoft/cpprestsdk#363]
I try to compile sample CasaLens in Ubuntu, but it seems that the header file of agents.h and tchar.h could not be found. So is there any way to fix these problems? Need I install other related libraries first?

**Comment by ras0219-msft** [comment]
The CasaLens sample currently only runs on Windows. The `tchar.h` header is a Unicode helper library on Windows (part of the Windows SDK) that probably doesn't have an analog on Ubuntu. `agents.h` is a part of the PPL, which was not added to the cross-platform `pplx` subset.

If you'd like to modify it to work on Ubuntu without substantially impacting the behavior, we'd be happy to take that contribution back upstream.
