### ISSUE TITLE
How do I make a POST request with parameters?

### ISSUE THREAD

**Issue by Varun-Sethu** [Microsoft/cpprestsdk#370]
This is the first time I have ever used this library and I was wondering how I would make a POST request. Please help me.

**Comment by Pintulalm** [comment]
I have implemented basic template set for GET,PUT,POST and DELETE requests . may be it can help you [Restweb](https://github.com/Pintulalm/Restweb)

**Comment by Varun-Sethu** [comment]
Thanks! This really helped
