### ISSUE TITLE
CMake don't support windows xp

### ISSUE THREAD

**Issue by horatii** [Microsoft/cpprestsdk#394]
I use vcpkg build cpprestsdk (vcpkg build cpprest:x86-windows-static), I found that have MACRO CPPREST_TARGET_XP can make it work , but i can't find it in CMakelist.txt

**Comment by ras0219-msft** [comment]
Hi @horatii, note that Vcpkg does not currently support XP.

While Cpprestsdk _can_ be built for XP, we consider it deprecated and do not test for XP. If you would like to modify the CMakeLists.txt to add the macro, you can add a single line at the top of the main `Release\CMakeLists.txt`:
```cmake
add_definitions(-DCPPREST_TARGET_XP)
```
