### ISSUE TITLE
Undefined boost::throw_exception(.. while trying to use SDK on Mac OSX

### ISSUE THREAD

**Issue by kunaldp-dev** [Microsoft/cpprestsdk#396]
I've been trying to use the SDK in my project on platform Mac OS x x86_64 based system and have been getting the following error.

Undefined symbols for architecture x86_64:
  "boost::throw_exception(std::exception const&)", referenced from:
      boost::asio::detail::do_throw_error(boost::system::error_code const&, char const*) in Common.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [build/darwin/x86_64/debug/obj/device/cpp/unit_test/test] Error 1

Now I did some search on this and it seems like I'd have to define the function boost::throw_exception in my project if I have BOOST_NO_EXCEPTIONS defined.  Based on this link http://stackoverflow.com/questions/9272648/boost-symbol-not-found

Can someone please help on this issue.

**Comment by abmantis** [comment]
Any tips on the solution to this?
