### ISSUE TITLE
thread_local in listener handler is never destructed

### ISSUE THREAD

**Issue by toby-allsopp** [Microsoft/cpprestsdk#400]
I have a `thread_local` variable in my handler function that is passed to `http_listener::support`. I never see the destructor of the thread local object called, even when the listener is shut down.

Is there something I can do to cause the threads to exit cleanly and thereby call the destructors of my thread local objects?

This is on Windows 10, compiling with VS 2015.

**Comment by LeonineKing1199** [comment]
Is it even valid to have `thread_local` in a handler? As far as I understand the library, callables are received and are executed in a background threadpool so threads aren't explicitly spawned or destroyed as tasks are executed.

I'm not sure if there's a cpprestsdk way of forcing the spawning of a thread for a task.

**Comment by toby-allsopp** [comment]
Not sure why it would be invalid. In our case, we have an object that is expensive to construct that is used during hte processing of each request. We need to ensure that if requests are being processed concurrently then they are using different instances, but we want to avoid creating a new one for every request. The `thread_local` works great for that, but it never seems to get destructed.

**Comment by toby-allsopp** [comment]
🏏s...

Is anyone reading this? We have a horrible hack in our code to work around this issue and I'd really like to be able to remove it.

**Comment by ras0219-msft** [comment]
We use the Windows Threadpool for task execution, so `thread_local` objects will be cleaned up based on the Threadpool lifetime -- potentially never, depending on the specifics of how it interacts with the application. This is to optimize the creation of new threads, which can be very expensive.

If you're looking for deterministic object lifetime, you probably will be better served by wrapping an unordered_map in an SRW lock, then keying off of the thread id [1]. Once you shut down the listener, you can purge the map; this would probably be most easily done by capturing it by `shared_ptr` in your handler.

[1] https://msdn.microsoft.com/en-us/library/mt771567.aspx#get_id_function

**Comment by toby-allsopp** [comment]
OK, thanks. Is "SRW lock" a MS thing?

**Comment by ras0219-msft** [comment]
Yeah, it's a very high performance shared mutex [1]. You could also use `std::shared_mutex`[2], which is backed by the same (just checked with the implementer).



[1] https://msdn.microsoft.com/en-us/library/windows/desktop/aa904937(v=vs.85).aspx
[2] https://docs.microsoft.com/en-us/cpp/standard-library/shared-mutex

**Comment by toby-allsopp** [comment]
Great, thank you for the info!
