### ISSUE TITLE
Use nuget/vcpkg to fetch dependencies

### ISSUE THREAD

**Issue by iHateInventNames** [Microsoft/cpprestsdk#411]
At cmake configure time try find dependencies like boost and openssl.
If no path was provided to cmake then fetch it using nuget or vcpkg.
Visual Studio 2017 cmake integration tools would be able to configure it well right after fetching the project.

**Comment by LeonineKing1199** [comment]
Why not just use vcpkg to fetch the cpprestsdk in the first place? :P

**Comment by iHateInventNames** [comment]
This would no allow to use dynamic link of its dependencies to reduce footprint. However the task is about coziness of configuring for Microsoft Visual Studio.

**Comment by LeonineKing1199** [comment]
I think there's a typo in your first sentence so I'm not sure what you meant.

But don't worry, everything installed via `vcpkg` does use DLLs. The `.lib`s you're linking against are import libraries which handle all that DLL loading nonsense for you. So you don't need to worry, all your dependencies installed via `vcpkg` do use DLLs so the footprint is reduced overall.

To echo your point though, I would like to see VS + `vcpkg` integration at some point. `vcpkg` is probably my favorite new tool to come from MS besides cpprestsdk.
