### ISSUE TITLE
Does project team have plan to support to compile cpprestsdk using visual studio 2017 ?

### ISSUE THREAD

**Issue by ityuhui** [microsoft/cpprestsdk#424]
Hi 
As title, do you have any plan to support visual studio 2017 to compile cpprestsdk?
Thanks

**Comment by LeonineKing1199** [comment]
I think I was able to build cpprestsdk using Visual Studio 2017 by using vcpkg and the Developer Command Prompt for VS 2017.

**Comment by ras0219-msft** [comment]
Vcpkg will build cpprestsdk using VS2017, and if you'd like to just grab the latest master you can do:
```
vcpkg install cpprestsdk --head
```
Additionally if you open the cpprestsdk140.sln solution file in VS 2017 and simply hit "yes" on the upgrade prompt it will build cleanly in VS2017. Our CMake build also fully supports building in VS2017 (`-G "Visual Studio 15 2017"`) -- use Vcpkg to get our dependencies.

Thus, the only thing "missing" here would be to duplicate the entire tree of MSBuild projects. Considering the above, I'll put this on the backlog but it has a pretty poor benefit/cost.

**Comment by ityuhui** [comment]
I think this is resolved by https://github.com/microsoft/vcpkg/issues/1841
