### ISSUE TITLE
http_request::reply causes SIGSEGV on Linux

### ISSUE THREAD

**Issue by robertbindar** [Microsoft/cpprestsdk#44]
I would appreciate if you could help me with this issue. I built the 'master' branch and I get segfault every time I want to reply to a request.

Part of the stack trace looks like this:

#0  0x0000000000686410 in vtable for web::http::details::_http_response ()
#1  0x000000000044609b in __gnu_cxx::new_allocator<web::http::details::_http_response>::destroy<web::http::details::_http_response> (this=0x7fffd4000f00, 
    __p=0x7fffd4000f00) at /usr/include/c++/4.9/ext/new_allocator.h:124
#2  0x0000000000442af9 in std::allocator_traits<std::allocator<web::http::details::_http_response> >::_S_destroy<web::http::details::_http_response> (__a=..., 
    __p=0x7fffd4000f00) at /usr/include/c++/4.9/bits/alloc_traits.h:282
#3  0x000000000043fcbf in std::allocator_traits<std::allocator<web::http::details::_http_response> >::destroy<web::http::details::_http_response> (__a=..., 
    __p=0x7fffd4000f00) at /usr/include/c++/4.9/bits/alloc_traits.h:411
#4  0x000000000043ac81 in std::_Sp_counted_ptr_inplace<web::http::details::_http_response, std::allocator<web::http::details::_http_response>, (__gnu_cxx::_Lock_p
olicy)2>::_M_dispose (this=0x7fffd4000ef0) at /usr/include/c++/4.9/bits/shared_ptr_base.h:524

**Comment by kavyako** [comment]
Could you please share the sample test code and the underlying platform details.

**Comment by ras0219-msft** [comment]
no repro.
