### ISSUE TITLE
Not able to use the wildchar "+" with http_listener

### ISSUE THREAD

**Issue by ashwinravianandan** [Microsoft/cpprestsdk#446]
Hello,

I am not able to use "+" wildchar in the URI fed to the http_listener.  When I use the '*' wildchar, localhost is resolved but directly specifying the IP or 127.0.0.1 doesn't work.  The exception message I receive is:
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<
  what():  resolve: Host not found (authoritative)

Environment: linux amd64.  Library version 2.9.1 ( built based on git tag )

**Comment by ashwinravianandan** [comment]
I have submitted a pull request that resolves this issue:
https://github.com/Microsoft/cpprestsdk/pull/447

**Comment by ras0219-msft** [comment]
Thanks for the PR!
