### ISSUE TITLE
Intel C++ Compiler 17.0 produces compilation warning

### ISSUE THREAD

**Issue by gladkovdmitry17** [Microsoft/cpprestsdk#455]
Intel C++ Compiler 17.0 concerned about missing return statement at the end of function:
`cpprest\json.h(1398): warning #1011: missing return statement at end of non-void function "web::json::number::operator=="`

That's not a problem, because program will be aborted in `_assume(0);` statement, but it will be pretty nice to suppress this kind of compilation warning.

**Comment by ras0219-msft** [comment]
Fixed by #454, thanks!
