### ISSUE TITLE
I can't get this to compile correctly. I've already done sudo apt-get install libcpprest-dev?

### ISSUE THREAD

**Issue by petachew** [Microsoft/cpprestsdk#457]
My Code

#include <iostream>
#include <cpprest/ws_client.h>

int main() { return 0; }

ISSUE:

Scanning dependencies of target cpprestsdk
[ 50%] Building CXX object CMakeFiles/cpprestsdk.dir/main.cpp.o
[100%] Linking CXX executable cpprestsdk
CMakeFiles/cpprestsdk.dir/main.cpp.o: In function `pplx::details::_TaskCollectionImpl::_RunTask(void (*)(void*), void*, pplx::details::_TaskInliningMode)':
/usr/include/pplx/pplx.h:205: undefined reference to `pplx::get_ambient_scheduler()'
collect2: error: ld returned 1 exit status
CMakeFiles/cpprestsdk.dir/build.make:94: recipe for target 'cpprestsdk' failed
make[3]: *** [cpprestsdk] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cpprestsdk.dir/all' failed
make[2]: *** [CMakeFiles/cpprestsdk.dir/all] Error 2
CMakeFiles/Makefile2:79: recipe for target 'CMakeFiles/cpprestsdk.dir/rule' failed
make[1]: *** [CMakeFiles/cpprestsdk.dir/rule] Error 2
Makefile:118: recipe for target 'cpprestsdk' failed
make: *** [cpprestsdk] Error 2

CMakeLists.txt

cmake_minimum_required(VERSION 3.7)
project(cpprestsdk)

set(CMAKE_CXX_STANDARD 11)

set(SOURCE_FILES main.cpp)
add_executable(cpprestsdk ${SOURCE_FILES})

**Comment by ras0219-msft** [comment]
Hi @petachew,

Could you post your CMake file? You will need to also link several boost and openssl libraries.

**Comment by petachew** [comment]
@ras0219-msft 

CMakeLists.txt

cmake_minimum_required(VERSION 3.7)
project(cpprestsdk)

set(CMAKE_CXX_STANDARD 11)

set(SOURCE_FILES main.cpp)
add_executable(cpprestsdk ${SOURCE_FILES})

**Comment by ras0219-msft** [comment]
Ah, I see you changed the original post.

You'll need to link cpprestsdk, boost, and openssl. I recommend doing:

```cmake
find_library(CPPREST_LIB cpprest)
find_package(Boost REQUIRED COMPONENTS random system thread filesystem chrono atomic date_time regex)
find_package(OpenSSL 1.0.0 REQUIRED)

target_link_libraries(cpprestsdk
  ${CPPREST_LIB}
  Boost::boost
  Boost::random
  Boost::system
  Boost::thread
  Boost::filesystem
  Boost::chrono
  Boost::atomic
  Boost::date_time
  Boost::regex
  OpenSSL::SSL)
```

**Comment by petachew** [comment]
Thank you so much :) It works!!!!!
