### ISSUE TITLE
http_listener is getting slower over time on Windows

### ISSUE THREAD

**Issue by wdx04** [Microsoft/cpprestsdk#46]
I wrote a simple http server using http_listener, with a simple client to test the performance of the server. Then I observed that the http server is getting slower after every run of the client, and its memory consumption is increasing:

```
PS C:\Develop\Tests\testrestserver\Release> ./testrestclient.exe
Sending 1000 requests...
Ellapsed Time: 1380 ms.
PS C:\Develop\Tests\testrestserver\Release> ./testrestclient.exe
Sending 1000 requests...
Ellapsed Time: 1468 ms.
PS C:\Develop\Tests\testrestserver\Release> ./testrestclient.exe
Sending 1000 requests...
Ellapsed Time: 1572 ms.
PS C:\Develop\Tests\testrestserver\Release> ./testrestclient.exe
Sending 1000 requests...
Ellapsed Time: 1642 ms.
PS C:\Develop\Tests\testrestserver\Release> ./testrestclient.exe
Sending 1000 requests...
Ellapsed Time: 1774 ms.
PS C:\Develop\Tests\testrestserver\Release> ./testrestclient.exe
Sending 1000 requests...
Ellapsed Time: 1952 ms.
PS C:\Develop\Tests\testrestserver\Release> ./testrestclient.exe
Sending 1000 requests...
Ellapsed Time: 2062 ms.
PS C:\Develop\Tests\testrestserver\Release> ./testrestclient.exe
Sending 1000 requests...
Ellapsed Time: 2153 ms.
PS C:\Develop\Tests\testrestserver\Release> ./testrestclient.exe
Sending 1000 requests...
Ellapsed Time: 2210 ms.
PS C:\Develop\Tests\testrestserver\Release> ./testrestclient.exe
Sending 1000 requests...
Ellapsed Time: 2352 ms.
PS C:\Develop\Tests\testrestserver\Release> ./testrestclient.exe
Sending 1000 requests...
Ellapsed Time: 2420 ms.
```

Testing Environment:
Hardware: AMD A10-5757M APU, 8GB RAM
Operating System: Windows 8.1 x64
Compiler: Visual C++ 2013 Update 2
C++ REST SDK version: 2.7

I also run the same test on Ubuntu 14.04 LTS on the same machine, the Boost.Asio-based http_listener do not have the problem.

Server source code:

```c++
#include <stdio.h>
#include <cpprest/uri.h>
#include <cpprest/http_listener.h>
#include <cpprest/asyncrt_utils.h>
#pragma comment(lib, "cpprest120_2_7.lib")
#pragma comment(lib, "bcrypt.lib")
#pragma comment(lib, "crypt32.lib")
#pragma comment(lib, "winhttp.lib")
#pragma comment(lib, "httpapi.lib")

using namespace web;
using namespace http;
using namespace utility;
using namespace http::experimental::listener;

class CommandHandler
{
public:
	CommandHandler() {}
	CommandHandler(utility::string_t url);

	pplx::task<void> open() { return m_listener.open(); }
	pplx::task<void> close() { return m_listener.close(); }

private:
	void handle_get_or_post(http_request message);

	http_listener m_listener;
};

CommandHandler::CommandHandler(utility::string_t url) : m_listener(url)
{
	m_listener.support(methods::GET, std::bind(&CommandHandler::handle_get_or_post, this, std::placeholders::_1));
	m_listener.support(methods::POST, std::bind(&CommandHandler::handle_get_or_post, this, std::placeholders::_1));
}

void CommandHandler::handle_get_or_post(http_request message)
{
	message.reply(status_codes::OK, "ACCEPTED");
};

int main(int argc, char argv[])
{
	try
	{
		utility::string_t address = U("http://*:8080");

		uri_builder uri(address);
		auto addr = uri.to_uri().to_string();

		CommandHandler handler(addr);
		handler.open().wait();

		ucout << utility::string_t(U("Listening for requests at: ")) << addr << std::endl;
		ucout << U("Press ENTER key to quit...") << std::endl;
		std::string line;
		std::getline(std::cin, line);

		handler.close().wait();
	}
	catch (std::exception& ex)
	{
		ucout << U("Exception: ") << ex.what() << std::endl;
		ucout << U("Press ENTER key to quit...") << std::endl;
		std::string line;
		std::getline(std::cin, line);
	}

	return 0;
}
```

Client source code:

```c++
#include <stdio.h>
#include <tchar.h>
#include <iostream>
#include <chrono>
#include <cpprest/uri.h>
#include <cpprest/asyncrt_utils.h>
#include <cpprest/http_client.h>
#pragma comment(lib, "cpprest120_2_7.lib")
#pragma comment(lib, "bcrypt.lib")
#pragma comment(lib, "crypt32.lib")
#pragma comment(lib, "winhttp.lib")

using namespace std;
using namespace web::http;
using namespace web::http::client;
using namespace utility;

#define N 1000

int _tmain(int argc, _TCHAR* argv[])
{
	cout << "Sending " << N << " requests..." << endl;
	auto t1 = std::chrono::high_resolution_clock::now();
	for (int i = 0; i < N; i++)
	{
		http_client c(U("http://localhost:8080/"));
		c.request(methods::GET, uri_builder(U("/PASS")).to_string())
		.then([=](http_response resp)
		{
			resp.extract_string().get();
		}).wait();
	}
	auto t2 = std::chrono::high_resolution_clock::now();
	cout << "Ellapsed Time: " << chrono::duration_cast<chrono::milliseconds>(t2 - t1).count() << " ms." << endl;
	return 0;
}
```

**Comment by wdx04** [comment]
The problem is caused by the concurrency runtime.
Add preprocessor definition CPPREST_FORCE_PPLX and recompile the library and the programs then the problem is gone.

**Comment by grahamreeds** [comment]
Surely though having to force pplx is a bug? There shouldn't be a memory
leak in either runtime?

**Comment by wdx04** [comment]
From the blog article http://ib-krajewski.blogspot.hk/2015/09/casablanca-c-rest-framework-one-year.html 

1. The only really big problem that hit us was the performance. The troublewas, that after a couple of thousands of file uploads or downloads, server performance tumbled into a free fall: the same basic polling which normally had taken 2-3% of the CPU time surged to 20-30% after that! That was a real show stopper at first. And of course it wasn't our code that showed up in the profiler, it was some of Casablanca internals!

 It took me about 2 weeks to investigate that, and maybe I'll write a more detailed post about it some time, but for now it suffices to say that Windows Concurrency Runtime (i.e. the native, task-based implementation of PPL) was left with an ever-growing internal list, which was sequentially scanned with each tick of the scheduler - at least in our environment of Windows 7 and Visual Studio 2013 plus an early Casablanca version (1.2.0).

 I reported it to Microsoft, and they reacted pretty quickly - the next release has been given a define (CPPREST_FORCE_PPLX) to disable Concurrency Runtime and switch over to Windows Threadpool based implementation of PPL. I got the latest version from the development branch, tested it, and voila! our performance problems vanished into thin air. We then waited for the next release (2.5.0) and when it came out, we upgraded our code to it and suddenly everything worked like a charm. BTW, for the Casablanca version for Visual Studio 2015 Windows Threadpool is the default setting (or so I was told)**.

**Comment by ChristophAlbert** [comment]
I noticed the problem of the high CPU load also with Websockets on Win32 (and VS2013), and the CPPREST_FORCE_PPLX symbol helps. 
But I have a question: Does switching to Windows Threadpool have any disadvantage compared to Concurrency Runtime? Is there a reason the symbol isn't set by default?
