### ISSUE TITLE
How to build with a custom Boost version?  Changed from 2.8 to 2.9

### ISSUE THREAD

**Issue by damienhocking** [Microsoft/cpprestsdk#461]
Up to version 2.8 of the cpprestsdk, you could build with a custom Boost version, for example like this:

https://casablanca.codeplex.com/discussions/571458

We've been using 2.8 compiled on Windows and Linux against Boost 1.61 and it's been fine.  With version 2.9 the -DBOOST_ROOT= yada/yada/yada in CMake doesn't work anymore.  There's been a lot of CMake changes.  What should we do in 2.9 to use a custom Boost (1.64 is what we're moving to).

Damien

**Comment by damienhocking** [comment]
Anyone know how to build on Linux with the latest version?

**Comment by ras0219-msft** [comment]
`-DBOOST_ROOT` should still work on Linux; the cmake build still eventually just calls `find_package(Boost)`[1]. Does a trivial cmake project correctly respond to `-DBOOST_ROOT` on your system?

Could you try adding the boost diagnostic macros[2] to the configure line for cpprest? (`-DBoost_DEBUG=ON` and `-DBoost_DETAILED_FAILURE_MSG=ON`)

[1] https://github.com/Microsoft/cpprestsdk/blob/6cac701e2d76e87fd5392b4129e8b4c2d18926ba/Release/cmake/cpprest_find_boost.cmake#L21
[2] https://cmake.org/cmake/help/latest/module/FindBoost.html

**Comment by komrat1988** [comment]
Hello. In cpprestsdk/Release/cmake/cpprest_find_boost.cmake i set.
-      set(BOOST_ROOT "${CMAKE_BINARY_DIR}/../Boost-for-Android/build" CACHE INTERNAL "")
-      set(BOOST_LIBRARYDIR "${CMAKE_BINARY_DIR}/../Boost-for-Android/build/lib" CACHE INTERNAL "")
+      set (BOOST_ROOT "${CMAKE_BINARY_DIR}/../boost_1_64_0/" CACHE INTERNAL "")
+      set (BOOST_INCLUDEDIR "${CMAKE_BINARY_DIR}/../boost_1_64_0/include" CACHE INTERNAL "")
+      set (BOOST_LIBRARYDIR "${CMAKE_BINARY_DIR}/../boost_1_64_0/armeabi-v7a" CACHE INTERNAL "")

**Comment by damienhocking** [comment]
I'm going to close this and try again with 2.10 because it looks like there's quite a few changes.
