### ISSUE TITLE
No support for Visual Studio 2017 (v141) platform toolset

### ISSUE THREAD

**Issue by avivanoff** [Microsoft/cpprestsdk#482]
Are there plans to have support for Visual Studio 2017 (v141) platform toolset?

**Comment by ras0219-msft** [comment]
VS2017 is supported through:
- All of the v140 NuGet packages support VS2017
- [Vcpkg](https://github.com/microsoft/vcpkg): `vcpkg install cpprestsdk:x64-windows`
- CMake
- Our MSBuild projects, by following the upgrade wizard.
