### ISSUE TITLE
Fixing crossplat::threadpool on Windows

### ISSUE THREAD

**Issue by adah1972** [Microsoft/cpprestsdk#503]
<pplx/threadpool.h> defines a useful `crossplat::threadpool`, which I used in one project in order to use the boost timer without creating a separate `boost::asio::io_service`. I then found out it did not work on Windows. It turned out that fixing it was not that difficult. While `boost::asio::io_service` does not work so well with `std::thread`, replacing `std::thread` with `boost::thread` is all I need.

Of course, `crossplat::threadpool` is not a main exposed API, but it is useful in some cases. Probably this is worth fixing?

**Comment by LeonineKing1199** [comment]
I think MS is trying to expose their parallelism via their `pplx::task` interface. On Windows, each `task` is run on the Windows system thread pool. The crossplatform thread pool is there for the Linux ports of cpprest. For this framework/lib, I'd recommend sticking with `task`s everywhere you can.

You can also check out stlab's concurrency library as well.

**Comment by adah1972** [comment]
Closing this as the current master branch is no longer using `std::thread` in threadpool.
