### ISSUE TITLE
Release for VS2017 (MSVC 14.1)?

### ISSUE THREAD

**Issue by JunielKatarn** [Microsoft/cpprestsdk#505]
Will you be releasing a NuGet variant for the MSVC 14.1 toolset?

Projects that need to use the latest compilers have issues consuming the current NuGet package.

**Comment by ras0219-msft** [comment]
What issues do you have with the current NuGet package? The latest packages should support MSVC 14.1.

**Comment by JunielKatarn** [comment]
Visual Studio 2017 fails to grab the package (targets?) correctly.

Simple way to test is, create Empty C++ project in VS2017, add cpprestsdk.v140.windesktop.msvcstl.dyn.rt-dyn, try to build importing some CPPRest header.

**Comment by ras0219-msft** [comment]
Following those repro steps results in a functional program for me.
```cpp
#include <cpprest/http_client.h>
int main()
{
    web::http::client::http_client c(U("www.microsoft.com"));
}
```

**Comment by JunielKatarn** [comment]
Guess I got a false negative.

Thanks :)
