### ISSUE TITLE
GCC or clang report filestream.h -Wsign-compare

### ISSUE THREAD

**Issue by fcharlie** [Microsoft/cpprestsdk#506]
commit: 7dca8e4a5c7c9624648f4ad92d92dac350f28c46

In the following code, written should not be compared with '-1' (maybe SIZE_T MAX ?)

```cpp
        virtual pplx::task<size_t> _putn(const _CharType *ptr, size_t count)
        {
            auto result_tce = pplx::task_completion_event<size_t>();
            auto callback = new _filestream_callback_write<size_t>(m_info, result_tce);

            size_t written = _putn_fsb(m_info, callback, ptr, count, sizeof(_CharType));

            if ( written != 0 && written != -1 )
            {
                delete callback;
                written = written/sizeof(_CharType);
                return pplx::task_from_result<size_t>(written);
            }
            return pplx::create_task(result_tce);
        }
```

https://github.com/Microsoft/cpprestsdk/blob/7dca8e4a5c7c9624648f4ad92d92dac350f28c46/Release/include/cpprest/filestream.h#L363

https://github.com/Microsoft/cpprestsdk/blob/7dca8e4a5c7c9624648f4ad92d92dac350f28c46/Release/include/cpprest/filestream.h#L575

**Comment by garethsb-sony** [comment]
Resolved by PR #585 (hasn't been merged yet though).

**Comment by ras0219-msft** [comment]
Fixed by #585, thanks again @garethsb-sony!

**Comment by fcharlie** [comment]
@ras0219-msft  Thanks, I hope you can always respond so quickly.

**Comment by garethsb** [comment]
@ras0219-msft You're welcome, and thanks for applying; I'm actively working with cpprestsdk on a few different platform/compiler combinations - and waiting for approval to sign the CLA - so I hope you'll be able to have a look at a few more of my PR (more in the pipeline!) soon.

**Comment by garethsb-sony** [comment]
@ras0219-msft You're welcome, and thanks for applying; I'm actively working with cpprestsdk on a few different platform/compiler combinations - and waiting for approval to sign the CLA - so I hope you'll be able to have a look at a few more of my PR (more in the pipeline!) soon.
