### ISSUE TITLE
listener_construction_tests.cpp:535:17: error: ‘class boost::asio::ssl::context’ has no member named ‘use_certificate_chain’

### ISSUE THREAD

**Issue by fjd1234** [Microsoft/cpprestsdk#553]
I'm trying to build cpprestsdk (2.9) on CentOS 7 and hitting the error below. I've done a few Google searches and it seems to be a boost issue (less than 1.47). I'm using 1.53 so not sure what's up. Hopefully I'm missing some package or need to remove another. I've included info from my system, but any pointers would be appreciated.

listener_construction_tests.cpp:535:17: error: ‘class boost::asio::ssl::context’ has no member named ‘use_certificate_chain’

[root@cni-builder-9-6-223 build]#  rpm --query centos-release
centos-release-7-3.1611.el7.centos.x86_64

[root@cni-builder-9-6-223 build]# g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@cni-builder-9-6-223 build]# yum list installed | grep 'boost\|ssl\|cmake\|gcc'
boost.x86_64                           1.53.0-27.el7                   @base    
boost-atomic.x86_64                    1.53.0-27.el7                   @base    
boost-chrono.x86_64                    1.53.0-27.el7                   @base    
boost-context.x86_64                   1.53.0-27.el7                   @base    
boost-date-time.x86_64                 1.53.0-27.el7                   @base    
boost-devel.x86_64                     1.53.0-27.el7                   @base    
boost-filesystem.x86_64                1.53.0-27.el7                   @base    
boost-graph.x86_64                     1.53.0-27.el7                   @base    
boost-iostreams.x86_64                 1.53.0-27.el7                   @base    
boost-locale.x86_64                    1.53.0-27.el7                   @base    
boost-math.x86_64                      1.53.0-27.el7                   @base    
boost-program-options.x86_64           1.53.0-27.el7                   @base    
boost-python.x86_64                    1.53.0-27.el7                   @base    
boost-random.x86_64                    1.53.0-27.el7                   @base    
boost-regex.x86_64                     1.53.0-27.el7                   @base    
boost-serialization.x86_64             1.53.0-27.el7                   @base    
boost-signals.x86_64                   1.53.0-27.el7                   @base    
boost-system.x86_64                    1.53.0-27.el7                   @base    
boost-test.x86_64                      1.53.0-27.el7                   @base    
boost-thread.x86_64                    1.53.0-27.el7                   @base    
boost-timer.x86_64                     1.53.0-27.el7                   @base    
boost-wave.x86_64                      1.53.0-27.el7                   @base    
cmake.x86_64                           2.8.12.2-2.el7                  @base    
cmake3.x86_64                          3.6.3-1.el7                     @epel    
cmake3-data.noarch                     3.6.3-1.el7                     @epel    
compat-gcc-44.x86_64                   4.4.7-8.el7                     @base    
cross-gcc-common.noarch                4.8.5-16.el7.1                  @epel    
extra-cmake-modules.noarch             5.36.0-1.el7                    @epel    
gcc.x86_64                             4.8.5-16.el7                    @base    
gcc-c++.x86_64                         4.8.5-16.el7                    @base    
gcc-x86_64-linux-gnu.x86_64            4.8.5-16.el7.1                  @epel    
libgcc.i686                            4.8.5-16.el7                    @base    
libgcc.x86_64                          4.8.5-16.el7                    @base    
mingw32-gcc.x86_64                     4.9.3-1.el7                     @epel    
openssl.x86_64                         1:1.0.2k-8.el7                  @base    
openssl-devel.x86_64                   1:1.0.2k-8.el7                  @base    
openssl-libs.x86_64                    1:1.0.2k-8.el7                  @base    
python-backports-ssl_match_hostname.noarch
[root@cni-builder-9-6-223 build]#

Thanks
Frank

**Comment by fjd1234** [comment]
That did it! I downloaded and built 1.54 and was able to build!

Thanks!

**Comment by wing328** [comment]
@fjd1234 if you don't mind, I wonder if you can contact me via the email address in my profile page.

I got a quick question for you about cpprestsdk.
