### ISSUE TITLE
http client request timeout

### ISSUE THREAD

**Issue by definename** [Microsoft/cpprestsdk#558]
Hi all,
I am going to use [set_timeout](http://microsoft.github.io/cpprestsdk/classweb_1_1http_1_1client_1_1http__client__config.html#ab13a7fc0e1d2d79abd11ed0da42e35b5) function in order to send requests to the server with some delay.

That is code of my client:
`web::http::client::http_client_config cfg;
cfg.set_timeout(std::chrono::seconds(10));
cfg.set_validate_certificates(false);
web::http::client::http_client client(U("http://localhost:7788"), cfg);
`

But no delay occurs. What am I doing wrong. Is it correct usage of `set_timeout` function?
Thanks.

**Comment by deeringc** [comment]
The timeout here refers to how long the client will wait for a particular leg of the asynchronous flow (of making a http request and receiving the response) to complete. Eg. It makes sure that the DNS query resolves within the period specified or else it fails the overall request. In my experience the timeout applies to each leg of the request individually. So, if you specify the timeout as 10 seconds it has 10 seconds to do the DNS, 10 seconds to connect TCP,  etc...

**Comment by definename** [comment]
So, in order to send request with some delay I need to do it by my own. There are no built-in functionality.

**Comment by deeringc** [comment]
That's correct, depending what platform you're on there are a range of options.

**Comment by definename** [comment]
Ok, got it. Thanks.

**Comment by abhisekmane98** [comment]
@deeringc Let's assume If one of particular leg get resolved in 5sec, Then it will proceed to another step or wait for to complete 10 Sec. 

```
response_task = client.request(req);
response = response_task.get();
```

here **client** is object of `http_client` class and **req** is object of `http_req` class. So I have concern that if response didn't came for in given time like 15 Second then then function should return. So what should I do that use this timeout functionality or else ?
