### ISSUE TITLE
Building cpprestsdk141.sln under Visual Studio 2017

### ISSUE THREAD

**Issue by mangh** [Microsoft/cpprestsdk#568]
### Loading
When I open cpprestsdk141.sln under VS2017 (and performing suggested retarget of cpprest141.andoid.vcxproj to "Android NDK r13b") the following projects fails to load (due to missing Windows10SDK.10240):

* cpprest141.uwp
* OAuth2Live141
* FacebookDemo141
* BlackJack_UIClient141

To fix this I have changed WindowsTargetPlatformVersion in the above projects, from the original "10.0.10240.0" to "10.0.16299.0" (SDK that I have installed):
```
<PropertyGroup Label="Globals">
   ...
   <WindowsTargetPlatformVersion>10.0.16299.0</WindowsTargetPlatformVersion>
   ...
</PropertyGroup>
```
After that I could load all projects and retarget the whole solution to SDK 10.0.16299.0. 
### Missing includes
Then it appeared that the solution does not build due to inaccessible includes:
```
packages\boost.1.58.0.0\lib\native\include\boost\asio\ssl\detail\openssl_types.hpp(19): fatal error C1083: Cannot open include file: 'openssl/conf.h': No such file or directory
release\src\http\common\http_helpers.cpp(33): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory
```
so I have inserted the following properties into cpprest141.vcxproj (right after `<PropertyGroup Label="Globals">`):
```
<PropertyGroup>
  <Force-Enable-openssl-v140-windesktop-msvcstl-static-rt-dyn-x86 Condition="'$(Platform)' == 'Win32'">true</Force-Enable-openssl-v140-windesktop-msvcstl-static-rt-dyn-x86>
  <Force-Enable-openssl-v140-windesktop-msvcstl-static-rt-dyn-x64 Condition="'$(Platform)' == 'x64'">true</Force-Enable-openssl-v140-windesktop-msvcstl-static-rt-dyn-x64>
  <Force-Enable-zlib-v140-windesktop-msvcstl-static-rt-dyn-x86 Condition="'$(Platform)' == 'Win32'">true</Force-Enable-zlib-v140-windesktop-msvcstl-static-rt-dyn-x86>
  <Force-Enable-zlib-v140-windesktop-msvcstl-static-rt-dyn-x64 Condition="'$(Platform)' == 'x64'">true</Force-Enable-zlib-v140-windesktop-msvcstl-static-rt-dyn-x64>
</PropertyGroup>
```
### Broken references
Then I have rebuilt the solution and - when it failed again - found that several projects have broken references to either `cpprest141` or `cpprest141.uwp` (yellow warning tag overlaying the reference icon). I have edited invalid vcxprojs and removed the broken reference(s):
```
<ItemGroup>
  <ProjectReference Include="$(CasablancaSrcDir)\build\vs141.uwp\cpprest141.uwp.vcxproj">
    <Project>{198ED804-2655-4D92-8104-C220E3EA9452}</Project>
  </ProjectReference>
</ItemGroup>
```
and then added new references to `cpprest141.vcxproj` (or `cpprest141.uwp.vcxproj`) under Visual Studio.
### Memory limit
Then I have added `/Zm150` to AdditionalOptions for BlackJack_UIClient141 project to eliminate errors C3859 (virtual memory range for PCH exceeded) and C1076 (compiler limit: internal heap limit reached).
### Remaining issues
Finally, after all of the above, **cpprestsdk141.sln seems to build correctly**, remaining two issues which (I think) can be ignored:
```
Unknown compiler version - please run the configure tests and report the results
```
from old `boost` library being unhappy when coping with younger Visual Studio partner, and:
```
Warning LNK4099 PDB 'zlibstatic.pdb' was not found with 'zlibstaticd.lib(...)'...
```
### Question
Is all of the above the right way to build cpprestsdk141.sln under Visual Studio 2017?

**Comment by dsailesh** [comment]
Why not build without retargeting the solution?

**Comment by mangh** [comment]
Why not retarget? Is there anything special in the "original" target (that is not installed)?

**Comment by wajsic** [comment]
Having the same problem

**Comment by karaahmed** [comment]
Having the same problem after retargeting to SDK 10.0.16299.0 that's included with VS2017 update 4.

**Comment by ras0219-msft** [comment]
Thank you for reporting this issue with such a detailed analysis!

I've applied all the fixes you mentioned, confirmed they work, and pushed the results to master.
