### ISSUE TITLE
how to set credentials while using C++ REST SDK

### ISSUE THREAD

**Issue by pramodbugudai** [Microsoft/cpprestsdk#573]
Hi Experts,

I am trying to make a GET request using the C++ REST SDK and when I try to set user name and password
using the class credentials cred(L"username", L"pwd") it crshes my program on an API http://localhost:8080/api/v1/Users . Any clues on this. Not able to proceed further. Any help is appreciated.

**Comment by deeringc** [comment]
Which platform are you on? Do you have a stack trace of where the program is crashing? Can you give some sample code of what you are doing?

**Comment by pramodbugudai** [comment]
Hi Deeringc,
Thanks for reviewing my question. We get it solved now. Thanks for contributing your answer.
