### ISSUE TITLE
Build Error with Visual Studio 15.5 preview 2

### ISSUE THREAD

**Issue by Milerius** [Microsoft/cpprestsdk#579]
![image](https://user-images.githubusercontent.com/21139416/32266764-ea159764-bee8-11e7-8437-cd656a9a0b84.png)

"do_while" is not member of Concurrency::details

Compile fine on visual studio 15.4.2
cpprest version : 2.9 , if anyway its works on cpprest 2.10, it's possible to update the microsoft vcpkg port for 2.10 version ?

**Comment by ras0219-msft** [comment]
Hi @Milerius, we indeed already have updated the vcpkg port to 2.10! Please make sure to `git pull` the latest, re-run `.\bootstrap-vcpkg.bat`, then `vcpkg remove cpprestsdk` and `vcpkg install cpprestsdk`.
