### ISSUE TITLE
web::http::experimental::listener::http_listener wait() called is blocked.

### ISSUE THREAD

**Issue by grouser** [Microsoft/cpprestsdk#581]
I have bumped into a strange problem.

I am using boost 1.58 on Ubuntu 16.04 and the latest version of Casablanca on the repository.

The code I am using it used to work well in the past. The application gets blocked in the wait() call.  I have got the same problem on different machines.

web::http::experimental::listener::http_listener m_listener;

plx::task<void> HttpServer::open() {
    return m_listener.open();                           
}                                                       
  
**listener.open().wait();**

**Comment by garethsb-sony** [comment]
This may not apply to you but I have encountered this recently when mistakenly building cpprestsdk and application using it with different Boost versions.

**Comment by grouser** [comment]
I have found the solution. Casablanca must be linked before Boost.
