### ISSUE TITLE
How can I derive from the json::value class?

### ISSUE THREAD

**Issue by PantherJohn** [Microsoft/cpprestsdk#586]
How can I derive from the **json::value** class? I know thisis a basic question, but I simply cannot find any solutions of it

**Comment by garethsb-sony** [comment]
What problem are you trying to solve? ``web::json::value`` is a vocabulary type like ``std::string`` and deriving from it doesn't make a lot of sense to me.

Additional convenience operations on ``value`` can be written as free functions, and ``value`` can be used as a member of your own ``struct`` and ``class`` types.

**Comment by PantherJohn** [comment]
Maybe I should use json::value to parse JSON configuration files instead of declaring variables (silly me!). And now it’s not a problem for me. Thanks anyway.
