### ISSUE TITLE
Error: Building package cpprestsdk:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by WarleiAlves** [Microsoft/cpprestsdk#590]
I get this error message when I try to install the CppRestSdk lib. I am using the latest version of vcpkg available in the git repository, cloned into a new folder... Dependencies like ZLib, OpenSSL and Boost have been compiled as expected, but CppRestSdk is always failing at the same point.

As I have not found any reports of this issue so far, I think it may be an unreported error.

Messages in the attachment file have portions in Portuguese. But it's easy to see that this is related to linker settings.

...
-- Build x86-windows-dbg
CMake Error at C:/VDS/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: C:/VDS/vcpkg/buildtrees/cpprestsdk/x86-windows-dbg
    See logs for more information:
      C:\VDS\vcpkg\buildtrees\cpprestsdk\install-x86-windows-dbg-out.log
      C:\VDS\vcpkg\buildtrees\cpprestsdk\install-x86-windows-dbg-err.log

Call Stack (most recent call first):
  C:/VDS/vcpkg/scripts/cmake/vcpkg_build_cmake.cmake:70 (vcpkg_execute_required_process)
  C:/VDS/vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  C:/VDS/vcpkg/ports/cpprestsdk/portfile.cmake:32 (vcpkg_install_cmake)
  C:/VDS/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package cpprestsdk:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cpprestsdk:x86-windows
  Vcpkg version: 0.0.95-2017-11-03-c0090ed4c98dbad3fe855f3ac3b9908e037afa03

Additionally, attach any relevant sections from the log files above.

[install-x86-windows-dbg-out.log](https://github.com/Microsoft/cpprestsdk/files/1442835/install-x86-windows-dbg-out.log)

**Comment by kklouzal** [comment]
You need to open up the Visual Studio Installer, go to "Individual Packages" and ensure you have the "CMake Tools for Visual Studio" installed. (That might not be the *exact* name of the package, however, it is the only package referring to 'cmake')

**Comment by WarleiAlves** [comment]
Well, CMake is set up correctly. It really seems to be something related to the settings of the package CppRestSdk or to the Vcpkg itself. I'm looking for a "restful" client in C ++ and I have some urgency. Otherwise, I would investigate the problem more closely. I left the message in the hope that others who have been dealing with the tools involved and the project itself for some time could shed a light. Anyway, thank you!

**Comment by ras0219-msft** [comment]
@WarleiAlves, thanks for submitting this issue!

It looks like the problem is that we're picking up a rogue copy of OpenSSL on your system: 
`C:\VDS\OpenSSL-Win32\lib\VC\libssl32MDd.lib`. The quickest fix would be to remove that, however I'll look at fixing it upstream as well!

**Comment by WarleiAlves** [comment]
This really was the problem. Many many thanks, @ras0219-msft!
