### ISSUE TITLE
Linux build fails with GCC [7.2.1]  with  [-Werror=type-limits]

### ISSUE THREAD

**Issue by entd** [Microsoft/cpprestsdk#595]
Library build fails on late version GCC:
`~/src/casablanca/Release/src/uri/uri.cpp: In static member function ‘static utility::string_t web::uri::decode(const string_t&)’:
~/src/casablanca/Release/src/uri/uri.cpp:676:24: error: comparison is always false due to limited range of data type [-Werror=type-limits]
         else if (*iter > CHAR_MAX || *iter < 0)
`
While it could be supressed it imply deeper problem with code. For me comparing if 8 bit char is more than CHAR_MAX seems pointless too. Is it false positive?

**Comment by echotor** [comment]
Hi, I want to know this problem is solved or not.

**Comment by StrangeTcy** [comment]
I'm having the same problem and am similarly interested in a solution.

**Comment by codehero** [comment]
This issue occurs with GCC 5.4.0 as well

**Comment by promgamer** [comment]
Same here. Trying to compile with gcc 7 for C++17.

**Comment by sridherj** [comment]
Did it work with C++17?

**Comment by ras0219-msft** [comment]
I've pushed a fix for this to the master branch, thanks everyone for reporting it!
