### ISSUE TITLE
std::wstring to string_t on Linux

### ISSUE THREAD

**Issue by epot** [Microsoft/cpprestsdk#596]
I am a bit lost on why string_t is different between linux and windows. My current issue is that I have a boot::filesystem::path that I can convert to a std::wstring and that I would like to put in a CppRestSDK Json. How can I do that ? On Linux it complains that there is no converstion from std::wstring to string_t right now.

**Comment by ras0219-msft** [comment]
Ideally, you should convert the `boost::filesystem::path` to a `wstring` on Windows and a `string` on Linux. Note that `wstring`s on Windows correspond to UTF-16, but on Linux they correspond to UTF-32.

It looks like `boost::filesystem` is quite full-featured, so there should be APIs available for both of those.

If you want a single code path for all platforms, you could get a UTF-8 `std::string` and pass it through `utility::conversions::to_string_t()`.

**Comment by garethsb-sony** [comment]
In recent versions of Boost, this is exactly what the [``path`` native format observer](http://www.boost.org/doc/libs/1_65_1/libs/filesystem/doc/reference.html#path-native-format-observers), ``native()`` does. ([Operating system examples](http://www.boost.org/doc/libs/1_65_1/libs/filesystem/doc/reference.html#Operating-system-examples) confirms the ``path::value_type`` for Windows and POSIX is ``wchar_t`` and ``char`` respectively.)

I think ``web::json::value::string(my_path.native())`` should be all that's required.

Supporting [C++17 ``std::filesystem``](http://en.cppreference.com/w/cpp/filesystem/path/native) should be just the same; supporting earlier incarnations in Boost.Filesystem, ``std::experimental::filesystem``, ``std::try2::sys``, etc. is possible but needs a bit more work.

**Comment by epot** [comment]
Thanks everyone for the detailed answers!
