### ISSUE TITLE
Link error with VS 2012

### ISSUE THREAD

**Issue by Sumoren** [Microsoft/cpprestsdk#62]
I have multiple error at link this like this:
error LNK2019: unresolved external symbol "__declspec(dllimport) long __cdecl pplx::details::platform::GetCurrentThreadId(void)" (__imp_?GetCurrentThreadId@platform@details@pplx@@YAJXZ) referenced in function "public: void __thiscall pplx::details::_CancellationTokenState::_DeregisterCallback(class pplx::details::_CancellationTokenRegistration *)" (?_DeregisterCallback@_CancellationTokenState@details@pplx@@QAEXPAV_CancellationTokenRegistration@23@@Z)

I added the cpprest120_2_7.lib to my project (nuget didn't keep the job done) but I'm stil missing symbol. It look like it's the only lib in the package.

When I check the pplx include I see weird thing like:
#if (defined(_MSC_VER) && (_MSC_VER >= 1800)) && !CPPREST_FORCE_PPLX
#error This file must not be included for Visual Studio 12 or later
#endif

My _MSC_VER is define to 1700 since I'm on VS 2012 so I don't get the #error but the message said this file must not be included in VS2012. Is the message incorrect?

Thank you

**Comment by Sumoren** [comment]
Did the same test with VS 2015 and I could compile/link after intslling the nuget package. No manual setup require like the tutorial said.

**Comment by jameskennedy2265** [comment]
I was going to tell anyone else looking here that I've been able to use C++ REST SDK with VS2012 by using version 2.4.0.1 as opposed to the most recent versions.

I would love to move to VS2015, but unfortuantley I have to use VS2012 with legacy programs.

So this can solve your problem if you're forced to use VS2012, just get version 2.4.0.1 by manually typing "Install-Package cpprestsdk –Version 2.4.0.1" in the console of the NUGET package manager. (without the quotes of course).
