### ISSUE TITLE
Link error w/ VS2017 15.5 c++17

### ISSUE THREAD

**Issue by VikingExplorer** [Microsoft/cpprestsdk#626]
Built cppRestSdk using vcpkg using this triplet:

set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

When I try to link my DLL, I'm getting errors like this:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _deflate referenced in function "public: class std::vector<unsigned char,class std::allocator<unsigned char> > __thiscall web::http::details::compression::stream_compressor::stream_compressor_impl::compress(unsigned char const *,unsigned int,bool)" (?compress@stream_compressor_impl@stream_compressor@compression@details@http@web@@QAE?AV?$vector@EV?$allocator@E@std@@@std@@PBEI_N@Z)	CouloirAFX	C:\Dev\Couloir\Generic\AFX\MVC\CouloirAFX\cpprest_2_10.lib(http_helpers.cpp.obj)	1	

In my linker settings, my "Additional Dependencies":

Winhttp.lib;httpapi.lib;bcrypt.lib;crypt32.lib;cpprest_2_10.lib;VFW32.lib;WINMM.lib;%(AdditionalDependencies)

Am I missing a lib?

**Comment by VikingExplorer** [comment]
adding zlibd.lib fixed this.

**Comment by ras0219-msft** [comment]
This might still be a bug in cpprestsdk; I believe the current intention is that when building as a DLL we shouldn't be leaking any references to zlib.

**Comment by VikingExplorer** [comment]
I was building it as static library.  All good.
