### ISSUE TITLE
Linker error (Boost) when building with CMake on macOS

### ISSUE THREAD

**Issue by aardvarkk** [Microsoft/cpprestsdk#637]
I installed as per instructions, but when building a project that only includes the header file `http_listener.h` I get the following errors:

```
Undefined symbols for architecture x86_64:
  "boost::system::system_category()", referenced from:
      boost::asio::error::get_system_category() in main.cpp.o
  "boost::system::generic_category()", referenced from:
      boost::system::error_category::std_category::equivalent(int, std::__1::error_condition const&) const in main.cpp.o
      boost::system::error_category::std_category::equivalent(std::__1::error_code const&, int) const in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Seems a bit strange, because when I run the cmake config for the project Boost isn't mentioned at all:

```
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11")
-- Found OpenSSL: /usr/local/opt/openssl/lib/libcrypto.dylib (found version "1.0.2n")
-- Configuring done
-- Generating done
```

It doesn't even seem to be attempting to find the Boost package.

Boost v1.66.0 was installed automatically when I ran `brew install cpprestsdk`.

**Comment by MrString** [comment]
Has this problem been solved?

**Comment by MrString** [comment]
The boost library you are using depends on the boost_system library. (Not all of them do.)

Assuming you use gcc, try adding -lboost_system to your compiler command line in order to link against that library.
https://stackoverflow.com/questions/9723793/undefined-reference-to-boostsystemsystem-category-when-compiling

**Comment by Dantali0n** [comment]
> The boost library you are using depends on the boost_system library. (Not all of them do.)
> 
> Assuming you use gcc, try adding -lboost_system to your compiler command line in order to link against that library.
> https://stackoverflow.com/questions/9723793/undefined-reference-to-boostsystemsystem-category-when-compiling

I find it weird that I manually have to specify to link boost_system when using this library. especially since it manages to add zlib and openssl to the linker when using find_library just fine.

The solution is simple:
```
find_package(Boost 1.53 COMPONENTS system REQUIRED)
find_package(cpprestsdk REQUIRED)

add_executable(example ${EXAMPLE_SOURCE})
target_link_libraries(example cpprestsdk::cpprest ${Boost_SYSTEM_LIBRARY})
```

**Comment by ras0219-msft** [comment]
This is due to issues in CMake version 3.11 and before which have trouble handling newer versions of Boost. This prevents us from correctly "chaining" boost like we do for zlib and openssl.

**Comment by Dantali0n** [comment]
> This is due to issues in CMake version 3.11 and before which have trouble handling newer versions of Boost. This prevents us from correctly "chaining" boost like we do for zlib and openssl.

Thank you for the quick explanation, I will close my issue related to this no need for it to further clog up the issue tracker.
