### ISSUE TITLE
Is this Project Dead? Are there better options?

### ISSUE THREAD

**Issue by JamesBewley** [microsoft/cpprestsdk#649]
Just noticed there are a lot of unanswered tickets against this project.  Is there anyone at Microsoft taking a lead on this?  Is it still active?

I started using this library to connect our C++ application to the Azure cloud but maybe it isn't the right choice.  I've seen examples of working with Amazon AWS APIs using Curl, is this a better option?

**Comment by BSalita** [comment]
Your intuition is justified. I've been following Casablanca from the beginning. Somewhere around 2-3 years ago, it felt like the devs stepped off the accelerator. I'm afraid I'll have to chuck months of casablanca integration into the bitbucket. See you over at the libcurl project.

**Comment by damienhocking** [comment]
It's not dead, there was a patch release 3 weeks ago.  There's a lot of issues because there's a lot of people using it.

**Comment by sonicpp** [comment]
And now?

**Comment by barcharcraz** [comment]
We're fixing extremely critical bugs only but do have someone (me) spending some minimal amount of time monitoring the issues. Lots of stuff falls through the cracks though.

libcurl is our recommended alternative.
