### ISSUE TITLE
"How to build for windows" contains outdated instructions

### ISSUE THREAD

**Issue by JonathanGawrych** [Microsoft/cpprestsdk#653]
https://github.com/Microsoft/cpprestsdk/wiki/How-to-build-for-Windows needs to be updated. Since commit 6f291dd16b244e9d02e54a903f7082f462505fd7, where v120 MSBuild files were removed, these instructions are outdated (they reference the now deleted `cpprestsdk120.sln` and `dirs.proj` files).

**Comment by ras0219-msft** [comment]
Thanks for posting this!

I've updated the page to reflect the new preferred build method using CMake and Vcpkg.

**Comment by JonathanGawrych** [comment]
Just a quick comment here. In order compile streams_test I needed to add `boost-interprocess` to the vcpkg install list. I don't believe this is specific for my machine, so it'd be nice if we could update the page on that.

Thanks!

**Comment by katxeus** [comment]
@JonathanGawrych , could this be the reason why this can't resolve on compiling

> Severity

 Code Description Project File Line Suppression State Error C1083 Cannot open include file: 'boost/interprocess/streams/bufferstream.hpp': No such file or directory streams_test c:\users\katxe\projects\cpprestsdk\release\tests\functional\streams\stdstream_tests.cpp 18

>
