### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by VikingExplorer** [Microsoft/cpprestsdk#659]
Why does code exhibit an apparent memory leak?

```
            TEST_F( WebServiceTests, client_request )
            {
               // Setup
               const String URL( L"https://url.net/Log/Messages/2.8" );

               // Software Unit Under Test
               web::http::uri TheURI( URL );
               web::http::client::http_client client( TheURI );

               client.request( web::http::methods::GET ).then( [&]( web::http::http_response response )
               {
                  if( response.status_code() == web::http::status_codes::OK )
                  {
                     auto result = response.extract_json().get();
                  }
                  if( response.status_code() == web::http::status_codes::NotFound )
                  {
                     Log::msg( MALFUNCTION, "http_response 404" );
                  }
               } ).get();

               // Analysis

               // Evaluate

               // Cleanup
            }
```

0 bytes in 0 Free Blocks.
416 bytes in 16 Normal Blocks.
12944 bytes in 14 CRT Blocks.
0 bytes in 0 Ignore Blocks.
0 bytes in 0 Client Blocks.
Largest number used: 24252 bytes.
Total allocations: 44796 bytes.
C:\Dev\Couloir\3pLibs\Include\MemLeakListener.h(56): error: Failed
Memory leak in WebServiceTests.client_request

**Comment by dimarusyy** [comment]
Are you sure you are not leaking in singleton Log::msg ?
Is URI accessible ? And what version of restsdk do you use ?

**Comment by VikingExplorer** [comment]
Yes, first thing I tried was commenting the Log message out, setting break point. Made no difference for the memory leak, never got there.

**Comment by dimarusyy** [comment]
I tried similar test-case with gtest and restsdk available via vcpkg (see attacheed solution).
So far, no memory leak is reported.
[Sample-Test1.zip](https://github.com/Microsoft/cpprestsdk/files/1629508/Sample-Test1.zip)

**Comment by VikingExplorer** [comment]
Maybe it's from the extract_json call.  Mine hits an actual web service & brings back data.

**Comment by dimarusyy** [comment]
Can you play a bit with a code and comment-out extract_json() call ? 
Some memory leaks were fixed in 2.10 release, please see https://github.com/Microsoft/cpprestsdk/releases/tag/v2.10.0.

**Comment by VikingExplorer** [comment]
```
            TEST_F( WebServiceTests, client_request )
            {
               // Setup
               //const String URL( L"https://url.net/Log/Messages/2.8" );

               // Software Unit Under Test
               web::http::uri TheURI( L"https://swetoolapi.azurewebsites.net/Log/Messages/2.8" );
               web::http::client::http_client client( TheURI );

               client.request( web::http::methods::GET ).then( [&]( web::http::http_response response )
               {
                  if( response.status_code() == web::http::status_codes::OK )
                  {
                     //auto result = response.extract_json().get();
                  }
                  if( response.status_code() == web::http::status_codes::NotFound )
                  {
                     //Log::msg( MALFUNCTION, "http_response 404" );
                  }
               } ).get();

               // Analysis

               // Evaluate

               // Cleanup
            }

```
0 bytes in 0 Free Blocks.
6566 bytes in 136 Normal Blocks.
12944 bytes in 14 CRT Blocks.
0 bytes in 0 Ignore Blocks.
0 bytes in 0 Client Blocks.
Largest number used: 21204 bytes.
Total allocations: 27996 bytes.
C:\Dev\Couloir\3pLibs\Include\MemLeakListener.h(56): error: Failed
Memory leak in WebServiceTests.client_request

**Comment by dimarusyy** [comment]
I'm afraid you either need to post small test-application to reproduce the case, get memory dump of the process or try to figure out yourself what is wrong by running under profiler.

**Comment by VikingExplorer** [comment]
<img width="622" alt="capture1" src="https://user-images.githubusercontent.com/15109208/34920858-afabc596-f947-11e7-80be-6b0e32e30fe4.PNG">

**Comment by VikingExplorer** [comment]
<img width="635" alt="capture" src="https://user-images.githubusercontent.com/15109208/34920866-c3b5df2c-f947-11e7-922c-06bcee4e56ea.PNG">

**Comment by VikingExplorer** [comment]
At this point, I have no code involved, so these leaks can only be coming from cpprestsdk. Call stack bears that out.  Very plausible since multiple memory leaks have been fixed in 2.10.  Must be more to find.  

I'm just trying to help you guys.  I was already tempted to switch to beast, and this just pushed me over the edge.

**Comment by dimarusyy** [comment]
@ras0219-msft, I probably need your impact here. 
I may be wrong, but this is how pplx tasks are designed to work in sdk : after completing request the shared pointer may be still alive for some period of time.

**Comment by VikingExplorer** [comment]
I can't tolerate either actual memory leaks or pseudo-garbage collection like behavior (c++ is deterministic).  

Nothing against pplx.  It was just what I wanted in 2005, when I first head about it.

But now, I want code that is easier to understand and reason about. I want a separation of concerns: threading, async, http, REST & json.

My solution was to refactor my code to boost::beast and rapidjson.
