### ISSUE TITLE
have problem with MACOS (#error <atomic> is not implemented) ?

### ISSUE THREAD

**Issue by 8bitidea** [Microsoft/cpprestsdk#668]
Hi Dears ,
I don't know what i am facing right now ! , is that a successful building of the SDK or not ?
specially the the compiler cannot figure the lib directory except when i define it like that : 
(#include </usr/local/Cellar/cpprestsdk/2.10.1/include/cpprest/http_client.h>)
but still have that error 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:543:2: error: <atomic> is not implemented
#error <atomic> is not implemented

**Comment by shamoons** [comment]
Same issue

**Comment by BillyONeal** [comment]
Looks like they implemented it now.
