### ISSUE TITLE
Nuget package for 2.10?

### ISSUE THREAD

**Issue by sinall** [Microsoft/cpprestsdk#672]
Will there be nuget package for 2.10?
vcpkg should work, but it takes huge space and lots of time to compile.

**Comment by ras0219-msft** [comment]
We do not plan to release a NuGet package for 2.10. However, you can generate one using:

`vcpkg export cpprestsdk:x64-windows --nuget`

After this, you can delete vcpkg and use the produced standalone NuGet package.

**Comment by wheelsmanx** [comment]
we cant use vcpkg as it will not connect 

Building package openssl-windows[core]:x64-windows... 
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip... Failed. Status: 6;"Couldn't resolve host name"

are there any plans to fix either the host name that appears to be down or the nuget package?
