### ISSUE TITLE
provide a Findcpprestsdk.cmake file

### ISSUE THREAD

**Issue by Mr-Foo** [Microsoft/cpprestsdk#69]
Pleas provide means to find the project with cmake.
so that a line like `find_package(cpprestsdk 2.7.0 REQUIRED)` works

**Comment by ras0219-msft** [comment]
This would be awesome.

**Comment by orens** [comment]
+1

**Comment by xgdgsc** [comment]
https://github.com/MatrixManAtYrService/HelloWorld-cpprestsdk like this.

**Comment by elvisdukaj** [comment]
I really want to use `cppredsdk` like

    find_package(cpprestsdk 2.7.0 REQUIRED)
    target_include_directories(mytarget cpprestsdk::cpprest)
    target_link_libraries(mytarget PUBLIC cpprestsdk::cpprest)

Is that possible?

**Comment by promgamer** [comment]
Did someone find a solution to this?

**Comment by elvisdukaj** [comment]
It seems that actualy cpprestsdk works this way!

**Comment by Mr-Foo** [comment]
Yes! Thank you.
