### ISSUE TITLE
streams.h error c2061 syntax error: identifier 'int_type'

### ISSUE THREAD

**Issue by mmetalfan** [Microsoft/cpprestsdk#690]
I recently upgraded cpprestsdk 2.10.1 via vcpkg
After running the upgrade and trying to compile, I am getting the following build error:

c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.12.25827\include\cpprest\streams.h(1724): error C2061: syntax error: identifier 'int_type'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.12.25827\include\cpprest\streams.h(1734): note: see reference to class template instantiation 'Concurrency::streams::type_parser<CharType,enable_if<_Test,_Ty>::type>' being compiled
1>        with
1>        [
1>            _Ty=std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>
1>        ]

I am pretty confused on why this started happening.

**Comment by garethsb-sony** [comment]
I think that's fixed on master. See https://github.com/Microsoft/cpprestsdk/commit/a159e4e7b5eb640a0a09eca8decff32827cb40be.

**Comment by mmetalfan** [comment]
That fixed the issue.
Thank you!

**Comment by mmetalfan** [comment]
Forgot to close this.
