### ISSUE TITLE
Request HTTP2 Support

### ISSUE THREAD

**Issue by fcharlie** [microsoft/cpprestsdk#697]
HTTP2 (rfc7540) has been released for nearly three years. But cpprestsdk not support HTTP2 still now.

In fact, `WinHTTP`, `Httpsys`, and `HttpClient` (Windows Runtime) now support HTTP2. CPPRESTSDK relies on these several components on Windows, so CPPRESTSDK can support HTTP2 on Windows

On Linux, MacOS cpprestsdk can use nghttp2 to support HTTP2. (CURL, Apache httpd, wget also use nghttp2 to support HTTP2).

WinHTTP
```c++
	// HTTP2 support
	DWORD dwOption = WINHTTP_PROTOCOL_FLAG_HTTP2;
	if (!WinHttpSetOption(hSession,
		WINHTTP_OPTION_ENABLE_HTTP_PROTOCOL,
		&dwOption, sizeof(dwOption))) {
		fprintf(stderr, "HTTP2 is not supported\n");
	}
```

Thanks.

**Comment by fcharlie** [comment]
@ras0219-msft Does cpprestsdk have a plan to support HTTP2

**Comment by CyrilleBenard** [comment]
I'm also really interesting in HTTP 2 support

**Comment by BillyONeal** [comment]
Not something we are planning to do anytime soon. Making it work with the asio backend would be the largest difficulty if WinHTTP indeed already has such support.

**Comment by CyrilleBenard** [comment]
Thanks for your feedback. It's really a bad news for us 'cause we planned to use cpprestsdk (on Linux) and we hardly need to be compliant with HTTP2. This is a mandatory aspect in 5G applications :cry:

**Comment by grahamreeds** [comment]
You are welcome to submit a pull request.

GR

**Comment by fcharlie** [comment]
@BillyONeal See: [libnghttp2_asio: High level HTTP/2 C++ library](https://nghttp2.org/documentation/libnghttp2_asio.html)

**Comment by madduci** [comment]
Any news on this?

**Comment by piotr-walczak** [comment]
Hi, was there any change in this regard? Maybe it would be possible to create some plan for http/2 support in terms of what needs to be done, so we could look for volunteers to contribute?

**Comment by barcharcraz** [comment]
Given the fundamental problems with cpprestsdk's tasking model, and the amount of work it's pretty unlikely http/2 will be added (it would be a lot of code to review as well, if it were).

I'd really recommend looking at libcurl instead.

**Comment by piotr-walczak** [comment]
@barcharcraz - thank you for the response!
