### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by jochemvanboxtel** [Microsoft/cpprestsdk#698]
I intend to use CppRestSDK to create a REST API in a Linux environment. I would like to use the Listener to do this, and would like to support HTTPS in the future. I have read several old threads online which say that HTTPS is not supported for the Listener under Linux. Is this true?

Also I read here that CppRestSDK uses OpenSSL. Am I right in assuming that any SSL/TLS version supported by OpenSSL is also supported by CppRestSDK?

**Comment by ras0219-msft** [comment]
We do support HTTPS on Linux: https://github.com/Microsoft/cpprestsdk/issues/343

You are correct, we use OpenSSL, so any SSL/TLS version supported inside that openssl binary should work.

**Comment by AmitGondaliya** [comment]
Hello,

I am exploring cpprestSDK with restweb server in c++ on ubuntu 16.04 host PC, I am able to perform request and response with HTTP protocol, but when I am trying to send the request using HTTPS protocol I am not able to get the response.
would you please suggest how to configure restweb to listen HTTPS request. or how to add support for HTTPS in restweb server.

thanks,
Amit Gondaliya.
