### ISSUE TITLE
[Help] How to get the address of the client connected to http_listener? 

### ISSUE THREAD

**Issue by freegodly** [Microsoft/cpprestsdk#718]
void RestServices::handle_get(http_request message)
{
 std::cout << "client: " << "[ip address]" << " requested " << request << std::endl;
}

**Comment by garethsb-sony** [comment]
Does ``http_request::remote_address`` help?
https://github.com/Microsoft/cpprestsdk/blob/master/Release/include/cpprest/http_msg.h#L933

**Comment by freegodly** [comment]
Thank you,my version is old.
