### ISSUE TITLE
How to set logging level

### ISSUE THREAD

**Issue by yyzhucheckpt** [Microsoft/cpprestsdk#727]
I am using cpp rest sdk for websocket stuff, on the server side, it will print out the logs:

Dispatching write containing 1 messages ....

Looks like it depends on your logging level for this kind of messages. I am wondering how to set the  logging level so no such messages are printed out.

**Comment by garethsb-sony** [comment]
That is a message from inside websocketpp.

C++ REST SDK wraps websocketpp for its existing websocket client implementation. It disables websocketpp's logging (see [ws_client_wspp.cpp](https://github.com/Microsoft/cpprestsdk/blob/master/Release/src/websockets/client/ws_client_wspp.cpp#L265)).

C++ REST SDK doesn't currently include server-side websocket implementation. If you are currently using websocketpp directly, the ws_client_wspp.cpp link above shows how to disable logging from websocketpp. There is a preliminary server-side implementation linked from #358 which also proposes how websocketpp  logging might be adapted to an interface appropriate for C++ REST SDK.
