### ISSUE TITLE
Compiling with CPPREST_FORCE_PPLX for WIN32 in vcpkg

### ISSUE THREAD

**Issue by TheGrandNagus** [Microsoft/cpprestsdk#734]
Hi,

I am trying to compile a win32 package of cpprestsdk with vcpkg and enforce the use of pplx.

I added the -DCPPREST_PPLX_IMPL:STRING=winpplx variable to the portfile.cmake, so that the config block looks like:
```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}/Release
    PREFER_NINJA
    OPTIONS
        ${OPTIONS}
        -DBUILD_TESTS=OFF
        -DBUILD_SAMPLES=OFF
        -DCPPREST_EXCLUDE_WEBSOCKETS=OFF
        -DCPPREST_EXPORT_DIR=share/cpprestsdk
        -DWERROR=OFF
        -DCPPREST_PPLX_IMPL:STRING=winpplx
    OPTIONS_DEBUG
        -DCPPREST_INSTALL_HEADERS=OFF
)
```
The build will fail with several errors.

Compiling in vcpkg without the variable works. Also compiling from the visual strudio project files from this repository works, when the CPPREST_FORCE_PPLX preprocessor definition is set.

What am I doing wrong?

**Comment by garethsb-sony** [comment]
Which version of cpprestsdk is this? What versions of CMake and Visual Studio? Can you attach the errors?

**Comment by TheGrandNagus** [comment]
I am trying to build the triplet: cpprestsdk:x64-windows
Visual Studio Version is 2015

I tried it both on vcpkg version: 0.0.105-2018-03-13-f72b46690a89a7e19563f93f0eaa5f8a21184254
and vcpkg version: 0.0.108-2018-04-12-a2aeb2f1949c42622ccc7f9572a441e2a4475132
wich both seem to use CMake: 3.10.2.

The error are logged in install-x64-windows-dbg-out.log

[install-x64-windows-dbg-out.log](https://github.com/Microsoft/cpprestsdk/files/1910297/install-x64-windows-dbg-out.log)

If you need any of the other logfiles, I will gladly upload them.

**Comment by garethsb-sony** [comment]
That log seems to show that compiling websockets\client\ws_client_wspp.cpp is pulling in both <ppltasks.h> and the cross-platform version in "pplx/pplxtasks.h", which won't work. I can't tell from the log why that should be - ``CPPREST_FORCE_PPLX=1`` should mean the cross-platform version is used. You could try using [/P (Proprocess to a File)](https://msdn.microsoft.com/en-us/library/8z9z0bx6.aspx) to compile that one file to determine why <ppltasks.h> is also being included.

**Comment by garethsb-sony** [comment]
Please can you tell which version of Boost are you using?

**Comment by garethsb-sony** [comment]
OK, to cut a long story short, the problem was introduced by commit 9a4ebda8739c6a82ca345a8a07be5f420b836cf8, which results in unintended ADL, and therefore the amibiguity errors we're seeing, due to the mixed usage in C++ REST SDK of ``namespace Concurrency``, its alias ``concurrency``, and ``pplx`` which is _not_ an alias if ``CPPREST_FORCE_PPLX=1``.

I'll submit a PR.

**Comment by TheGrandNagus** [comment]
Super. That is awsome. Thank you sir!

**Comment by garethsb-sony** [comment]
We need to hope @ras0219-msft revisits C++ REST SDK soon and makes a new release, because there have been a slew of PRs and issues reported in the last few months since v2.10.2. Some of these are controversial but there are several simple fixes that would be great to have in a release.

**Comment by garethsb-sony** [comment]
Thank you, @ras0219-msft ! Please would consider merging the one-liner of #681 from 30 Jan too? :-)

**Comment by garethsb-sony** [comment]
Great, thank you. #742 has been reported recently and looks the same as an older issue with a PR at #575 - which looks like an obvious straightforward fix plus a delay workaround which maybe needs more consideration.

A huge number of the issues that have been reported in the last few months are user error or build environment related. I suspect the 300+ open issues could be triaged down to something more respectable quite simply.
