### ISSUE TITLE
build iOS error

### ISSUE THREAD

**Issue by whipslerin** [Microsoft/cpprestsdk#740]
I used xcode7.2 to build iOS library,I followed the steps, minus the building of boost and openssl, 
I am more or less doing these steps:
`mkdir build.debug
pushd build.debug
cmake .. -DCMAKE_BUILD_TYPE=Debug`
then I get err.
`Check dependencies
target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphonesimulator' platform

** BUILD FAILED **`
I fitted it by fellowed this page
https://github.com/Microsoft/cpprestsdk/issues/436
then I got next error.
`-- Looking for include file xlocale.h - found
-- Setting clang options
-- websocketpp not found, using the embedded version
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/lib/libz.dylib (found version "1.2.5") 
CMake Error at src/CMakeLists.txt:183 (message):
  Unknown compiler`
I had not idea how to do it.

**Comment by JasonYang-MSFT** [comment]
Seems you are trying to build on iOS, but we never test iOS scenario. Maybe you can try our iOS library:
https://github.com/Azure/azure-storage-ios
