### ISSUE TITLE
CMakeLists.txt is missing

### ISSUE THREAD

**Issue by PowerOfCreation** [Microsoft/cpprestsdk#764]
As I do have this #763 Issue I tried building from source. There is just one tiny thing preventing me from doing so: there is no CMakeLists.txt in this project. Are there any plans on adding a CMakeLists.txt so it is possible to build from source?

**Comment by ras0219-msft** [comment]
Issue #763 is caused by an incorrect `find_package()` directive. In our README, we document that the correct invocation is:

```cmake
find_package(cpprestsdk REQUIRED)
```


However, if you would like to build from source, the CMakeLists.txt file is located in the `Release\` subdirectory.
