### ISSUE TITLE
HTML Page Using Javascript to Access C++ REST Web Service?

### ISSUE THREAD

**Issue by jameskennedy2265** [Microsoft/cpprestsdk#77]
Apologies ahead of time if this is the wrong place to put this question, I didn't see a discussion place for general topics. I've also posted this over at the old C++ REST SDK page.

Hey All, 

So I've spent about two weeks learning and creating my web service using C++ REST. 

I've really liked it so far and I've actually got everything up and running I believe. Here is some of the code I am using which will process a simple GET request.

```
int main(int argc, char *argv[])
    {

    uri_builder uri(L"http://localhost:8888");          // This defines my URI location. example is http://localhost:8888/
    http_listener listener(uri.to_uri());              //this will create a listener at the given location of my defined URI above
    printf("HTTP LISTENER STARTED \n");


    // This is the part where the listener can handle GET requests
    listener.support(methods::GET, [](http_request request)         // this block causes the listener to support GET requests
        {                              // When pinged for a GET request it will do the following
        printf("GET Request\n");    
        int status = 5;
        web::json::value statvalue = json::value::number(status);  //putting status into a json container
        printf("GET Request Finished \n");
        request.reply(status_codes::OK, statvalue);

}

```

This handles an incoming GET request and will output the value 5 if completed. I've tested this using TELNET to connect to the webservice and I used a generic GET request 

GET /test HTTP/1.1 
Host: localhost 

in order to show that it all works out. 

Now I am trying to create an HTML web page that will perform a GET request to my webservice. 

So far I've been unable to perform this. Below is what my HTML page is looking like

```
<html>

<head>
    <title>GET TEST</title>
    
        <script language="JavaScript">
        
            var iCallID;
            function InitializeService()
            {
                service.useService("http://localhost:8888/",  "httprequestservice");
                service.httprequestservice.callService("http_request");
            }

            function ShowResult()
            {
               alert(event.result.value);
            }
            
        </script>
        
        <meta http-equiv="refresh" content="5" />
</head>

    <body  onload="InitializeService()"  id="service" style="behavior:url(webservice.htc)"  onresult="ShowResult()">
    
    </body>
    
</html>

```

What am I doing wrong? Is there an example somewhere that someone could show me how to access this websebservice using an HTML page? 

Thanks!

**Comment by damienhocking** [comment]
Are you OK with using AJAX?  It's pretty easy if you use AJAX with jQuery.

Damien

Damien Hocking, PhD
CTO & Founder, Corelium Software
t:  403 510 6619  e: dhocking@coreliuminc.com  w: http://coreliuminc.com

**Comment by jameskennedy2265** [comment]
Hello,

I don't mind using AJAX, but to be honest I have little knowledge of it or JS in general. The most I have is tidbits learned from maintaining a website through Wordpress ha.

Would I need to implement any libraries to use AJAX? Or compile/install any program to use it to create my html page? I probably have a completely wrong idea on how other JS like scripts are done.

**Comment by damienhocking** [comment]
AJAX uses Javascript and it's really not hard to do.  I was in your 
position a year ago and once I got the basics it was not hard to do.  
You can Google for a whole pile of AJAX examples.  There's also a 
non-AJAX way that's pure HTML done in the browser.  Here's good examples 
of both:

http://blog.garstasio.com/you-dont-need-jquery/ajax/

**Comment by jameskennedy2265** [comment]
Thanks m8,

I'll follow along these guidelines from now and update with my new html page to see if I'm on the right direction. Hope it works out.

**Comment by jameskennedy2265** [comment]
So here's my updated code using AJAX/jQuery

```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="refresh" content="5" />
<script src="http://localhost:80"></script>
<script>

        $.get("http://localhost:80", function(data, status){
            alert("Data: " + data + "\nStatus: " + status);

            $("#div1").load(data);
            $("#div2").load(status);

        });

</script>



</head>

<body>

<p>GET TEST</p>
<div id="div1"><h2>tbd</h2></div>
<div id="div2"><h2>tbd2</h2></div>

</body>
</html>

```

From my original code I am assuming that statvalue is the data in my original code.
Good news is that when I run this html page it is seeing my listener and it is responding I am assuming.

I am having difficulty in understanding how I am to display the value of statvalue from my original code in the webpage.

I tried to use the load command, but I don't believe this is it and from the other examples I'm not seeing another method to load the variable into my webpage. I'm probably making something overcomplicated to show the variable data and status.

Thanks!

**Comment by damienhocking** [comment]
http://stackoverflow.com/questions/477543/how-do-i-assign-value-to-a-textbox-using-javascript

Damien

**Comment by jameskennedy2265** [comment]
Thanks again for the help. I finally got it working. The end code for the HTML was 

```
<!DOCTYPE html>
<html>

<body>

<h2>GET TEST</h2>

<p id="demo"></p>


<script>

        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (xhttp.readyState == 4 && xhttp.status == 200) {
                document.getElementById("demo").innerHTML = xhttp.responseText;
            }
        };
        xhttp.open("GET", "http://localhost:80", true);
        xhttp.send();

</script>

</body>
</html>
```

So it's proof that the C++ REST SDK is working perfectly. Thanks for all the help Damien!

James
