### ISSUE TITLE
cpprestsdk can't find boost libraries atomic & random  cmake

### ISSUE THREAD

**Issue by FlorianBehague** [Microsoft/cpprestsdk#771]
Hello !

I have an issue installing cpprestsdk using a cmake file. Here is the cmake file :
[cpprestsdk.txt](https://github.com/Microsoft/cpprestsdk/files/2053937/cpprestsdk.txt)

While installing, it seems enable to find "boost_atomic" and "boost_random" as described in the error : 
[Error.txt](https://github.com/Microsoft/cpprestsdk/files/2053965/Error.txt)

Those libraries are in the same folder than the others as you can see in this picture, and I can't find why those two librairies are an issue regardless of the boost version I am downloading.
![github help picture file](https://user-images.githubusercontent.com/39767454/40721444-d33c8cf6-6419-11e8-9f4e-cb41b92af9be.PNG)

I am currently working on WIN64 ( can this be the problem ? ) and VS 12.

If you need any other information I will answer as soon as possible
Thank you for your time !

**Comment by garethsb-sony** [comment]
Make certain to set BOOST_INCLUDEDIR and BOOST_LIBRARYDIR consistently - the error shows that it thinks it's found Boost 1.58 but the path says "1_56".

The error message also tells you that it's the static libraries that CMake can't find, not the include headers/directories which are in your screenshot.

You may need to use b2 to build an appropriate configuration of the libraries you need, e.g. 64-bit, VS 12, static.

God luck.
