### ISSUE TITLE
How to enable 'CPPREST_FORCE_HTTP_LISTENER_ASIO'?

### ISSUE THREAD

**Issue by sinall** [Microsoft/cpprestsdk#783]
I'm trying to use vcpkg to install cpprestsdk, and I want to be able to use 'CPPREST_FORCE_HTTP_LISTENER_ASIO'.

How do I pass this pre-processor definitions to vcpkg?

**Comment by sinall** [comment]
The reason I want to use ASIO is because otherwise the application needs admin privileges.
I don't know if it still needs admin privileges when 'CPPREST_FORCE_HTTP_LISTENER_ASIO' is enabled.

**Comment by BillyONeal** [comment]
I don't know if vcpkg has a means to pass in custom defines like this; I think it does not. You can always install cpprestsdk's dependencies with vcpkg and then build this yourself.

Note that the listeners should be considered experimental.
