### ISSUE TITLE
Crash in 2.7 

### ISSUE THREAD

**Issue by glukacsy** [Microsoft/cpprestsdk#79]
Hi, 

Have you guys ever seen this or have any idea what might cause this (we are getting this reported from our users via Crashaltytics)?

Regards,
Gergely

Thread : Crashed: Thread
0  libcpprest.2.7.dylib           0x10da10b7d boost::asio::detail::posix_thread::func<boost::asio::detail::resolver_service_base::work_io_service_runner>::run() + 29
1  libcpprest.2.7.dylib           0x10da10b13 boost_asio_detail_posix_thread_function + 19
2  libsystem_pthread.dylib        0x7fff98172c13 _pthread_body + 131
3  libsystem_pthread.dylib        0x7fff98172b90 _pthread_body + 166
4  libsystem_pthread.dylib        0x7fff98170375 thread_start + 13

**Comment by ras0219-msft** [comment]
Unfortunately, this simply says that one of the boost threadpool threads crashed. Without more information (what other threads were doing, was it a segfault/exception/memory corruption/???), there's nothing to do here.
