### ISSUE TITLE
error C3861: '_parse_input': identifier not found.

### ISSUE THREAD

**Issue by robert-andrzejuk** [Microsoft/cpprestsdk#794]
Using: VS 2017 Preview (15.8.3)

In the file `streams.h` line 1750 method `parse` calls  the protected template function `_parse_input` from a template base class.

This gives an error: `cpprestsdk\release\include\cpprest\streams.h(1750): error C3861: '_parse_input': identifier not found`

The solution is to prefix this call with the type: `_type_parser_base<CharType>`.

**Comment by robert-andrzejuk** [comment]
Related Visual Studio issue: 
https://developercommunity.visualstudio.com/content/problem/238445/template-class-cant-access-protected-member-when-c.html

Problem is that my code is compiling with `/permissive-`, so the template functions are affected by this issue.

**Comment by robert-andrzejuk** [comment]
Created a pull request for a fix: #809

**Comment by robert-andrzejuk** [comment]
PR merged.

**Comment by ChristophePichaud** [comment]
I updated to 15.8.3 and compilation failed ! a shame !
Why does the libraries are not recompiled on each release of the compiler ????????
It's so simple... A so big mistake !!!!
