### ISSUE TITLE
My program directly exit without any prompt message "concrt140.dll was not found"

### ISSUE THREAD

**Issue by Fang3s** [Microsoft/cpprestsdk#796]
In general, A message dialog will pop up if missing xx.dll (e.g. msvcp140.dll). But, why my program seems not run (nothing flashes in Windows Task Magager unless I use a debugger to execute it) without any message dialog about missing dll and then after I copy a CONCRT140.dll, it can run successfully?
```
MyProgam.exe
  + msvcp140.dll
  + vcruntime140.dll
  + cpprest_2_10.dll
         + LIBEAY32.dll
         + SSLEAY32.dll
         + CONCRT140.DLL
         + msvcp140.dll
         + vcruntime140.dll
```

**Comment by BillyONeal** [comment]
concrt140.dll is part of the Visual C++ redistributable. See https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
