### ISSUE TITLE
Crash in boost::asio::detail::resolver_service_base

### ISSUE THREAD

**Issue by glukacsy** [Microsoft/cpprestsdk#80]
Hi, 

Same question as with the other one: did anyone has seen this before?

Regards,
Gergely

0   libcpprest.2.7.dylib  
boost::asio::detail::resolver_service_base::resolver_service_base(boost::asio::io_service&) + 20
1
libcpprest.2.7.dylib  
boost::asio::io_service::service\* boost::asio::detail::service_registry::createboost::asio::ip::resolver_service<boost::asio::ip::tcp >(boost::asio::io_service&) + 77
2
libcpprest.2.7.dylib  
boost::asio::detail::service_registry::do_use_service(boost::asio::io_service::service::key const&, boost::asio::io_service::service\* (*)(boost::asio::io_service&)) + 179
3
libcpprest.2.7.dylib  
web::http::client::details::asio_client::asio_client(web::uri, web::http::client::http_client_config) + 1923
4
libcpprest.2.7.dylib  
std::__1::shared_ptrweb::http::client::details::asio_client std::__1::shared_ptrweb::http::client::details::asio_client::make_shared<web::uri const&, web::http::client::http_client_config const&>(web::uri const&&&, web::http::client::http_client_config const&&&) + 165
5
libcpprest.2.7.dylib  
std::__1::shared_ptrweb::http::client::details::http_network_handler std::__1::shared_ptrweb::http::client::details::http_network_handler::make_shared<web::uri const&, web::http::client::http_client_config const&>(web::uri const&&&, web::http::client::http_client_config const&&&) + 125
6
libcpprest.2.7.dylib  
web::http::client::http_client::build_pipeline(web::uri const&, web::http::client::http_client_config const&) + 81
7   libcpprest.2.7.dylib  
web::http::client::http_client::http_client(web::uri const&, web::http::client::http_client_config const&) + 30

**Comment by ras0219-msft** [comment]
Can you map this back to source lines?

What was the crash? Null dereference?

**Comment by glukacsy** [comment]
Unfortunately that's all I have. The crash happened on OS X so no crash dump, all we have is the Crashalytics stactrace (as per above).

**Comment by glukacsy** [comment]
Here is a bit larger stacktrace from a new instance of the same crash:

Thread : Crashed: com.apple.root.default-qos
0  libcpprest.2.7.dylib           0x10713d6a2 boost::asio::detail::resolver_service_base::start_resolve_op(boost::asio::detail::task_io_service_operation*) + 162
1  libcpprest.2.7.dylib           0x1071deec9 void boost::asio::detail::resolver_service<boost::asio::ip::tcp>::async_resolve<boost::_bi::bind_t<void, boost::_mfi::mf2<void, web::http::client::details::asio_context, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::list3<boost::_bi::value<std::__1::shared_ptr<web::http::client::details::asio_context> >, boost::arg<1> (*)(), boost::arg<2> (*)()> > >(std::__1::shared_ptr<void>&, boost::asio::ip::basic_resolver_query<boost::asio::ip::tcp> const&, boost::_bi::bind_t<void, boost::_mfi::mf2<void, web::http::client::details::asio_context, boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp> >, boost::_bi::list3<boost::_bi::value<std::__1::shared_ptr<web::http::client::details::asio_context> >, boost::arg<1> (*)(), boost::arg<2> (*)()> >&) + 121
2  libcpprest.2.7.dylib           0x1071c2367 web::http::client::details::asio_context::start_request()::'lambda'(std::__1::shared_ptr<web::http::client::details::asio_context>)::operator()(std::__1::shared_ptr<web::http::client::details::asio_context>) const + 3975
3  libcpprest.2.7.dylib           0x1071bae70 web::http::client::details::asio_context::start_request() + 752
4  libcpprest.2.7.dylib           0x1071ba2ba web::http::client::details::asio_client::send_request(std::__1::shared_ptr<web::http::client::details::request_context> const&) + 282
5  libcpprest.2.7.dylib           0x1071c0998 std::__1::__function::__func<web::http::client::details::_http_client_communicator::async_send_request(std::__1::shared_ptr<web::http::client::details::request_context> const&)::'lambda'(), std::__1::allocator<web::http::client::details::_http_client_communicator::async_send_request(std::__1::shared_ptr<web::http::client::details::request_context> const&)::'lambda'()>, void ()>::operator()() + 104
6  libcpprest.2.7.dylib           0x1070c64f3 std::__1::__function::__func<pplx::details::_MakeVoidToUnitFunc(std::__1::function<void ()> const&)::'lambda'(), std::__1::allocator<pplx::details::_MakeVoidToUnitFunc(std::__1::function<void ()> const&)::'lambda'()>, unsigned char ()>::operator()() + 19
7  libcpprest.2.7.dylib           0x1071c06ab pplx::task<unsigned char>::_InitialTaskHandle<void, web::http::client::details::_http_client_communicator::async_send_request(std::__1::shared_ptr<web::http::client::details::request_context> const&)::'lambda'(), pplx::details::_TypeSelectorNoAsync>::_Init(pplx::details::_TypeSelectorNoAsync) const + 171
8  libcpprest.2.7.dylib           0x1071c04a3 pplx::details::_PPLTaskHandle<unsigned char, pplx::task<unsigned char>::_InitialTaskHandle<void, web::http::client::details::_http_client_communicator::async_send_request(std::__1::shared_ptr<web::http::client::details::request_context> const&)::'lambda'(), pplx::details::_TypeSelectorNoAsync>, pplx::details::_TaskProcHandle>::invoke() const + 35
9  libcpprest.2.7.dylib           0x10708dc03 pplx::details::_TaskProcHandle::_RunChoreBridge(void*) + 19
10 libdispatch.dylib              0x7fff90633e73 _dispatch_client_callout + 8
11 libdispatch.dylib              0x7fff90636dc7 _dispatch_root_queue_drain + 935
12 libdispatch.dylib              0x7fff90636a1c _dispatch_worker_thread3 + 91
13 libsystem_pthread.dylib        0x7fff90e59a9d _pthread_wqthread + 729
14 libsystem_pthread.dylib        0x7fff90e573dd start_wqthread + 13
