### ISSUE TITLE
Blocking issue for azure-storage-cpp upgrading to CPPRest version 2.10.2.

### ISSUE THREAD

**Issue by katmsft** [Microsoft/cpprestsdk#804]
Recently we are trying to upgrade CPPRest’s version to 2.10.2, and we found a blocking issue.

For Azure Storage REST API, ‘Content-Encoding’ has been a property for Blob and File that user can use themselves to store the encoding of content. This header will be returned in multiple API calls, even when the request method is ‘HEAD’, when there should be no content returned in the response body.

In version 2.10.0 of CPPRest, compression/decompression is supported with the code snippet below in [http/client/http_client_winhttp.cpp](https://github.com/Microsoft/cpprestsdk/blob/master/Release/src/http/client/http_client_winhttp.cpp#L1374):
```
// If the response body is compressed we will read the encoding header and create a decompressor object which will later decompress the body
utility::string_t encoding;
if (web::http::details::compression::stream_decompressor::is_supported() && response.headers().match(web::http::header_names::content_encoding, encoding))
{
    auto alg = web::http::details::compression::stream_decompressor::to_compression_algorithm(encoding);

    if (alg != web::http::details::compression::compression_algorithm::invalid)
    {
        p_request_context->decompressor = std::make_unique<web::http::details::compression::stream_decompressor>(alg);
    }
    else
    {
        utility::string_t error = U("Unsupported compression algorithm in the Content Encoding header: ");
        error += encoding;
        p_request_context->report_exception(http_exception(error));
    }
}
```
So when our user sets the blob’s or file’s content encoding to whatever value that is not a valid `web::http::details::compression::compression_algorithm`, an exception will be thrown when retrieving the properties of such blob or file.

There is no way we can bypass this decompression, since it checks all the response headers on every platform except MacOS for `Content-Encoding`. The only solution is to modify the code and create an API that changes the if statement like this:
```
if (web::http::details::compression::stream_decompressor::is_supported() && 
    !web::http::details::compression::stream_decompressor::ignore_decompression() &&
    response.headers().match(web::http::header_names::content_encoding, encoding))
```
Also, we found that the method `report_exception` calls [`finish()`](https://github.com/Microsoft/cpprestsdk/blob/master/Release/src/http/client/http_client_winhttp.cpp#L262), but does not return, and if the request method is `HEAD`, `request_context->complete_request(0)` will be called that calls `finish()` again, suppressing the error of unsupported compression algorithm but throws error in [line](https://github.com/Microsoft/cpprestsdk/blob/master/Release/src/http/client/http_client_winhttp.cpp#L265) `assert(m_self_reference != nullptr)`

Please be aware, that this is a blocking issue for us to release our next version needs to support OpenSSL 1.1.0 as well. We cannot use version 2.9.1 since it does not support OpenSSL 1.1.0, and we cannot use 2.10.0-2.10.2 because of the mentioned issue.

**Comment by BillyONeal** [comment]
Was fixed sometime before 2.10.6.
