### ISSUE TITLE
SSL error: WINHTTP_CALLBACK_STATUS_FLAG_CERT_REV_FAILED failed to check revocation status. 

### ISSUE THREAD

**Issue by sinall** [Microsoft/cpprestsdk#808]
It happens when using cpprestsdk-2.10.2 http_client to access a https website on Windows10.

How to fix it?

**Comment by sinall** [comment]
#664

**Comment by BillyONeal** [comment]
Closing as a dupe of #664

**Comment by brennanmh** [comment]
This question doesn't seem like a dupe of https://github.com/Microsoft/cpprestsdk/issues/664

#664 is about disabling checking, not how to FIX the problem.
