### ISSUE TITLE
Installation problem: can't download boost in vcpkg

### ISSUE THREAD

**Issue by liuliushimonkey** [Microsoft/cpprestsdk#835]
I have the following problem when tried to install cpprestsdk in vcpkg:
I'm not using a proxy. Can you please help? It seems that vcpkg tried to download boost from https://github.com/boostorg/preprocessor/archive yet this link is not available. Thank you!

-- Downloading https://github.com/boostorg/preprocessor/archive/boost-1.67.0.tar
.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:151 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/is
sues

**Comment by liuliushimonkey** [comment]
vcpkg solved this pb, it works now

**Comment by zhaihm** [comment]
@liuliushimonkey Which vcpkg version did you use to solve this issue? I'm using version 2019.09.12 and having the same problem.
