### ISSUE TITLE
OpenSSL and Boost on Windows Phone 8.1

### ISSUE THREAD

**Issue by rinopazzo** [Microsoft/cpprestsdk#84]
We are working on a cross-platform core for a mobile application written in C++.
We are using the NuGet package of cpprestsdk in a Windows Phone Runtime Component written in C++.
In our code we would use boost and openssl.

For example, we would use this:
`#include <openssl/rsa.h>`
but if we use it, we receive an error (not found).
Instead on iOS and Android it works.

Is there a way to use openssl and boost included in cpprestsdk lib in WinRT?

**Comment by ras0219-msft** [comment]
When built against WinRT, we do not use Boost or Openssl.

To ask for support for Boost/OpenSSL on winrt, you probably should contact the respective projects.
