### ISSUE TITLE
Problem building boost-regex

### ISSUE THREAD

**Issue by Vicomp** [Microsoft/cpprestsdk#841]
...
Additional packages (*) will be modified to complete this operation.
Starting package 1/87: boost-regex:x86-windows
Building package boost-regex[core]:x86-windows...
-- Using cached D:/_DOWNLOADS/vcpkg/vcpkg-master/downloads/boostorg-regex-boost-1.67.0.tar.gz
-- Using source at D:/_DOWNLOADS/vcpkg/vcpkg-master/buildtrees/boost-regex/src/ost-1.67.0-d36604157f
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: D:/_DOWNLOADS/vcpkg/vcpkg-master/installed/x86-windows/tools/boost-build/b2.exe;--stagedir=D:/_DOWNLOADS/vcpkg/vcpkg-master/buildtrees/boost-regex/x86-windows-rel/stage;--build-dir=D:/_DOWNLOADS/vcpkg/vcpkg-master/buildtrees/boost-regex/x86-windows-rel;--user-config=D:/_DOWNLOADS/vcpkg/vcpkg-master/buildtrees/boost-regex/x86-windows-rel/user-config.jam;-j8;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="D:/_DOWNLOADS/vcpkg/vcpkg-master/installed/x86-windows/include";-sBZIP2_INCLUDE="D:/_DOWNLOADS/vcpkg/vcpkg-master/installed/x86-windows/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=32;architecture=x86;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="D:/_DOWNLOADS/vcpkg/vcpkg-master/installed/x86-windows/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="D:/_DOWNLOADS/vcpkg/vcpkg-master/installed/x86-windows/lib";variant=release;debug-symbols=on
    Working Directory: D:/_DOWNLOADS/vcpkg/vcpkg-master/buildtrees/boost-regex/src/ost-1.67.0-d36604157f/build
    See logs for more information:
      D:\_DOWNLOADS\vcpkg\vcpkg-master\buildtrees\boost-regex\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x86-windows/share/boost-build/boost-modular-build.cmake:231 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:71 (include)

Error: Building package boost-regex:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x86-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.

D:\_DOWNLOADS\vcpkg\vcpkg-master>

**Comment by BillyONeal** [comment]
You should contact vcpkg, not us :). It's possible you don't have a compiler installed.
