### ISSUE TITLE
UWP server implementation

### ISSUE THREAD

**Issue by Liastre** [Microsoft/cpprestsdk#858]
Hello, I've tried to use your SDK to create server using web::http::experimental::listener and seems it's not supported for UWP yet: https://github.com/Microsoft/cpprestsdk/blob/e8dda215426172cd348e4d6d455141f40768bf47/Release/include/cpprest/http_listener.h#L24
Are you gonna extend this namespace to UWP in future, or is there another solution to rise server? Thank you.

**Comment by BillyONeal** [comment]
As far as I can tell this doesn't appear to be possible, as WinRT has no server API.
