### ISSUE TITLE
compile error for a program which sends a GET HTTP request on a Ubuntu

### ISSUE THREAD

**Issue by danielxiong** [Microsoft/cpprestsdk#865]
Hello,
I am trying to run the cpp-rest-sdk-based test program to send a GET HTTP request on a Ubuntu 16.04 (in VMware workstation, Win10 64bit). 
I have followed the [steps in "How to setup, build, and run tests on Linux"](https://github.com/Microsoft/cpprestsdk/wiki/How-to-build-for-Linux)

All the steps go all right, but I have encountered a build error in Step 7.
Here is my [main.cpp file](https://github.com/danielxiong/cpprestsdkTest/blob/master/main.cpp):

Here is the [output ](https://github.com/danielxiong/cpprestsdkTest/blob/master/gpp_out.txt)where I run " g++ -std=c++11 main.cpp -o my_file -lboost_system -lcrypto -lssl -lcpprest
"

Some supplements:
1. "casablanca" git source directory
/home/daniel/daniel/2018_9_12_cpp_rest_sdk/casablanca
2. test program directory
/home/daniel/daniel/2018_9_12_cpp_rest_sdk/test

Could someone please suggest me if something wrong in the above code, and how to fix that?
Could any body share some test code I could run on Ubuntu?
Any help would be appreciated :)
Thanks in advance!

**Comment by hrantzsch** [comment]
Your example program relies on MS Windows specific functions. You can find a test project that works on Linux in the [Getting Started Tutorial](https://github.com/Microsoft/cpprestsdk/wiki/Getting-Started-Tutorial).

**Comment by danielxiong** [comment]
@hrantzsch thanks very much! It works using the example in the [Getting Started Tutorial](https://github.com/Microsoft/cpprestsdk/wiki/Getting-Started-Tutorial).
