### ISSUE TITLE
SSL handshake error in test_runner

### ISSUE THREAD

**Issue by yxiang92128** [Microsoft/cpprestsdk#876]
Please help a newbie. Any hints would be helpful. 

I followed the following procedure to install cpprest on my Ubuntu 16.04.5 LTS system. 
https://github.com/Microsoft/cpprestsdk/wiki/How-to-build-for-Linux

And tried to execute:
./test_runner *_test.so

And here is what I got as a SSL handshake error. But am I missing here please?
Loaded libhttpclient_test.so...
=== Running tests from: <static> ===
=== Running tests from: libhttpclient_test.so ===
Starting test case authentication_tests:empty_username_password...
Test case authentication_tests:empty_username_password ^[[1;32mPASSED
^[[0mStarting test case authentication_tests:auth_no_data...
Test case authentication_tests:auth_no_data ^[[1;32mPASSED
^[[0mStarting test case authentication_tests:unsuccessful_auth_with_basic_cred...
Test case authentication_tests:unsuccessful_auth_with_basic_cred ^[[1;32mPASSED
^[[0mStarting test case authentication_tests:set_user_options_asio_http...
Test case authentication_tests:set_user_options_asio_http ^[[1;32mPASSED
^[[0mStarting test case authentication_tests:set_user_options_asio_https...
^[[1;31m/var/opt/home/yang/casablanca/Release/tests/functional/http/client/authentication_tests.cpp:696: error: Failure in set_user_options_asio_https: Unhandled exception: **Error in SSL handshake FAILED**
^[[0m^[[1;31mTest case authentication_tests:set_user_options_asio_https FAILED

Thanks,

Yang

**Comment by yxiang92128** [comment]
self-solved. All it required is:
export SSL_CERT_DIR=/etc/ssl/certs

**Comment by crusader-mike** [comment]
See: https://github.com/microsoft/cpprestsdk/issues/929#issuecomment-635587905
