### ISSUE TITLE
Install issues in casablanca on RHEL 6.9

### ISSUE THREAD

**Issue by parikshitnangre22** [Microsoft/cpprestsdk#877]
Hi,

Currently we are trying to install cpprest/casablanca on RHEL 6.9 but we are not successful. We also dont have root access. Could you please provide us the steps to install it with root access and also without root access ?

It is also not in source list of our RHEL version.

**Comment by BillyONeal** [comment]
We don't really have RHEL experience; you can see Linux commands we use to build in Pipelines here: https://github.com/Microsoft/cpprestsdk/blob/master/azure-pipelines.yml#L132 -- perhaps that will help. You will need CMake and some dependencies available.
