### ISSUE TITLE
Intermittent Application crash due to Exception code 0xc0000005 in cpprest140_2_9.dll

### ISSUE THREAD

**Issue by basukaushik** [Microsoft/cpprestsdk#878]
Hi,

I need help on an intermittent crash issue I’m getting due to an AV in cpprest140_2_9.dll.

The application is used to transfer files to a server using REST calls thru. CPP REST SDK. There is a continuous flow of incoming files which are being transferred to server. After few hours, the application is crashing due to AV in cpprest140_2_9.dll.

Here is the EventViewer  Log :
--------------------------------------------------------------------------------------------------------------------
Error 9/14/2018 11:29:08 AM Application Error 1000 (100) "Faulting application name:
LDDClientService.exe, version: 5.1.0.0, time stamp: 0x5b7c1893
Faulting module name: cpprest140_2_9.dll, version: 2.9.0.0, time stamp: 0x5993e54c
Exception code: 0xc0000005
Fault offset: 0x0000000000156302
Faulting process id: 0x92c
Faulting application start time: 0x01d44c53c67a2bf0
Faulting application path: D:\Program Files\Lexmark\Solutions\ClientSoftware\LDDClientService.exe
Faulting module path: D:\Program Files\Lexmark\Solutions\ClientSoftware\cpprest140_2_9.dll
Report Id: 10f4ad91-b84c-11e8-811e-005056a76321
Faulting package full name: 
Faulting package-relative application ID: "
--------------------------------------------------------------------------------------------------------------------
Please let me know if you need any further input.

Thanks,
Kaushik Basu

**Comment by BillyONeal** [comment]
Unfortunately we need a more concrete repro in order to investigate something like this.

**Comment by basukaushik** [comment]
[CrashDumps_Dll_And_Pdb.zip](https://github.com/Microsoft/cpprestsdk/files/2497792/CrashDumps_Dll_And_Pdb.zip)

Attaching three crash dump files, corresponding cpprest140d_2_9.dll and cpprest140d_2_9.pdb.

Please let me know if you need any further input.

Thanks,
Kaushik Basu

**Comment by BillyONeal** [comment]
Does it still repro with the current version, 2.10.6?

**Comment by creyes07** [comment]
quisiera saber si se resolvió el problema ya que tengo el mismo problema.
