### ISSUE TITLE
Errors under Windows XP / 2003

### ISSUE THREAD

**Issue by zolll** [Microsoft/cpprestsdk#88]
Hello, 

I am using cpptestsdk in a C++ application, I need also compatibility with Windows XP / 2003 systems. If I use the latest stable 2.8 SDK, compiling my application fails when linking, giving me the following errors:
error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall web::details::win32_encryption::~win32_encryption(void)" (__imp_??1win32_encryption@details@web@@QAE@XZ)
error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall web::details::win32_encryption::win32_encryption(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &)" (__imp_??0win32_encryption@details@web@@QAE@ABV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z)

I can confirm that using the restsdk modules compiled for Windows 2008 and later works fine. Also, I can confirm that the error is given when I do a call to a http_client_config() constructor. If I comment this line, everything compiles fine also with the XP modules. 

Furthermore, compilation fails when using rest sdk 2.6 or 2.8. I can compile under rest sdk 2.3 and 2.4, including Windows XP versions.  

Also, obviously I am using the correct rest DLLs, libraries and includes (I am simply using them from nuGet). Compilation behaves the same in both release and debug compilations. 

Please advise.

Thanks!

**Comment by MariuszKra** [comment]
I have exactly the same problem. Is anything with this?

**Comment by WaydeL** [comment]
I fixed this by adding the CPPREST_TARGET_XP to preprocessor definitions.
