### ISSUE TITLE
Error in SSL handshake with openssl v1.1

### ISSUE THREAD

**Issue by sophia84** [Microsoft/cpprestsdk#900]
I am trying to run the test cases for cpprest with openssl1.1 version and below is the failed output for https and open ssl test cases:
1.
"error: Failure in set_user_options_asio_https: Unhandled exception: Error in SSL handshake FAILED
Test case authentication_tests:set_user_options_asio_https FAILED"

"** authentication_tests:set_user_options_asio_https FAILED ****
**** outside_tests:multiple_https_requests FAILED ****
**** outside_tests:outside_ssl_json FAILED ****
**** authentication_tests:ssl_test FAILED ****
**** authentication_tests:sni_with_older_server_test FAILED ****
**** authentication_tests:sni_explicit_hostname FAILED **"

2. Error in SSL handshake is comming with the url having "https" url but there is no issue with http url.

Could anybody help me resolving the issue.

**Comment by sophia84** [comment]
https://github.com/Microsoft/cpprestsdk/issues/876

**Comment by crusader-mike** [comment]
See: https://github.com/microsoft/cpprestsdk/issues/929#issuecomment-635587905
