### ISSUE TITLE
Building fails on CentOS 7.4 - json_parsing.cpp

### ISSUE THREAD

**Issue by Palooon** [Microsoft/cpprestsdk#917]
Hi,
because there is no package for centos, I wanted to build it myself. 
I was successful with 2.9, but when I used the lastest sources - 2.10.1, I got error in ~/json/json_parsing.cpp file (output is below). 

Commands I used:
`git clone https://github.com/Microsoft/cpprestsdk.git cpprest`
`cd cpprest`
`mkdir Release/build.release`
`cd Release/build.release`
`cmake3 .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DWERROR=OFF -DBUILD_TESTS=OFF -DBUILD_SAMPLES=OFF`
`make -j 2`

Configuration:

> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Check for working C compiler: /bin/cc
> -- Check for working C compiler: /bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /bin/c++
> -- Check for working CXX compiler: /bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Looking for include file xlocale.h
> -- Looking for include file xlocale.h - found
> -- Setting gcc options
> -- websocketpp not found, using the embedded version
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> --   random
> --   system
> --   thread
> --   filesystem
> --   chrono
> --   atomic
> --   date_time
> --   regex
> -- Found OpenSSL: /usr/lib64/libcrypto.so (found suitable version "1.0.2k", minimum required is "1.0.0") 
> -- Performing Test _SSL_LEAK_SUPPRESS_AVAILABLE
> -- Performing Test _SSL_LEAK_SUPPRESS_AVAILABLE - Success
> -- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/administrator/cpprest/Release/build.release

Making:

> Scanning dependencies of target cpprest
> [  3%] Building CXX object src/CMakeFiles/cpprest.dir/http/client/http_client.cpp.o
> [  6%] Building CXX object src/CMakeFiles/cpprest.dir/http/client/http_client_msg.cpp.o
> [ 10%] Building CXX object src/CMakeFiles/cpprest.dir/http/common/http_helpers.cpp.o
> [ 13%] Building CXX object src/CMakeFiles/cpprest.dir/http/common/http_msg.cpp.o
> [ 17%] Building CXX object src/CMakeFiles/cpprest.dir/http/common/http_compression.cpp.o
> [ 20%] Building CXX object src/CMakeFiles/cpprest.dir/http/listener/http_listener.cpp.o
> [ 24%] Building CXX object src/CMakeFiles/cpprest.dir/http/listener/http_listener_msg.cpp.o
> [ 27%] Building CXX object src/CMakeFiles/cpprest.dir/http/listener/http_server_api.cpp.o
> [ 31%] Building CXX object src/CMakeFiles/cpprest.dir/http/oauth/oauth1.cpp.o
> [ 34%] Building CXX object src/CMakeFiles/cpprest.dir/http/oauth/oauth2.cpp.o
> [ 37%] Building CXX object src/CMakeFiles/cpprest.dir/json/json.cpp.o
> [ 41%] Building CXX object src/CMakeFiles/cpprest.dir/json/json_parsing.cpp.o
> /home/administrator/cpprest/Release/src/json/json_parsing.cpp: In instantiation of ‘std::unique_ptr<web::json::details::_Value> web::json::details::JSON_Parser<CharType>::_ParseObject(web::json::details::JSON_Parser<CharType>::Token&) [with CharType = char]’:
> /home/administrator/cpprest/Release/src/json/json_parsing.cpp:1089:40:   required from ‘std::unique_ptr<web::json::details::_Value> web::json::details::JSON_Parser<CharType>::_ParseValue(web::json::details::JSON_Parser<CharType>::Token&) [with CharType = char]’
> /home/administrator/cpprest/Release/src/json/json_parsing.cpp:137:50:   required from ‘web::json::value web::json::details::JSON_Parser<CharType>::ParseValue(web::json::details::JSON_Parser<CharType>::Token&) [with CharType = char]’
> /home/administrator/cpprest/Release/src/json/json_parsing.cpp:1155:39:   required from here
> /home/administrator/cpprest/Release/src/json/json_parsing.cpp:1032:12: error: could not convert ‘obj’ from ‘std::unique_ptr<web::json::details::_Object, std::default_delete<web::json::details::_Object> >’ to ‘std::unique_ptr<web::json::details::_Value>’
>      return obj;
>             ^
> [ 44%] Building CXX object src/CMakeFiles/cpprest.dir/json/json_serialization.cpp.o
> make[2]: *** [src/CMakeFiles/cpprest.dir/json/json_parsing.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [src/CMakeFiles/cpprest.dir/all] Error 2
> make: *** [all] Error 2

Any idea what causes this? Was anyone successful with building newest cpprestsdk on centos7.4?

**Comment by ndjensen** [comment]
I am trying to do the same thing, literally just today, and hitting the same error, which is:

> /common/njensen/git/cpprestsdk/Release/src/json/json_parsing.cpp: In instantiation of ‘std::unique_ptr<web::json::details::_Value> web::json::details::JSON_Parser<CharType>::_ParseObject(web::json::details::JSON_Parser<CharType>::Token&) [with CharType = char]’:
/common/njensen/git/cpprestsdk/Release/src/json/json_parsing.cpp:1089:40:   required from ‘std::unique_ptr<web::json::details::_Value> web::json::details::JSON_Parser<CharType>::_ParseValue(web::json::details::JSON_Parser<CharType>::Token&) [with CharType = char]’
/common/njensen/git/cpprestsdk/Release/src/json/json_parsing.cpp:137:50:   required from ‘web::json::value web::json::details::JSON_Parser<CharType>::ParseValue(web::json::details::JSON_Parser<CharType>::Token&) [with CharType = char]’
/common/njensen/git/cpprestsdk/Release/src/json/json_parsing.cpp:1155:39:   required from here
**/common/njensen/git/cpprestsdk/Release/src/json/json_parsing.cpp:1032:12: error: could not convert ‘obj’ from ‘std::unique_ptr<web::json::details::_Object, std::default_delete<web::json::details::_Object> >’ to ‘std::unique_ptr<web::json::details::_Value>’
     return obj;**
            ^
In file included from /home/njensen/Download/boost_1_68_0/boost/date_time/adjust_functors.hpp:13:0,
                 from /home/njensen/Download/boost_1_68_0/boost/date_time/gregorian/greg_duration_types.hpp:15,
                 from /home/njensen/Download/boost_1_68_0/boost/date_time/gregorian/gregorian_types.hpp:22,
                 from /home/njensen/Download/boost_1_68_0/boost/date_time/posix_time/posix_time_config.hpp:18,
                 from /home/njensen/Download/boost_1_68_0/boost/date_time/posix_time/posix_time_system.hpp:13,
                 from /home/njensen/Download/boost_1_68_0/boost/date_time/posix_time/ptime.hpp:12,
                 from /home/njensen/Download/boost_1_68_0/boost/date_time/posix_time/posix_time_types.hpp:12,
                 from /home/njensen/Download/boost_1_68_0/boost/thread/thread_time.hpp:11,
                 from /home/njensen/Download/boost_1_68_0/boost/thread/lock_types.hpp:18,
                 from /home/njensen/Download/boost_1_68_0/boost/thread/pthread/mutex.hpp:16,
                 from /home/njensen/Download/boost_1_68_0/boost/thread/mutex.hpp:16,
                 from /common/njensen/git/cpprestsdk/Release/src/pch/stdafx.h:62,
                 from /common/njensen/git/cpprestsdk/Release/src/json/json_parsing.cpp:14:

I'm using
* CentOS 7.4
* cpprestsdk master
* cmake 3.12.3
* boost 1.68
* OpenSSL 1.1.1
* zlib 1.2.11

with the compiler flag -DWERROR=OFF.  Any help is appreciated.

**Comment by Palooon** [comment]
I managed to build cpprestsdk 2.10.6 - didn't check, if it actually works though. 
Just do `git reset --hard v2.10.6`

**Comment by ndjensen** [comment]
Thank you.
