### ISSUE TITLE
How can it be used on projects which already have some common auxiliary libs?

### ISSUE THREAD

**Issue by georgii11** [Microsoft/cpprestsdk#918]
I have a C++ project on Windows Desktop which includes zlib and crypto.
So by installing the cpprestsdk (with vcpkg install cpprestsdk cpprestsdk:x64-windows) and using it in my project, I'm getting linker errors (LNK2005) because some stuff from the crypto lib which I am using are already defined in libeay32 from the sdk and stuff from the zlib which I'm using are already defined in the zlib from the sdk.
How can I use the cpprestsdk in this case? Removing the two libs from my main project is not an option.

**Comment by DetlefGolze** [comment]
You can compile CPPREST separately and then add the generated lib to your project (linker tab).

**Comment by BillyONeal** [comment]
It sounds like you're trying to mix a DLL version of OpenSSL with a statically linked version of cpprestsdk or similar? vcpkg should automatically install the right OpenSSL (e.g. libcrypto) bits for you.

**Comment by georgii11** [comment]
Hi,
I already have openSSL (zlib and crypto) linked to my project as static libraries. And I want to use those, not what vcpkg automatically installs for cpprestsdk. 
So I guess the solution could be what DetlefGolze suggested, to compile cpprest separately and link it to my main project. However I don't know how to do that. Are there any steps documented somewhere? I only found steps on how to get it with vcpkg or nuget which both lead to the "already defined" linker errors.
Thanks!

**Comment by DetlefGolze** [comment]
Given that you use Visual Studio, you need to download or clone the source package and then open the solution (*.sln) which matches your Visual Studio version. Then compile the project cpprestsdk140. This will generate cpprest140_2_10.dll and cpprest140_2_10.lib. The DLL must be copied to your application and the lib must be specified in Linker > Input of your project.

Note that this requires that your project is compiled with same settings as CPPREST (e.g. Release, x64 and "Multi-threaded DLL" in C/C++ > Code Generation).

**Comment by BillyONeal** [comment]
@georgii11 As long as you build cpprestsdk with matching library versions to what you use in your application already you shouldn't run into such linking problems...

**Comment by georgii11** [comment]
Sorry for the late reply, my notifications went to spam.
Thanks for your answers!
I'll close the question for now since it's been opened for a while and I'm not sure when I'll get to try out your solution and will get back in case I run into any problems then.
