### ISSUE TITLE
Building for iOS (Xcode 10 + Mojave)

### ISSUE THREAD

**Issue by steven-pearson** [Microsoft/cpprestsdk#934]
New instructions much improved and pretty much works except for a failure in the cpprestsdk build.

-- Setting clang options
CMake Error at cmake/cpprest_find_websocketpp.cmake:14 (message):
  -- websocketpp not found and embedded version not present; try `git
  submodule update --init` and run CMake again
Call Stack (most recent call first):
  src/CMakeLists.txt:68 (cpprest_find_websocketpp)

To resolve, doing...
**git submodule update --init**
...in the casablanca folder fixes the issue.

**Comment by BillyONeal** [comment]
Yep, that's what the error message says :). I fixed the wiki.

**Comment by steven-pearson** [comment]
@BillyONeal the line
git submodule update --init
Should be in Step 5, after
cd casablanca
