### ISSUE TITLE
Square brackets in query strings are not encoded by web::uri::encode_uri 

### ISSUE THREAD

**Issue by TianyiChen** [Microsoft/cpprestsdk#969]
I am using version 2.10.2-6 from Ubuntu 18.04.1 repo. I found square brackets in query strings are not encoded by web::uri::encode_uri. According to RFC 3986:

> A host identified by an Internet Protocol literal address, version 6
>    [RFC3513] or later, is distinguished by enclosing the IP literal
>    within square brackets ("[" and "]").  This is the only place where
>    square bracket characters are allowed in the URI syntax. 

So I feel URL https://www.example.com/?q=a[b] should be encoded to "https://www.example.com/?q=a%5Bb%5D". 

Test program:
```
#include<bits/stdc++.h>
#include<cpprest/http_client.h>
using namespace std;
int main(){
	cerr<<web::uri::encode_uri("https://www.example.com/?q=a[b]")<<endl;
}
```
Output:
`https://www.example.com/?q=a[b]`

Should this be fixed or am I missing something?

**Comment by BillyONeal** [comment]
web::uri::encode_uri with no second parameter defaults to "full URI" mode, which means it only encodes characters that are not allowed anywhere in the URI. It doesn't attempt to parse the URI and encode each bit separately.

(Note that I'm describing what this function does, I don't know why anyone would ever want to do this)P
