### ISSUE TITLE
Continuation task after exception handling throws scheduler error

### ISSUE THREAD

**Issue by acceleratxr** [Microsoft/cpprestsdk#972]
I have code that performs an async task and upon failure (throws exception) starts a new task and chains the all tasks together. This is useful for instance when performing an HTTP request that checks for a resource and if missing (throws exception) creates the resource that could not be found. In the case that the resource is not found, the code works without error. However, any time the resource already exists and no exception is caught an exception is thrown by `::Concurrency::scheduler_ptr _GetScheduler() const` in _pplwin.h_.

Steps to reproduce:
1. Run the following code.
```
return pplx::create_task([=]()
{
    // Do something that doesn't throw an exception.
}).then([](pplx::task<void> prev)
{
	try
	{
		prev.wait();
	}
	catch (...)
	{
		return pplx::create_task([]()
		{
			// Do something else
		});
	}
}).wait();
```

Expected Result:
Task finishes and no error occurs.

Actual Result:
An `Access violation reading location 0xFFFFFFFFFFFFFFFF.` exception is thrown by `::Concurrency::scheduler_ptr _GetScheduler() const` in _pplwin.h_.

**Comment by acceleratxr** [comment]
I discovered a workaround by adding an empty continuation task at the end of the handler outside of the catch statement.

```
return pplx::create_task([=]()
{
	throw std::exception("An error has occurred.");
}).then([](pplx::task<void> prev)
{
	try
	{
		prev.wait();
	}
	catch (...)
	{
		return pplx::create_task([]()
		{
			// Do something else
		});
	}
	
	// Dummy continuation task
	return pplx::create_task([](){});
}).wait();
```

**Comment by BillyONeal** [comment]
Your example has undefined behavior; you're allowing control to reach the end of a non-void function.
