### ISSUE TITLE
[wiki] "How to build for Linux" page mixes make and ninja commands

### ISSUE THREAD

**Issue by dmjones** [Microsoft/cpprestsdk#976]
A recent change to [How to build for Linux](https://github.com/Microsoft/cpprestsdk/wiki/How-to-build-for-Linux) added the ninja build system:

> cmake **-G Ninja** .. -DCMAKE_BUILD_TYPE=Debug

It is therefore necessary to update the installation instructions:

> 6. To install on your system run: sudo make install

should become...

> 6. To install on your system run: sudo **ninja** install

This tripped me up (see #975), although it's probably obvious to Ninja aficionados.

**Comment by dmjones** [comment]
cc @BillyONeal, who authored the change.

**Comment by BillyONeal** [comment]
Fixed! Thanks!

I have no idea how well / if install actually works :P
