### ISSUE TITLE
deal with return value of last task in another function.

### ISSUE THREAD

**Issue by mxito3** [Microsoft/cpprestsdk#995]
hello,here is the question.

```C++
void a()
{
    b()
}
pplx::task<std::shared_ptr< int >> b()
{

}
int main()
{
a();
}
```

now i want to deal with the return value of function b in function a,so i tried as following 
```C++
void a()
{
    b().then({[=] (std::shared_ptr<int> result)
     //deal with result here.
})
}
```

but i get nothing in b().then().so what should i do?

**Comment by BillyONeal** [comment]
Your code example invokes undefined behavior by reaching the end of a non-void function without returning. You would actually need to return something to see anything sane.
