### ISSUE TITLE
2.10.7 link error: http_listener::~http_listener

### ISSUE THREAD

**Issue by RotateAt60MPH** [Microsoft/cpprestsdk#998]
Grrr.  I updated my cpprestsdk x64-windows via vcpkg by mistake.  With NO changes to my code, I now get this link error when I rebuilt my solution under VS 2017:

`
3>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl web::http::experimental::listener::http_listener::~http_listener(void)" (__imp_??1http_listener@listener@experimental@http@web@@QEAA@XZ) referenced in function "public: __cdecl ServiceListener::~ServiceListener(void)" (??1ServiceListener@@QEAA@XZ)
3>ServiceListener.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl web::http::experimental::listener::http_listener::~http_listener(void)" (__imp_??1http_listener@listener@experimental@http@web@@QEAA@XZ)
3>D:\Devel\Development\Project\x64\Debug17\RestService.exe : fatal error LNK1120: 1 unresolved externals
`

I am on 2.10.6-3 on another machine, and of course, I do not have this error so the problem happened sometime between then and now.  After I updated, I made sure I did a 'vcpkg integrate install' to make the libraries 'known' to my projects.

Here's my service listener:

    class ServiceListener
    {
        public:
                            ServiceListener() {}
                            ServiceListener( utility::string_t url );

        pplx::task<void>        open() { return m_listener.open(); }
        pplx::task<void>        close() { return m_listener.close(); }

    private:
        ...
        web::http::experimental::listener::http_listener           m_listener;
    };
`

I went and copied the entire vcpkg directory, which included cpprestsdk 2.10.6-3, onto the 'problem' machine, rebuilt, and the link error went away.

**Comment by BillyONeal** [comment]
That function got moved into the header; so if you still had bits trying to look for it, that means you didn't recompile the bits with the updated headers.

cpprestsdk does not provide ABI compatibility between versions, only API compatibility.

**Comment by RotateAt60MPH** [comment]
So could this be a vcpkg issue?  I'm not cloning or building anything myself - I'm relying on vcpkg for all that.

**Comment by BillyONeal** [comment]
It doesn't sound like a vcpkg issue; it sounds like some stuff in your solution didn't get rebuilt and reconfigured when the vcpkg upgrade happened. Note that if you use CMake support in the IDE a normal "rebuild" doesn't actually do a reconfigure step, so it may be finding things in bad places
