### ISSUE TITLE
Got an exception when running at handler.open().wait() , how to fix it?

### ISSUE THREAD

**Issue by chengshuyi** [Microsoft/cpprestsdk#999]
I have installed cpprestsdk by vcpkg and i once run my program successfully. I dont know why it cant work unexpectedly. Below is my code:
```
int main()
{
	//打开服务器端口8080，并监听http请求
	try
	{
		string_t address = U("http://*:8080");
		uri_builder uri(address);
		auto addr = uri.to_uri().to_string();
		Command handler(addr);
		handler.open().wait();
		ucout << utility::string_t(U("Listening for requests at: ")) << addr << std::endl;
		ucout << U("Press ENTER key to quit...") << std::endl;
		std::string line;
		std::getline(std::cin, line);
		handler.close().wait();
	}
	//异常处理
	catch (const std::exception& ex)
	{
		ucout << U("Exception: ") << ex.what() << std::endl;
		ucout << U("Press ENTER key to quit...") << std::endl;
		std::string line;
		std::getline(std::cin, line);
	}
	return 0;
}
```

Debugging the program, i find it run at `handler.open().wait();` and throw an exception. It's so sad.Below is the print log that i cant read.

![default](https://user-images.githubusercontent.com/10515655/50127553-9c372180-02ac-11e9-9a53-08b3d2129a27.png)

Thanks for any advice!

**Comment by BillyONeal** [comment]
`Command` doesn't appear to be a type provided by this project. It seems like you need to contact whomever owns that?

**Comment by chengshuyi** [comment]
> 
> 
> `Command` doesn't appear to be a type provided by this project. It seems like you need to contact whomever owns that?

Okay!
